### ISSUE TITLE
Convex hull on higher dimensional point sets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1001]
Furthermore, I suggest to extend the `convex_hull` function to also accept higher-dimensional vertices. In this case just create a `polyhedron` and call `removevredundancy!` on it (we can outsource this part from your `VPolytope` code).

_Originally posted by @schillic in https://github.com/JuliaReach/LazySets.jl/pull/953#issuecomment-448545383_

**Comment by schillic** [comment]
What is the difference to #952?

**Comment by mforets** [comment]
In #952 we're adding `remove_redundant_vertices(::VPolytope)` and `convex_hull(::VPolytope, ::VPolytope)`. In this issue we add `convex_hull(::Vector{VN})` for higher dimensional point sets and this entails modifying the existent functions.
