### ISSUE TITLE
Simplify overapproximations API

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1020]
We can simplify the API by making `box_approximation` and `ballinf_approximation` to be aliases (or eliminated them altogether) for `overapproximate(S, Hyperrectangle)` and `overapproximate(S, BallInf)` respectively.

This has the benefit of:

- adding `overapproximate(S, BallInf)`, currently doesn't exist
- when there is a more efficient implementation of an overapproximation, use dispatch. for example, in https://github.com/JuliaReach/LazySets.jl/pull/1019 we add a better box approx for zonotopes, and adding `overapproximate(S, Hyperrectangle)` will use it

Note: the test added in [this PR](https://github.com/JuliaReach/LazySets.jl/pull/1019) needs to be adapted.

**Comment by schillic** [comment]
This was first resolved in #1556 and then swapped in #2422.
