### ISSUE TITLE
Zonotope has redundant vertices

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1021]
```julia
julia> Z = Zonotope([0., 0.], [1. 0. 1.; 0. 1. 1.]);

julia> vertices_list(Z)
8-element Array{Array{Float64,1},1}:
 [2.0, 2.0]  
 [0.0, 2.0]  
 [2.0, 0.0]  
 [0.0, 0.0]  
 [0.0, 0.0]  
 [-2.0, 0.0] 
 [0.0, -2.0] 
 [-2.0, -2.0]
```
The origin is both a duplicate and is even inside.
It turns out that `2^p` is only an upper bound (and probably a lower bound is `2p`).
Related: #593 and #561

**Comment by mforets** [comment]
About this, i would suggest to add a convex hull before returning from `vertices_list(::Zonotope)`.

**Comment by schillic** [comment]
In [1] there is an estimation of the number of vertices if the zonotope is in general position. The paper also presents a randomized algorithm to enumerate the vertices. It also gives two alternatives: use our algorithm followed by a convex hull, or use the algorithm from [2].
I suggest that we use the convex hull here and defer the implementation of [2] to #1404.

[1] https://arxiv.org/abs/1602.06620
[2] http://dx.doi.org/10.1016/j.ejor.2003.04.011
