### ISSUE TITLE
Implement convex hull array

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#103]
Implement the symbolic convex hull array operator such that

```julia
julia> C = ConvexHullArray([Singleton([1.0, 0.5]), Singleton([1.1, 0.2]), Singleton([1.4, 0.3]), Singleton([1.7, 0.5]), Singleton([1.4, 0.8])])
```

works (alias: `CHArray`). The choice `xyzArray` follows the nomenclature used previously for `MinkowskiSum` and `CartesianProduct`.

**Comment by schillic** [comment]
Would it not be `ConvexHullArray`?

**Comment by mforets** [comment]
yes 👍

**Comment by schillic** [comment]
Oh sorry, this is what you proposed, I only saw the alias...

**Comment by mforets** [comment]
actually my first comment was edited :)
