### ISSUE TITLE
Add meaningful test for linear_map

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1036]
#1035 fixed a bug where the array of constraints contained `undef`s. The [unit test](https://github.com/JuliaReach/LazySets.jl/blob/master/test/unit_Polytope.jl#L116) only checks if the method does not crash. To avoid such problems in the future, we should at least test that each constraint is indeed a constraint.

**Comment by mforets** [comment]
One could make a simple but meaningful test in such situation by checking for example that the image of an element is in the linear map:

```julia
M = N[2 3; 1 2]                             # invertible matrix
MP = linear_map(N[2 3; 1 2], P)  # check concrete linear map
@test M * an_element(P) ∈ MP   # check that the image of an element is in the linear map  
```

**Comment by schillic** [comment]
These tests have been added starting in #1080.
https://github.com/JuliaReach/LazySets.jl/blob/e4654d790332389d62f9854b652ffa35c925aa0d/test/unit_Polytope.jl#L120
