### ISSUE TITLE
Decomposed intersection for CartesianProductArray

### ISSUE THREAD

**Issue by kostakoida** [JuliaReach/LazySets.jl#1041]
<img width="492" alt="screen shot 2019-01-25 at 12 29 07 am" src="https://user-images.githubusercontent.com/7996008/51681299-45a1cd80-2038-11e9-8b7a-02ac6e54df22.png">

 We preprocess our system in such way,  we know what blocks are necessary to make an intersection with guard or invariant. Then we apply new intersection method(LazySets.jl) of two CartesianProductArray`s(which are represent our decomposed RSets and decomposed constraints of guard or invariant). It is important to note, that our RSets and constraints should be decomposed in the same number of blocks for CartesianProductArray.

**Comment by mforets** [comment]
@kostakoida Thanks for the write-up.

Can you add a minimal example to imagine how we plan to actually implement this?

Is it going to be a concrete intersection algorithm (see [here](https://juliareach.github.io/LazySets.jl/latest/lib/binary_functions.html#LazySets.intersection-Union{Tuple{N},%20Tuple{Interval{N,IN}%20where%20IN%3C:AbstractInterval{N},Interval{N,IN}%20where%20IN%3C:AbstractInterval{N}}}%20where%20N%3C:Real)), or an algorithm to calculate the support function of a lazy intersection more efficiently (see [here](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Intersection.jl#L245))?

**Comment by kostakoida** [comment]
> What function(s) need to be provided by this package that are of independent interest of this reachability algorithm?
We should implement new intersection algorithm to compute intersection between two CartesianProductArrays smartly(only between required blocks)
 
> Are the intersections appearing in lines 20, 21, 23 all lazy? (`intersect` in LazySets)
Yes
