### ISSUE TITLE
Shared wiki for the JuliaReach organization

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#105]
This [is not officially supported](https://webapps.stackexchange.com/questions/107387/wiki-for-an-organization-in-github-possible). But there is a [proposed solution](https://brendancleary.com/2013/03/08/including-a-github-wiki-in-a-repository-as-a-submodule/).

**Comment by mforets** [comment]
other things that it would be useful to share are: 

- label tags colors
-  the common assets eg. `/docs/src/assets/juliareach.css`

**Comment by schillic** [comment]
> label tags colors

There are several approaches for this:
* [1](https://github.com/destan/github-label-manager) with a [blog entry](https://medium.com/@dtinth/how-to-copy-github-labels-from-one-project-to-another-1857adc73e0f)
* [2](https://github.com/jhare/github-label-copy)
* [3](https://github.com/jvandemo/copy-github-labels)

> the common assets

I am not sure if this is possible, but they usually do not change anyway.

**Comment by mforets** [comment]
The "official" source of `juliareach.css` and other assets is now [JuliaReachTemplatePkg](https://github.com/JuliaReach/JuliaReachTemplatePkg). For other conventions we write them on [JuliaReachDevDocs](https://github.com/JuliaReach/JuliaReachDevDocs).
