### ISSUE TITLE
Concrete linear map of a halfspace

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1066]
```julia
julia> M = rand(2, 2); H = rand(HalfSpace, dim=2);

julia> linear_map(M, H)
ERROR: MethodError: no method matching linear_map(::Array{Float64,2}, ::HalfSpace{Float64})

Closest candidates are:
  linear_map(::AbstractArray{N<:Real,2}, ::AbstractPolygon{N<:Real}; output_type) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractPolygon.jl:2
07
  linear_map(::AbstractArray{N<:Real,2}, ::ZeroSet{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/ZeroSet.jl:178
  linear_map(::AbstractArray{N<:Real,2}, ::AbstractSingleton{N<:Real}) where N<:Real at /Users/forets/.julia/dev/LazySets/src/AbstractSingleton.jl:166
  ...
Stacktrace:
 [1] top-level scope at none:0

julia> HPolyhedron([H])
HPolyhedron{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([0.286447, -1.76997], -0.666374)])

julia> linear_map(M, HPolyhedron([H]))
HPolyhedron{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([-2.16862, 1.86982], -0.666374)])
```

**Comment by schillic** [comment]
What about the following idea? Under certain conditions (*to be found*), we can compute two vertices `x` and `y` where `x` is on the boundary (such that `a * x = b`) and `y = x + a` is along the normal vector. Then we apply the map to those vertices to obtain `x' = M * x` and `y' = M * y`. Finally, we obtain a new `HalfSpace` with `a' = y' - x'` and `b' = a' * x'`.
Now there are cases where this does not work. The matrix `[1. 0.; 0. 0.]` for instance turns a half-space into a hyperplane or even just a ray for the half-space `x >= c`.

    Tentative precondition: `M` is injective.

Is "is injective" equivalent to "is square and has no zero-row"?
