### ISSUE TITLE
Add option to linear map of abstract polytope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1092]
Proposal: add an option `use_constraints::Bool` such that `linear_map(M, X)` uses the current implementation (vertices) if it is false, and otherwise it uses the implementation for `HPolytope` (check for invertibility criterion in which case the linear map is applied using its inverse).

This is useful for sets such that their constraints list is available or can be computed more easily than its vertices:

```julia
julia> n = 20; M = rand(n, n);

julia> H = rand(Hyperrectangle, dim=n);

julia> @time linear_map(M, H);  # current master
  1.652406 seconds (4.19 M allocations: 920.006 MiB, 12.87% gc time)

julia> @time linear_map(M, convert(HPolytope, H)); # using the hpolytope implementation
  0.000282 seconds (438 allocations: 57.891 KiB)
```

**Comment by schillic** [comment]
Agreed, but I slightly prefer `use_vertices` because the constraint version may still fall back to the vertices.
