### ISSUE TITLE
An element for HPolytope is not type stable

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1105]
```julia
julia> P
HPolytope{Rational{Int64}}(HalfSpace{Rational{Int64}}[HalfSpace{Rational{Int64}}(Rational{Int64}[1//1, 0//1], 1//1), HalfSpace{Rational
{Int64}}(Rational{Int64}[0//1, 1//1], 1//1), HalfSpace{Rational{Int64}}(Rational{Int64}[-1//1, 0//1], 1//1), HalfSpace{Rational{Int64}}
(Rational{Int64}[0//1, -1//1], 1//1)])

julia> an_element(P)
2-element Array{Float64,1}:
 1.0
 0.0
```

**Comment by mforets** [comment]
Idea: calculate the bounding box (in floating point, it doesn't matter), then compute the center of this box (as a rational) and check if it belongs to `P`. If it does not, subdivide the box and try repeat. Downside: sounds costly.

Otherwise: compute the [Chebyshev center](https://en.wikipedia.org/wiki/Chebyshev_center), convert to rational and check membership. There is already a `chebyshevcenter` [in Polyhedra](https://juliapolyhedra.github.io/Polyhedra.jl/latest/utilities.html#Polyhedra.chebyshevcenter) that performs this calculation.

**Comment by schillic** [comment]
What about we use [`:Exact`](https://github.com/JuliaOpt/GLPKMathProgInterface.jl/blob/master/src/GLPKInterfaceLP.jl#L25) for `Rational`s, just as we do for `CDDLib`? This could potentially solve a lot of other issues.

**Comment by mforets** [comment]
If we can get `σ(sparsevec([1], [one(N)], dim(S)), S)` to return a rational if `N` is `Rational{Int}`, that would be the most proper way, yes. Look we don't pass any option to `GLPKSolverLP` [here](https://github.com/JuliaReach/LazySets.jl/blob/master/src/HPolyhedron.jl#L177), so it's at least worth a try.

**Comment by schillic** [comment]
> Look we don't pass any option to GLPKSolverLP here, so it's at least worth a try.

Yes, we should outsource the creation of the `GLPKSolverLP` to a function.

**Comment by schillic** [comment]
A possibly more robust implementation is to solve the feasibility LP, and the solver will return a witness automatically.

**Comment by schillic** [comment]
And yet another (inefficient) approach is to use the V-representation. We currently use the same implementation there, but we could change it to return the *average* point, `1/m * ∑_i=1^m v_m`.

**Comment by schillic** [comment]
> If we can get `σ(sparsevec([1], [one(N)], dim(S)), S)` to return a rational if `N` is `Rational{Int}`, that would be the most proper way, yes. Look we don't pass any option to `GLPKSolverLP` [here](https://github.com/JuliaReach/LazySets.jl/blob/master/src/HPolyhedron.jl#L177), so it's at least worth a try.

I just tested: both the arguments and the solver are `Rational` but we get a `Float64` solution out. I guess that we cannot preserve the type using our current solver backend.

**Comment by schillic** [comment]
To summarize the valid proposals:
1. use method for floats, convert to rational, and check membership; if it does not work, fall back to one of the proposals below
2. compute center of bounding box (which mathematically is always inside the set but could suffer from the same problem that we may need to do a conversion)
3. compute Chebyshev center

#1108 used 1. and 3. which I think was good. After #1696 I suggest to re-implement #1108 to finally close this issue.

**Comment by schillic** [comment]
We do not handle LP-solver conversions (see #1711).
