### ISSUE TITLE
Outsource package-requirement messages to a central place

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1109]
We have quite a few of these guys, sometimes with slightly different text:
```julia
@assert isdefined(@__MODULE__, :Polyhedra) "this function requires the package 'Polyhedra'"
```
I propose to outsource them to a central function to make the code simpler.
Maybe we should even write a macro, e.g., `@required` (`@require` is already taken by `Requires`).

**Comment by mforets** [comment]
Yes, a macro `@requires_polyhedra`,  or `@requires(:Polyhedra)` that displays a message similar to `"this function needs the package 'Polyhedra'; do 'using Polyhedra'" and then try again` would centralize those messages in one place.

**Comment by schillic** [comment]
> `@requires_polyhedra`

I prefer to have a generic macro, as in your second proposal. `Polyhedra` is not the only optional package.
