### ISSUE TITLE
Add AbstractAffineMap interface

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1113]
Subtypes: `AffineMap` (#1111), `LinearMap`, `ExponentialMap`, `ResetMap` (#1112), `Translation` (#882); (`ExponentialProjectionMap` ?).

To make use of the interface, all subtypes should provide a method to obtain the `A` matrix and the `b` vector. Then the functionality for affine maps can be written generically and automatically be used by all subtypes (as usual).

A useful function is `apply(M::AbstractAffineMap, x::AbstractVector)` (and the `!` version).

**Comment by mforets** [comment]
> A useful function is apply(M::AbstractAffineMap, x::AbstractVector) (and the ! version).

Ok, i opened a new issue, https://github.com/JuliaReach/LazySets.jl/issues/1997
