### ISSUE TITLE
SymmetricIntervalHull of unbounded set

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1116]
```julia
julia> S = SymmetricIntervalHull(HPolyhedron([HalfSpace([1., 1.], 1.)]));

julia> ρ([1., 0.], S)
Inf

julia> isbounded(S)
true

julia> vertices_list(S)
4-element Array{Array{Float64,1},1}:
 [Inf, Inf]  
 [-Inf, Inf] 
 [Inf, -Inf] 
 [-Inf, -Inf]
```
The problem is that `SymmetricIntervalHull` is an `AbstractHyperrectangle`, but this is not true if the wrapped set is unbounded.
I see the following ways to fix this:
* Let `SymmetricIntervalHull` not inherit from this interface anymore. This implies that we lose many convenient implementations.
* (my favorite) Clarify in the documentation that the results are undefined if the wrapped set is unbounded.

**Comment by mforets** [comment]
Yes, i agree with option (2).

We could as well assert that the wrapped set is bounded, in the creation of a new `SymmetricIntervalHull`.

Related: For some set types `isbounded` is fast, while for others it is not (for some types we use only the type information, and for others we use also the value information). Perhaps we should clarify this, e.g. letting `isbounded` work on type by default, but have an option to work it out on each instance.

**Comment by schillic** [comment]
> letting `isbounded` work on type by default

This does not work because of lazy operations. We do not have an `unknown` option, only `true` and `false`.
