### ISSUE TITLE
Constraints list should return a copy

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1118]
I think that this is an odd behavior, and that `constraints_list(::HPoly)` should return a copy:

```julia
julia> using LazySets
[ Info: Recompiling stale cache file /Users/forets/.julia/compiled/v1.1/LazySets/NjrGc.ji for LazySets [b4f0291d-fe17-52bc-9479-3d1a3
43d9043]

julia> P = rand(HPolygon)

HPolygon{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([0.946699, 1.77815], -1.56807), HalfSpace{Float64}([-0.795953, 0.138196], 1.6
8976), HalfSpace{Float64}([-0.157028, -0.0725113], 0.390089), HalfSpace{Float64}([-0.605762, -0.710484], 1.81739), HalfSpace{Float64}
([0.612043, -1.13335], 0.628364)])

julia> c = constraints_list(P)
5-element Array{HalfSpace{Float64},1}:
 HalfSpace{Float64}([0.946699, 1.77815], -1.568071584840482)
 HalfSpace{Float64}([-0.795953, 0.138196], 1.6897635928694956)
 HalfSpace{Float64}([-0.157028, -0.0725113], 0.3900886827152788)
 HalfSpace{Float64}([-0.605762, -0.710484], 1.817389057643565)
 HalfSpace{Float64}([0.612043, -1.13335], 0.6283636644212813)

julia> pop!(c)
HalfSpace{Float64}([0.612043, -1.13335], 0.6283636644212813)

julia> constraints_list(P)
4-element Array{HalfSpace{Float64},1}:
 HalfSpace{Float64}([0.946699, 1.77815], -1.568071584840482)
 HalfSpace{Float64}([-0.795953, 0.138196], 1.6897635928694956)
 HalfSpace{Float64}([-0.157028, -0.0725113], 0.3900886827152788)
 HalfSpace{Float64}([-0.605762, -0.710484], 1.817389057643565)
```

**Comment by schillic** [comment]
Let us make it optional. If the user knows that the constraints are not modified, this is more efficient.

**Comment by mforets** [comment]
OK but accessing the field should be preferred to make the modifications in-place. 

The possible source of confusion is to expect that the modification applies for all sets that have a constraints list. For instance,  if i `pop!` from the `constraints_list(::BallInf)`, or a `Hyperrectangle`, it does not affect them at all.

**Comment by mforets** [comment]
I think that the current behavior is that getter functions (such as `constraints_list`, or `vertices_list`) do *not* return a copy. Hence I suggest to close this issue.

**Comment by schillic** [comment]
I see the problem. Ideally we would have a parameter to control whether you get a copy or not. For sets like `Hyperrectangle` the behavior is identical. For sets like `HPolytope` you may want a fast and a safe version. I am fine with closing or adding the parameter.

**Comment by schillic** [comment]
I guess we can close this. We also have this phenomenon in other functions (that a stored vector etc. is returned and can be accidentally modified). It would be nice to have a solution, but I think that would mean to add the keyword `copy` to _all_ methods, which seems a lot of work.
