### ISSUE TITLE
Revise supp function of lazy intersection of polyhedra

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1127]
The support function of the lazy intersection and polyhedra, [see here](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Intersection.jl#L426) can be possibly handled in a cleaner way using dispatch and the `AbstractPolyhedron` interface.

**Comment by schillic** [comment]
Should we add it to the list in #1078?

**Comment by mforets** [comment]
Yes, i think that goes in that bucket 👍  

(I don't see any line using `AbstractPolyhedron` in [Intersections.jl](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Intersection.jl#L426) indicating that it should be added and simplify a bunch of cases).

**Comment by schillic** [comment]
I think this is resolved.

https://github.com/JuliaReach/LazySets.jl/blob/679ee52bc323418b2afeb71eb275c8b10c19e907/src/LazyOperations/Intersection.jl#L484-L487
