### ISSUE TITLE
Add manual for set operations

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#113]
Add a manual page for the new set operations (`∈`, `⊆`, `is_intersection_empty`).

* [ ] operation names with syntax, description, aliases
* [ ] table with available combinations (see [here](https://github.com/JuliaReach/LazySets.jl/issues/69#issuecomment-350864515))
* [ ] examples

**Comment by mforets** [comment]
and also union `∪` that needs to be added (the symbol) would go in the same page.

**Comment by schillic** [comment]
What would be the meaning of `∪`?

**Comment by schillic** [comment]
I was thinking if we want to move the code of the binary functions to new files (`subset.jl`/`intersection.jl`). The reason is that it is not clear where `⊆(::T1, ::T2)` should be, in `T1.jl` or in `T2.jl`. It would also simplify the type files a bit and you can find existing implementations faster (currently you have to search in all files).

**Comment by mforets** [comment]
> What would be the meaning of ∪?

set union. we've got the file `UnionSet.jl`, but it's a rather hidden one, since it is not even included in `LazySets.jl` !

**Comment by schillic** [comment]
>> What would be the meaning of ∪?
>
>set union. we've got the file `UnionSet.jl`, but it's a rather hidden one, since it is not even included in `LazySets.jl` ! 

I see, two remarks:
1. I do not want to have `UnionSet.jl` being a `LazySet` because it is not convex and thus breaks some assumptions.
2. The function `∩` does *not* compute the intersection. It checks if the intersection is empty. Maybe we should rename it, in particular if we want to have a function that computes the intersection.

**Comment by mforets** [comment]
1. agreed. since this is a running assumption in LazySets, we may in the future open another project repo to handle non-convex sets, like an extension of LazySets.

2. yes, we should rename it. we'd need to compute the intersection for applications.

**Comment by schillic** [comment]
1. Programmatically this would be simple: Just define a supertype of `LazySet`. But we should probably instead have an abstract type `ConvexSet` in between, otherwise it will be confusing.
2. Should we create a new issue for this or do it in this one?

**Comment by mforets** [comment]
+1 for new issue

**Comment by schillic** [comment]
added #117

**Comment by schillic** [comment]
My question [here](https://github.com/JuliaReach/LazySets.jl/issues/113#issuecomment-355760013) got lost. We could also add them to the `LazySet.jl` that is soon coming [here](https://github.com/JuliaReach/LazySets.jl/issues/63#issuecomment-355787279), but I think it is better to have new files.

**Comment by mforets** [comment]
> I was thinking if we want to move the code of the binary functions to new files (subset.jl/intersection.jl). The reason is that it is not clear where ⊆(::T1, ::T2) should be, in T1.jl or in T2.jl. It would also simplify the type files a bit and you can find existing implementations faster (currently you have to search in all files).

i like this, i see that having this functionalities gathered in files is convenient.

on the other hand, i think that there are advantages of having the code for sets or operations in independent files, such as with the case of polyhedron (before) that we were to enable/disable (although that was more of a transition), or that there are methods that only make sense for a particular class of set such as `order` for zonotopes.

thus, we may go for something in between. for example, i wouldn't split the `dim` method for each  type into a `dim.jl` file.

**Comment by schillic** [comment]
Right, I was only talking about binary functions, where you cannot clearly say to which type they belong. I am not for splitting `∈` (but also not against it).
