### ISSUE TITLE
Dimension assertion in support function

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1141]
```julia
julia> ρ(rand(2), rand(Hyperrectangle, dim=1))
0.48401586321364154
```

This may be part of a more general discussion about a "safe" mode with assertions activated and an unsafe mode where assertions are off. Assertions are useful working in the REPL but in many cases one would rather deactivate them.

**Comment by schillic** [comment]
Is this a duplicate of #70?

**Comment by mforets** [comment]
Yes, i think that we can merge this into that one.
