### ISSUE TITLE
Type that represents the Complement

### ISSUE THREAD

**Issue by tomerarnon** [JuliaReach/LazySets.jl#1152]
_Not an issue, just a note._

In `NeuralVerification`, we have found it useful to define a `PolytopeComplement` type ([see here](https://github.com/sisl/NeuralVerification.jl/blob/complements/src/utils/problem.jl#L24)). For the most part, all it does is serve as a wrapper for a set that reverses operations that act on it. I.e.`issubset(comp)` becomes `is_intersection_empty(comp.set)` etc.

I don't see any reason why it cannot be used to represent also more complex types like set unions, lazy convex hulls, etc., and maybe it is of some use to you as well, so I though I should mention it.

**Comment by mforets** [comment]
In general it makes sense to take the complement of an `AbstractPolyhedron` (an interface to for sets represented by the intersection of a finite number of halfspaces).

I imagine it can be defined as a struct `SetComplement{N<:Real, PT<:AbstractPolyhedron{N}}`?

**Comment by mforets** [comment]
> I imagine it can be defined as a struct SetComplement{N<:Real, PT<:AbstractPolyhedron{N}}?

The lazy set complement added in #1152 actually wraps *any* LazySet.

**Comment by tomerarnon** [comment]
@mforets, yes, I recently generalized to any LazySet, maybe without all the consequences thought out. It seems like it should be ok, but please let me know if the definition is problematic! @schillic already pointed out a method inaccuracy in [#52](https://github.com/sisl/NeuralVerification.jl/pull/52/)

For our purposes in NeuralVerification, the complement of an AbstractPolyhedron is sufficient (we really only need HalfSpaces, Hyperrectangles, and Polytopes) but we will ultimately adopt your `Complement` type regardless.
