### ISSUE TITLE
Add method to get all concrete subtypes of a given set interface

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1159]
`subtypes` returns concrete and abstract types:

```julia
julia> first(subtypes(LazySet))
AbstractCentrallySymmetric

julia> last(subtypes(LazySet))
ResetMap
```
In some cases it is useful to be able to ask for all concrete subtypes of a given set interface.

**Comment by schillic** [comment]
We can outsource [this piece of code](https://github.com/JuliaReach/LazySets.jl/blob/ae4e196f3513299c7650382faefcc5c8dbf0ac62/test/check_method_implementation.jl#L51).
