### ISSUE TITLE
"Error: matrix is not square" in inv(M) in AbstractPolyhedron linear_map 

### ISSUE THREAD

**Issue by tomerarnon** [JuliaReach/LazySets.jl#1163]
The problem:
```julia
M = rand(5,4)
LazySets.isinvertible(M) #true
inv(M) #error
```

Should `linear_map` with `check_invertibility = true` use `pinv` instead of `inv` to deal with non square matrices?

**Comment by schillic** [comment]
> `LazySets.isinvertible(M)` #true

I think that is already wrong and we should check for square matrices.

> use `pinv` instead of `inv`

```julia
help?> pinv
search: print println pointer printstyled pointer_from_objref sprint isprint typeintersect codepoint atreplinit typemin flipsign

Couldn't find pinv
Perhaps you meant inv, print, pi, Cint, bind, div, in, min, sin, sinc, sind, sinh, sprint, Pipe, sinpi, pairs, pop!, prod or put!
  No documentation found.

  Binding pinv does not exist.
```

What is `pinv`?
Note that if `isinvertible` (correctly) returns `false`, we will use the vertex representation and things should work (but become more slowly, obviously).

**Comment by tomerarnon** [comment]
`pinv` [belongs to LinearAlgebra](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/index.html#LinearAlgebra.pinv). It computes the pseudo inverse. Since it behaves like an inverse, I think linear_map may still be correct using it. Note that the pseudo inverse of a square matrix is just the inverse.

**Comment by schillic** [comment]
I suggest to fix `isinvertible` for now to at least make it not crash.
@mforets: Do you think we want to investigate the pseudoinverse direction?

**Comment by mforets** [comment]
Thanks for the report!

I agree that `pinv` is worth considering as a replacement for `inv`. Alternatively, if the matrix is not square one we can turn off `use_inv` and use left division (we have to code this so it works automatically). From the docs of `?\`,

> For rectangular A the result is the minimum-norm least squares solution computed by a pivoted QR factorization of A and a rank estimate of A based on the R factor.

Example of use: `linear_map(M, H, use_inv=false)`. But we need to fix another bug previously (https://github.com/JuliaReach/LazySets.jl/issues/1165)...

**Comment by tomerarnon** [comment]
Thanks for addressing this so quickly!

Unfortunately, it seems that the behavior of `checksquare` is to throw an error if the matrix is not square, which is counter to the goal here.

I couldn't find a function to just perform the check in Base, but here is one:
```julia
function issquare(M)
    m, n = size(M)
    m == n
end
```

**Comment by tomerarnon** [comment]
Thanks, works on master!

**Comment by mforets** [comment]
👍  As as follow-up issue, https://github.com/JuliaReach/LazySets.jl/issues/1169 proposes to keep the hrep if possible also for the rectangular case (#1164 enforced to use the vrep).
