### ISSUE TITLE
Keep halfspace representation for rectangular linear maps of hyperrectangles

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1169]
With https://github.com/JuliaReach/LazySets.jl/pull/1164 we enforce vrep for linear maps of non-square matrices. But there are two alternatives to keep the hrep that may apply in some cases:

- use left division `\`, see [this comment](https://github.com/JuliaReach/LazySets.jl/issues/1163#issuecomment-467399155)
- use the matrix pseudoinverse

**Comment by mforets** [comment]
A third, arguably better idea is to take the multiplication by transforming the lazy set to constraint representation, if it's not already in constraint form, and then converting to a `Zonotope`.

**Comment by schillic** [comment]
> converting to a `Zonotope`

For `AbstractHyperrectangle` this can be done implicitly by generalizing the `Zonotope` method to `AbstractZonotope`:
https://github.com/JuliaReach/LazySets.jl/blob/63a418dc09634e600dd3cff4df2b6f8a3f49522e/src/Zonotope.jl#L405-L412

**Comment by mforets** [comment]
The generalization in the last comment is now implemented, and

```julia
linear_map(rand(2, 3), rand(Hyperrectangle, dim=3))
```
returns a Zonotope.

I'm closing and opening a new issue for the other ideas in the [first comment](https://github.com/JuliaReach/LazySets.jl/issues/1169#issue-414766871.
