### ISSUE TITLE
Rename function ∩

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#117]
The function `∩(S1, S2)` does *not* compute the intersection. It checks if the intersection is empty.
We should rename it because we want to have a function that computes the intersection as well.

Name candidate: `is_intersection_empty` (a bit long, but this function is not so common)

**Comment by mforets** [comment]
+1 for `is_intersection_empty` and to reserve the symbol `∩` for the set based intersection.

**Comment by schillic** [comment]
Oh my, I proposed a stupid name. The implementations have the inverted meaning!
Solution options:
1. rename to `is_intersection_nonempty` (or another name)
2. invert the return value

**Comment by mforets** [comment]
ok, i don't have a particular preference for the return value, what is more convenient in your application?

**Comment by schillic** [comment]
I check for `have_intersection`.

**Comment by mforets** [comment]
thinking it twice, it's better IMO if we avoid the negation (nonempty), so +1 for `is_intersection_empty`.
