### ISSUE TITLE
Concrete translation of basic set types

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1184]
In https://github.com/JuliaReach/LazySets.jl/pull/1173 we added a lazy `Translation` operator.
We should add the concrete operation.

It can preserve the type in many cases, for example, the translation of an abstracthyperrectangle amounts to translating the center. For a general polytopic set, one translates the vertices. For a set represented by constraints, one can translate the constraints using `constraints_list(::Translation)`.

(About the name `translate` or `translation` -- I prefer `translate` ... but for the concrete intersection we kept `Intersection` for the type and `intersection`, i wonder we we didn't choose `intersect`..)

**Comment by schillic** [comment]
> i wonder we we didn't choose `intersect`

Because in Julia `intersect == ∩`.
```julia
help?> ∩
"∩" can be typed by \cap<tab>

search: ∩

  intersect(s, itrs...)
  ∩(s, itrs...)
```

**Comment by mforets** [comment]
Oh, ok, so the problem was that if we extend `intersect` then we cannot use the symbol `∩` for the *lazy* operation, we we do with other types.

**Comment by schillic** [comment]
I support `translate`.

**Comment by schillic** [comment]
> translating the center

This even extends to the `AbstractCentrallySymmetric` interface. However, we need to do add a method for every implementing type because there is no generic way to define a new set instance. And moreover, for `SymmetricIntervalHull` we need to create a `Hyperrectangle` because the `center` is fixed.
