### ISSUE TITLE
Annotate block_options in decompose

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1202]
The [decompose function](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/decompositions.jl#L219) accepts `block_options` of type `Any`.

Proposal: annotate `block_options` argument. In particular requires that linear indexing is available, since it is used as: `project(S, block, block_options[i], n)`.

**Comment by schillic** [comment]
I do not know if there is a corresponding interface in Julia. `Union{AbstractVector, AbstractDict{Int}}` could be a practical solution.

**Comment by mforets** [comment]
From [this function](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/decompositions.jl#L233) and the cases covered in the Examples section:

```julia
                   block_options::Union{Type{<:LazySet},
                                        Pair{<:UnionAll, <:Real},
                                        Real,
                                        Type{<:AbstractDirections},
                                         Dict{Int, Union{<:LazySet, <:Real}}}
```
It can be an `AbstractVector` as well?

**Comment by schillic** [comment]
Why not? You can access an `AbstractVector` at a given index, right?

**Comment by mforets** [comment]
Good. I've opened https://github.com/JuliaReach/LazySets.jl/issues/1203 to fill an example with that purpose and updated the union type above with `AbstractVector{<:LazySet}` and `AbstractVector{Union{<:LazySet, <:Real}}`.

**Comment by schillic** [comment]
You are missing the `AbstractDirections` in the vectors/dictionary.
That is exactly why I left it open - it becomes too much clutter.

**Comment by schillic** [comment]
I do not think this is still needed. So I close this.
