### ISSUE TITLE
Quantifier elimination for projections of unbounded sets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1207]
Currently, the list of constraints of an unbounded set cannot be obtained in some cases, e.g. the projection of a halfspace:

```julia
julia> S = Approximations.project(HalfSpace([1.0, 1.0, 0.0], 1.0), [1], LinearMap)
LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}}(
  [1, 1]  =  1.0, HalfSpace{Float64}([1.0, 1.0, 0.0], 1.0))

julia> constraints_list(S)
ERROR: ArgumentError: the linear map in vertex representation for an unbounded set is not defined
Stacktrace:
 [1] _linear_map_vrep(::SparseArrays.SparseMatrixCSC{Float64,Int64}, ::HalfSpace{Float64}) at /Users/forets/.julia/dev/LazySets/src/AbstractPolyhedron_functions.jl:335
 [2] #linear_map#18(::Bool, ::Float64, ::Bool, ::Function, ::SparseArrays.SparseMatrixCSC{Float64,Int64}, ::HalfSpace{Float64}) at /Users/forets/.julia/dev/LazySets/src/AbstractPolyhedron_functions.jl:313
 [3] linear_map at /Users/forets/.julia/dev/LazySets/src/AbstractPolyhedron_functions.jl:309 [inlined]
 [4] constraints_list(::LinearMap{Float64,HalfSpace{Float64},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}}) at /Users/forets/.julia/dev/LazySets/src/LinearMap.jl:377
 [5] top-level scope at none:0
```

A robust approach would be to use [quantifier elimination](https://en.wikipedia.org/wiki/Quantifier_elimination) to find the list of constraints above (in this case, the universal set). In this direction i've seen that [Reduce](https://chakravala.github.io/Reduce.jl/latest/man/11-substitution.html#.2.5-Substitutions-for-General-Expressions-1) offers quantifier elimination, but i haven't tried it.

**Comment by schillic** [comment]
I have not thought about this thoroughly, but I have the feeling that the answer can be computed with a simpler algorithm. Here are some preliminary ideas to investigate (they may or may not work):
1. `constraints_list(project(X::AbstractPolyhedron)) == project(constraints_list(X))`
2. `project(X::HalfSpace)` is either the original half-space (with some dimensions removed), namely if only unconstrained dimensions are removed (i.e., the corresponding entries in the normal vector are zero), or otherwise it is the low-dimensional `Universe`

**Comment by schillic** [comment]
related: #1086

**Comment by mforets** [comment]
see also Polyhedra's `eliminate` and `fixandeliminate`, https://juliapolyhedra.github.io/Polyhedra.jl/latest/projection/#Projection/Elimination-1

**Comment by mforets** [comment]
See #1950 for an apllication of such algorithms that use the implementation in CDDLib

**Comment by mforets** [comment]
I would consider this issue to be closed with #1950.

**Comment by schillic** [comment]
Sorry, but #1957 did not eliminate constrained dimensions (I was silly there).

**Comment by mforets** [comment]
To extend on my comment, what i meant was that quantifier elimination for projections of unbounded sets can be done with #1950 through `linear_map`'s function using the new `"elimination"` algorithm.

**Comment by mforets** [comment]
In that sense i don't see what additional task does this issue propose.

**Comment by schillic** [comment]
Okay, then we can close it with #1950 if the `"elimination"` algorithm is used in `linear_map` by default. In other words, `project(P, block)` should work for unbounded `P` and arbitrary `block`.

**Comment by mforets** [comment]
Exactly; if `m < n` then both invertibility and lifting checks quickly fail and `elimination` is returned by [_default_linear_map_algorithm](https://github.com/JuliaReach/LazySets.jl/pull/1950/files#diff-5e796138f8958d1d7c93fd38b67eb60aR363).
