### ISSUE TITLE
Generic overapproximate by falling back to convert

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1229]
Instead of duplicating these `overapproximate(X, Y) = convert(Y, X)` methods, we could define one such fallback method that checks for `hasmethod` and otherwise throws an error.

**Comment by mforets** [comment]
Yes, i thought about this recently. I think it is a good idea, but it may need to fix ambiguities for cases that are already generic in the set type, e.g. for `overapproximate(::LazySet, Hyperrectangle)`, we would not like to use the `convert` fallback.

**Comment by schillic** [comment]
True, but I hope that Julia will consider the other methods as "more specific" and choose them automatically.
