### ISSUE TITLE
Use CDDLib as default

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1235]
EDIT: See [this comment](https://github.com/JuliaReach/LazySets.jl/issues/1235#issuecomment-473852123) for the updated plan.

When using `Polyhedra`, we should automatically detect (via `Requires`) when `CDDLib` is loaded and use that as the default backend. That backend is more stable and faster.

(Note that in newer versions the constructor changed from `CDDLib.CDDLibrary()` to `CDDLib.Library()`.)

**Comment by schillic** [comment]
I suggest that we also offer a method `set_polyhedra_backend(name::String)` or similar. This makes it easier to change the backend, especially from the REPL.

**Comment by mforets** [comment]
Good! That function may override the function `default_polyhedra_library` so any methods that has `backend` kwarg will use it.

On the other hand, i suggest to switch to CDDLib as default (for the time being).
