### ISSUE TITLE
Optional tolerance argument for membership check

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#126]
In #68 we added containment checks. For floating-point numbers this check might fail due to precision issues. I would like to have an optional argument `tolerance::N=zero(N)`.

**Comment by mforets** [comment]
We have discussed elsewhere to make the tolerance a global variable that can be set optionally and hav  default value, see [src/comparisons.jl](https://github.com/JuliaReach/LazySets.jl/blob/master/src/comparisons.jl#L3); those variables can be `RTOL` and `ABSZTOL`.

**Comment by schillic** [comment]
`ABSZTOL` is a `const` and hence cannot be changed, right?

**Comment by mforets** [comment]
Right; my comment was that we can remove `const` and let both `RTOL` and `ABSZTOL` be those globals that control the tolerance.

**Comment by mforets** [comment]
> We have discussed elsewhere to make the tolerance a global variable that can be set optionally and has a default value, this seems the cleaner approach. 

See https://github.com/JuliaReach/LazySets.jl/pull/1510
