### ISSUE TITLE
More readable string output

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#127]
For nested set types the string output is not very helpful.
* Should we add a shorter output string function?
* Should it be default or optional?
* Do we want to have several levels (e.g., "print only sets up to two nesting levels", "print only the first 10 sets", ...)?

**Comment by mforets** [comment]
i agree that for nested sets there is an ugly output and we can do better with `Base.show`. more readable would be like: 

```julia
julia> b = Ball2(ones(2), 1.)
A Ball2 of center [1.0, 1.0] and radius 1.0.
julia> b ⊕ b
MinkowskiSum of a Ball2 of center [1.0, 1.0] and radius 1.0 and a Ball2 of center [1.0, 1.0] and radius 1.0
```

or even

```julia
julia> b ⊕ b
(Ball2 of center [1.0, 1.0] and radius 1.0) ⊕ (Ball2 of center [1.0, 1.0] and radius 1.0)
```

**Comment by schillic** [comment]
And what if we have deep nesting, e.g., `MinkowskiSum(MinkowskiSum(U, V), MinkowskiSum(X, Y))`?
What about array set types?
