### ISSUE TITLE
Rotated hyperrectangle / orthogonal polytope

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1280]
A rotated hyperrectangle is a normal hyperrectangle after applying a linear map (an alternative name is "orthogonal polytope"). It is thus a special case of a parallelotope or a zonotope (which is an affine map applied to a high-dimensional unit square) of order 1. The benefit over axis-aligned hyperrectangles is that the rotated versions are closed under linear maps. The benefit over zonotopes is that the support function is more efficient to evaluate.

It is probably easiest and most efficient to represent this type by storing the axis-aligned hyperrectangle and the matrix.

Maybe(!) a linear map of a hyperrectangle is equivalent to an affine map of the unit square. If so, an alternative is to store only the affine map, which might be more efficient in computations.

**Comment by mforets** [comment]
> Maybe(!) a linear map of a hyperrectangle is equivalent to an affine map of the unit square.

Yes, i think so, since a linear map distributes over Minkowski sum.
