### ISSUE TITLE
In convex hull?

### ISSUE THREAD

**Issue by kmundnic** [JuliaReach/LazySets.jl#1281]
I have gone through the docs, but cannot seem to find a way to check whether a vector or Singleton is in a convex hull. Is this an implemented operation?

This is how I imagine it:
```julia
> points = N -> [randn(2) for i in 1:N]
> v = points(30)
> hull = convex_hull(v)
> Singleton(v[1]) ∈ VPolygon(hull)
true
```
However, this throws the following error:
```julia
ERROR: MethodError: no method matching iterate(::VPolygon{Float64})
Closest candidates are:
  iterate(::Core.SimpleVector) at essentials.jl:589
  iterate(::Core.SimpleVector, ::Any) at essentials.jl:589
  iterate(::ExponentialBackOff) at error.jl:171
  ...
Stacktrace:
 [1] in(::Singleton{Float64,Array{Float64,1}}, ::VPolygon{Float64}) at ./operators.jl:949
 [2] top-level scope at none:0
```
which unfortunately is not very informative for a newcomer.

I also thought about creating a set from a Singleton, and try using `⊆`, but that always throws a `false` for convex hulls.

If this is supported, it would be a good addition in the convex hull section of the docs.

Thanks for your help!

**Comment by schillic** [comment]
> `> Singleton(v[1]) ∈ VPolygon(hull)`

`Singleton(x)` gives you a set containing the point `x`. `VPolygon(y)` also gives you a set of points. So the l.h.s. and the r.h.s. of `∈` are sets of points in your example. What you want to do is either of the following (they are equivalent):

```julia
julia> v[1] ∈ VPolygon(hull)
true

julia> Singleton(v[1]) ⊆ VPolygon(hull)
true
```

**Comment by mforets** [comment]
> If this is supported, it would be a good addition in the convex hull section of the docs.

See https://github.com/JuliaReach/LazySets.jl/pull/1282, comments welcome!

**Comment by kmundnic** [comment]
I thought `Singleton` wasn't a set, that's why I was using `∈` instead of `⊆`. Thanks for the clarification!

**Comment by mforets** [comment]
No problem! Thanks for pushing us to improve the docs ;)
