### ISSUE TITLE
GJK algorithm for checking disjointness of convex sets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1283]
See [the Wikipedia page](https://en.wikipedia.org/wiki/Gilbert%E2%80%93Johnson%E2%80%93Keerthi_distance_algorithm).

The algorithm can return a certificate, which is useful when applied in a loop with similar sets.
> If the positions in the new frame are close to those in the old frame, the algorithm will converge in one or two iterations. This yields collision detection systems which operate in near-constant time.

**Comment by mforets** [comment]
dup of https://github.com/JuliaReach/LazySets.jl/issues/920 ?
