### ISSUE TITLE
Singleton containment invokes the wrong method

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1298]
```julia
julia> Z = rand(Zonotope);
julia> Singleton(vertices_list(Z)[1]) ⊆ Z
# invokes invoke(⊆, Tuple{LazySet{N}, typeof(P), Bool}, S, P, witness)
# instead of ⊆(S::AbstractSingleton{N}, set::LazySet{N}, ...)
true
```

**Comment by mforets** [comment]
Actually, using `∈` *degrades* performance since support functions are faster than this [linear program](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Zonotope.jl#L264). In master:

In `master`:

```julia
julia> @btime center($Z) ∈ $Z
  36.290 μs (184 allocations: 10.25 KiB)
true

julia> @btime Singleton(center($Z)) ⊆ $Z
  14.192 μs (207 allocations: 42.30 KiB)
true
```

Based on this i would argue against changing the invocation method of `⊆`. Worth mentioning this difference though (the times get closer in higher dimensions). Maybe mention the different algorithms used in `∈` and in `⊆` in the [the documentation](https://github.com/JuliaReach/LazySets.jl/issues/1294)

**Comment by schillic** [comment]
Currently:
```julia
julia> @which Singleton(vertices_list(Z)[1]) ⊆ Z
issubset(S::AbstractSingleton{N}, P::AbstractPolyhedron{N}) where N<:Real in LazySets at .julia/dev/LazySets/src/ConcreteOperations/issubset.jl:329
```
Should we close this?
