### ISSUE TITLE
Set difference between axis-aligned boxes

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1305]

**Comment by schillic** [comment]
Set difference is generally non-convex. Is this intended?

**Comment by mforets** [comment]
I was thinking to make this operation return a union of hyperrectangles so we don't have to create a new type. The application that i have in mind is removal of reachable states in flowpipe approximation.

**Comment by mforets** [comment]
> Set difference is generally non-convex. Is this intended?

yes, it is intended. the output would be a `UnionSetArray`, comparable to the `UnionSet` return type of the set difference between intervals.

**Comment by mforets** [comment]
The new function should go in [this file](https://github.com/JuliaReach/LazySets.jl/blob/master/src/ConcreteOperations/difference.jl).

We saw that IntervalArithmetic.IntervalBox already has an implementation (for any dimension). It uses the interval representation, eg.

```julia
function Base.setdiff(A::Hyperrectangle{N}, B::Hyperrectangle{N}) where {N}
    Aib = convert(IntervalBox, A)
    Bib = convert(IntervalBox, B)
    return UnionSetArray(convert.(Hyperrectangle, IntervalArithmetic.setdiff(Aib, Bib)))
end

setdiff(rand(Hyperrectangle), rand(Hyperrectangle))

UnionSetArray{Float64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}}(Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}[Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([-0.5791442179784394, -0.4502732568374004], [0.28460180053503553, 1.5800148646546406])])
```

cc: @tacuaaa
