### ISSUE TITLE
Travis terminates building the docs

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1326]
Building the docs currently takes 700 seconds on Travis. However, Travis terminates builds that do not write any output within 600 seconds.
Currently there are some warnings about `ExponentialMap` docs missing (because we do not load the optional package `Expokit` for building the docs, which that type depends on). This is a dirty hack and makes the docs incomplete.
We should try to add an output when building docs instead (and load `Expokit`).

**Comment by mforets** [comment]
> Currently there are some warnings about ExponentialMap docs missing (because we do not load the optional package Expokit for building the docs, which that type depends on). This is a dirty hack and makes the docs incomplete.

Expokit is currently not loaded *on purpose* so that some warnings  show up in the screen before the build terminates for inactivity. (thanks @schillic  for the clarification, i had forgotten about this)

**Comment by schillic** [comment]
The problem with the `travis_wait` approach is that errors are no longer reported as errors, so we may falsely think that everything is okay even if it is not. An example is [here](https://travis-ci.org/JuliaReach/LazySets.jl/jobs/546392756#L641) where we provoked an error but the build was still green. The excerpt from the log is:
```
$ travis_wait 20 julia --project=docs/ docs/make.jl
Still running (10 of 20): julia --project=docs/ docs/make.jl
The command julia --project=docs/ docs/make.jl exited with 0.
Log:
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: ExpandTemplates: expanding markdown templates.
┌ Warning: failed to run `@example` block in src/man/reach_zonotopes.md:96-108
```
So the error is printed in the log, but `travis_wait` does not seem to care as long as the command terminated. I did some research and could not find any way. The best solution might be to bring the build time down below 10 minutes again.

**Comment by mforets** [comment]
`Skipping the after_success step, as specified in the configuration.` looks like a configuration issue (settings specified in `make.jl` and passed to Documenter).

**Comment by schillic** [comment]
No, this is fine. The relevant part is
`The command "travis_wait 20 julia --project=docs/ docs/make.jl" exited with 0.`
However, it now looks to me that this warning is actually never reported as an error (so this has nothing to do with `travis_wait`).

**Comment by schillic** [comment]
As @mforets observed, the trick is to add the `strict` keyword (see #1447).
