### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1332]
Here we trigger new releases using [`Registrator`](https://juliaregistrator.github.io/) ([example](https://github.com/JuliaReach/LazySets.jl/issues/1278#issuecomment-488332068)).

Meta issue.

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by schillic** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by schillic** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by schillic** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator regiser()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by schillic** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by schillic** [comment]
@JuliaRegistrator register()

**Comment by schillic** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
we can also trigger the bot on PR comments..

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()

**Comment by mforets** [comment]
@JuliaRegistrator register()
