### ISSUE TITLE
Handle inexact vectors in ispermutation

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1337]
If the vectors are floating points, `ispermutation` may fail:

```julia
function ispermutation(u::AbstractVector{T}, v::AbstractVector{T})::Bool where T
    ...
    occurrence_map = Dict{T, Int}()
    has_duplicates = false
    for e ∈ u
        if e ∉ v   
            return false
        end
....
```
It would be nice to add another function that can handle vectors that were originated by different means, in floating point, or add a tolerance keyword argument to `ispermutation`.

**Comment by mforets** [comment]
Approximate `ispermutation` was added in https://github.com/JuliaReach/LazySets.jl/pull/1484. However, there is a bug because the `_in` function does not dispatch on floats. It should be:

```julia
# alias for Julia's containment check
function _in(x, itr)
    return x ∈ itr
end

# approximate containment check for numbers in floating point
function _in(x::T, itr) where {T<:AbstractFloat}
    return any(y -> _isapprox(x, y), itr)
end

# approximate containment check for a vector in floating point
function _in(x::AbstractVector{T}, itr) where {T<:AbstractFloat}
    return any(y -> _isapprox(x, y), itr)
end
```

**Comment by schillic** [comment]
There is a bug with this implementation of inexact types: The `occurrence_map` obviously does not work anymore.
```julia
julia> ispermutation(N[1, 1 + Base.rtoldefault(N)], N[1, 2])
true
```
