### ISSUE TITLE
Improve intersection of VPolygon

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1347]
---

On the other hand intersection of original `VPolygon` is slow:

```julia
@btime intersection($p, $q) # as VPolygon
2.594 ms (32355 allocations: 1.84 MiB)
```
(this passes through Polyhedra through [this function](https://github.com/JuliaReach/LazySets.jl/blob/6289f14b24c78f8e13a7824bafc0487ec2408169/src/concrete_intersection.jl#L412), i'm thinking if we should rather use a 2D implementation, or at least convert to HPolygon and then use the intersection of HPolygon should be cheaper.

_Originally posted by @mforets in https://github.com/JuliaReach/LazySets.jl/issues/672#issuecomment-490281146_

**Comment by schillic** [comment]
I suggest the intersection via `HPolygon`. More precisely, we should keep the old method only for `VPolytope`s and add a new method for cases where are least one operand is a `VPolygon`.

**Comment by mforets** [comment]
in master, the operation uses an `intersection` function that is specialized for `VPolygon`:

```julia
julia> @btime intersection($p, $q) # as VPolygon
  1.867 μs (47 allocations: 3.83 KiB)
```

**Comment by schillic** [comment]
This came in #2345.
