### ISSUE TITLE
MethodError in overapproximation of lazy intersections of polyhedra

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1352]
```julia
julia> P = rand(HPolyhedron);

julia> overapproximate(P ∩ P, OctDirections(2));

MethodError: LazySets.Approximations.overapproximate(::Intersection{Float64,HPolyhedron{Float64},HPolyhedron{Float64}}, ::OctDirections{Float64}) is ambiguous. Candidates:
  overapproximate(cap::Intersection{N,#s35,#s24} where #s24<:LazySet where #s35<:AbstractPolyhedron{N}, dir::LazySets.Approximations.AbstractDirections{N}) where N<:Real in LazySets.Approximations at /Users/forets/.julia/dev/LazySets/src/Approximations/overapproximate.jl:442
  overapproximate(cap::Intersection{N,#s35,#s24} where #s24<:AbstractPolyhedron{N} where #s35<:LazySet, dir::LazySets.Approximations.AbstractDirections{N}) where N<:Real in LazySets.Approximations at /Users/forets/.julia/dev/LazySets/src/Approximations/overapproximate.jl:432
Possible fix, define
  overapproximate(::Intersection{N<:Real,#s35,#s24} where #s24<:AbstractPolyhedron{N<:Real} where #s35<:AbstractPolyhedron{N<:Real}, ::LazySets.Approximations.AbstractDirections{N<:Real})

Stacktrace:
 [1] top-level scope at In[66]:2
```

**Comment by schillic** [comment]
Sounds like we should add `overapproximate` to our ambiguity tests.

**Comment by mforets** [comment]
I'm not sure it's just a matter of disambiguation, for example `overapproximate_cap_helper(X::LazySet, P::AbstractPolyhedron)` assumes that the first set is compact, while for the missing method this may not be the case (if the intersection involves two unbdd polyhedron then the result can be as well unbdd, and overapproximate doesn't make much sense (?)

But may that's ok, in the sense that if `X ∩ Hi[i]` is unbdd in direction `di` then `ρ_X_Hi_min` would be inf.. perhaps we should check for `inf` inside `overapproximate`, since it is not checked in the polytope constructor:

```julia
julia> HPolytope([HalfSpace(rand(2), Inf)])
HPolytope{Float64}(HalfSpace{Float64}[HalfSpace{Float64}([0.650608, 0.870066], Inf)])
```

**Comment by schillic** [comment]
> I'm not sure it's just a matter of disambiguation

> `MethodError: LazySets.Approximations.overapproximate(::Intersection{Float64,HPolyhedron{Float64},HPolyhedron{Float64}}, ::OctDirections{Float64}) is ambiguous.`

Well, I am sure :smiley:
