### ISSUE TITLE
Remove redundant vertices of LinearMap

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1355]
Proposal: add an optional argument (default: `true`) for the `vertices_list` of a lazy linear map that takes the convex hull.

Possible test:

```julia
julia> X = rand(Interval) × ZeroSet(1);

julia> M = [0 1.; 0 2];

julia> vertices_list(M * X)  # should return only [[0.0, 0.0]]
2-element Array{Array{Float64,1},1}:
 [0.0, 0.0]
 [0.0, 0.0]
```

**Comment by schillic** [comment]
You forgot to describe the purpose of this argument :wink:
