### ISSUE TITLE
Add star set representation

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1357]
Proposal: add the symbolic set representation of generalized stars.

This set representation has applications in reachability analysis [1].

References:

- [Duggirala, P. S., & Viswanathan, M. 2016, July. Parsimonious, simulation based verification of linear systems. In International Conference on Computer Aided Verification pp. 477-494. Springer, Cham.](http://cs.unc.edu/~psd/files/research/2016/psd-mv-cav-16.pdf)

**Comment by schillic** [comment]
Stars are also used in Hylaa.

**Comment by mforets** [comment]
Ok thanks for the pointer, i thought my ref was the same set of people but it is not, although the intersection is non-empty ([HyLAA ref](http://stanleybak.com/hylaa/)).

**Comment by mforets** [comment]
Star sets used also in [Safety Verification of Cyber-Physical Systems with Reinforcement Learning Control](https://dl.acm.org/doi/abs/10.1145/3358230).

Here is a tentative definition:

```julia
# it is not generally convex but i make it <: LazySet
struct Star{N<:Real, VN<:AbstractVector{N}} <: LazySet{N}
    c::VN # center
    V::Vector{VN} # basis
    P::HPolyhedron{N} # predicate
end
```
In particular, the predicate function is implemented as a conjunction of linear constraints.
