### ISSUE TITLE
FIx documentation of right_turn (internal function)

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1379]
The docs suggest that the function `right_turn` determines whether an angle is a right turn.

https://github.com/JuliaReach/LazySets.jl/blob/923cf4ea5f893bde598cc152b3c0d9d1a95688dd/src/concrete_convex_hull.jl#L169-L197

However, this is the job of `is_right_turn`.

https://github.com/JuliaReach/LazySets.jl/blob/923cf4ea5f893bde598cc152b3c0d9d1a95688dd/src/AbstractPolygon.jl#L116-L135

While we are at it, I suggest to move both functions to `helper_functions.jl`.

**Comment by mforets** [comment]
👍  or move both of them to `AbstractPolygon.jl` (since both are specific to 2D).
