### ISSUE TITLE
Add DOI badge

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#138]
See, e.g., [here](https://github.com/GiovineItalia/Gadfly.jl).

**Comment by mforets** [comment]
we should be able to do that automatically for the next release. the problem was that i turned the repository to "ON" mode in the Zenodo page *after* the 1.0 release, thus it doesn't appear yet (although it could be done manually..). see [Zenodo FAQ](http://help.zenodo.org/) for more info.

**Comment by schillic** [comment]
It might be nice to have that for a publication soon (but I have not really an opinion here). The next release is not realistic before that.

**Comment by mforets** [comment]
we can have it for the v1.1 with the new intersections stuff

**Comment by mforets** [comment]
we added the DOI badge (see 
https://zenodo.org/account/settings/github/repository/JuliaReach/LazySets.jl
 )
for later we could add in the README and/or the docs "How to cite LazySets` with explanation.
