### ISSUE TITLE
Intersection of two sets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#139]
Add a lazy binary operator type `Intersection` (and maybe an n-ary variant) representing the intersection of two sets `S1` and `S2`.
Also have a convenience alias `∩(S1, S2)`, for which Julia's built-in alias is `intersect`.

Related but simpler: #67

**Comment by schillic** [comment]
1. What do we do if the intersection is not representable? Overapproximate? Underapproximate? Support both with a parameter?
2. Do we want to have a lazy type `Intersection`? It would be almost insonsistent to not have this, but the support vectors might not be as easy as with the other types.

**Comment by mforets** [comment]
yes, i think `∩` *should* be lazy. we can provide an option to compute it exactly, as it is the case for the minkowski sum of 2d clouds of points, for example.

**Comment by schillic** [comment]
Okay, I edited the first post.

**Comment by schillic** [comment]
Is it correct that, assuming that the intersection is nonempty, the support vector is just the minimum/maximum of both operands' support vectors?
```julia
function σ(d::AbstractVector{N}, I::Intersection{N, S1, S2})::AbstractVector{N} where {N<:Real}
    v = copy(d)
    sv1 = σ(d, I.X1)
    sv2 = σ(d, I.X2)
    for i in 1:length(d)
        v[i] = d[i] < 0 ? max(sv1[i], sv2[i]) : min(sv1[i], sv2[i])
    end
end
```
I am not sure about the case where a vector entry is 0.

And of course we need to detect that the intersection is nonempty. Can we just ask `σ(-d, I)` and see if the results contradict? This sounds too simple...

**Comment by mforets** [comment]
cc: @viryfrederic

**Comment by schillic** [comment]
Okay, this is Section 8.1, first paragraph in Le Guernic's thesis. I just have to study it.

**Comment by schillic** [comment]
The implementation we have now just crashes when asked for the support vector. We should think about what we can do here, maybe solve a complicated optimization problem or resort to subcases.

**Comment by mforets** [comment]
we could also write an `intersect` function that works by dispatching on some special pairs of sets for which we can implement it.

**Comment by schillic** [comment]
@mforets found [this paper](http://spaceex.imag.fr/documentation/publications/flowpipe-guard-intersection-reachability-computations-support-functions-4) about the general case.

**Comment by schillic** [comment]
We should pull out the `LinearConstraints.intersection` function here, too. See #57.

**Comment by mforets** [comment]
still this is open: 

> the implementation (of the intersection) we have now just crashes when asked for the support vector. 

one approach is to compute the concrete intersection (done in #173), and ask for the support vector. but i wouldn't do it this way since this wouldn't be a *lazy* operation at all. seems to me that it will be preferable to apply Lemma 4 from [Frehse and Ray](http://spaceex.imag.fr/sites/default/files/frehser_adhs2012.pdf).

**Comment by schillic** [comment]
Well, there are different levels of laziness.
1. `Intersection` waits with computing the intersection until you ask for it. This is what we could have with #173.
2. All our other lazy types never compute the actual set but only provide the support vector of a given direction by passing the query to their child sets. This is what you meant, and I agree that this is better (assuming it is actually cheaper).

**Comment by mforets** [comment]
Lots of interesting material: https://www.geometrictools.com/Documentation/Documentation.html

**Comment by schillic** [comment]
For the `LineSegment` we have `is_intersection_empty` but not `intersection`. In this case they are almost identical, so we should rather write the function for `intersection` and call this function from `is_intersection_empty` which then interprets the output.

**Comment by schillic** [comment]
Another interesting page: http://www.realtimerendering.com/intersections.html

**Comment by schillic** [comment]
Closing this one and continuing the meta collection in #1391.
