### ISSUE TITLE
Remove linear dependencies from zonotope's generators in constraints_list

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1453]
This came up [in #1451](https://github.com/JuliaReach/LazySets.jl/pull/1451#issuecomment-503821023).
> So perhaps we can check if the matrix of generators is full rank, and if it is not, remove the linearly dependent generators with the QR factorization and apply the algorithm for the independent case.

**Comment by mforets** [comment]
After the discussion, I think that the rank condition is a necessary (but not sufficient condition), so i would add a third check. 

```
    if p < n || (check_full_rank && rank(G) < n)
        return _constraints_list_fallback(Z)
    end
    res, Znew = _remove_redundant_constraints(Z)  # new auxiliary function
    if res # found redundant generators
        return _constraints_list_fallback(Znew)
    end
    ...
```
