### ISSUE TITLE
Faster support vector for BallInf

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1459]
For `BallInf`, instead of using `radius_hyperrectangle(H)` which allocates (because it has a `fill`), one can use `radius_hyperrectangle(H, i)` which is better since it can directly use `B.radius`.

_Originally posted by @mforets in https://github.com/JuliaReach/LazySets.jl/pull/1454#issuecomment-504240090_

**Comment by schillic** [comment]
I already did this in #1454.
