### ISSUE TITLE
minkowski_sum for VPolygons depends on order of vertices

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1462]
I just looked at the code from #1377 more closely and found that the implementation is unsound. 

https://github.com/JuliaReach/LazySets.jl/blob/3e9d8370bb295fe3a4007af77b5c9eb53e16c11c/src/VPolygon.jl#L582-L611

Here is a counterexample: `P2` is equivalent to `P` but with a different starting point in the vertices. The result is the same except for the last vertex.
```julia
julia> P = VPolygon([[4., 0], [6., 2], [4., 4]];)
julia> Q = VPolygon([[-2., -2], [2., 0], [2., 2], [-2., 4]]);
julia> PQ = minkowski_sum(P, Q)
VPolygon{Float64,Array{Float64,1}}(Array{Float64,1}[
[2.0, -2.0], [6.0, 0.0], [8.0, 2.0], [8.0, 4.0], [6.0, 6.0], [2.0, 8.0]])

julia> P2 = VPolygon([[4., 4], [4., 0], [6., 2]]);
julia> P2Q = minkowski_sum(P2, Q)
VPolygon{Float64,Array{Float64,1}}(Array{Float64,1}[
[2.0, -2.0], [6.0, 0.0], [8.0, 2.0], [8.0, 4.0], [6.0, 6.0], [2.0, 2.0]])
```
![PQ](https://user-images.githubusercontent.com/9656686/59941414-70fcdd00-945d-11e9-96bd-241fe5f3ecdb.png)

![P2Q](https://user-images.githubusercontent.com/9656686/59941417-72c6a080-945d-11e9-9c0b-4727e7d3b9ad.png)

The algorithm ([p. 295](https://people.inf.elte.hu/fekete/algoritmusok_msc/terinfo_geom/konyvek/Computational%20Geometry%20-%20Algorithms%20and%20Applications,%203rd%20Ed.pdf)) relies on the sorting of the vertices based on a common start, which the `VPolygon` type does not guarantee. Excerpt from the book:
> The lists of vertices are assumed to be in counter-clockwise order, with v1 and w1 being the vertices with smallest y-coordinate (and smallest x-coordinate in case of ties).

So in a preprocessing we need to identify the right value for `j` and `k`. (I suppose that it does not really matter that we choose the smallest y coordinate but rather that we align the two starting vertices, so it might be sufficient to adapt `j` to `k` or vice versa. But this might be over-engineering.)

**Comment by mforets** [comment]
CC : @SebastianGuadalupe
