### ISSUE TITLE
Set inclusion between zonotope and linear map

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1481]
> ```julia
> julia> N = Float64;
> 
> julia> B = BallInf(N[0, 0, 0], N(1))
> BallInf{Float64}([0.0, 0.0, 0.0], 1.0)
> 
> julia> X = minkowski_sum(B, B)
> Zonotope{Float64}([0.0, 0.0, 0.0], [1.0 0.0 … 0.0 0.0; 0.0 1.0 … 1.0 0.0; 0.0 0.0 … 0.0 1.0])
> 
> julia> X ⊆ 2.0 * B
> true
> 
> julia> 2.0 * B ⊆ X
> false
> ```

**Comment by schillic** [comment]
The implementation converts the zonotope to a polytope whose constraints look correct. So the problem occurs somewhere in `Polyhedra`; most probably this is just an issue with floating-point numbers.

**Comment by mforets** [comment]
Hmm i had a look, and it should actually have only 6 constraints, but it returns 30 constraints and the problem is that some of them contain `NaNs`:

```julia
julia> P = X; # a Zonotope

julia> S = 2.0 * B;
 
julia> constraints_list(P)[1:10]
10-element Array{HalfSpace{Float64,Array{Float64,1}},1}:
 HalfSpace{Float64,Array{Float64,1}}([0.0, -0.0, 1.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([0.0, -1.0, 0.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([NaN, NaN, NaN], NaN)
 HalfSpace{Float64,Array{Float64,1}}([0.0, -0.0, 1.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([0.0, -1.0, 0.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([1.0, -0.0, 0.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([0.0, -0.0, -1.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([NaN, NaN, NaN], NaN)
 HalfSpace{Float64,Array{Float64,1}}([1.0, -0.0, 0.0], 2.0)
 HalfSpace{Float64,Array{Float64,1}}([0.0, 1.0, 0.0], 2.0)
```

**Comment by schillic** [comment]
True, not sure what I looked at then :+1:
So the problem might be in `constraints_list(::Zonotope)`, or actually before that in
`minkowski_sum(::AbstractZonotope, ::AbstractZonotope)` because that creates a generator matrix with linear dependencies:
```julia
julia> X.generators
3×6 Array{Float64,2}:
 1.0  0.0  0.0  1.0  0.0  0.0
 0.0  1.0  0.0  0.0  1.0  0.0
 0.0  0.0  1.0  0.0  0.0  1.0
```

**Comment by SebastianGuadalupe** [comment]
The OP works in v1.21.0
```julia
julia> B = BallInf(N[0, 0, 0], N(1))
BallInf{Float64}([0.0, 0.0, 0.0], 1.0)

julia> X = minkowski_sum(B, B)
Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}}([0.0, 0.0, 0.0], [2.0, 2.0, 2.0])

julia> X ⊆ 2.0 * B
true

julia> 2.0 * B ⊆ X
true
```

**Comment by mforets** [comment]
Then i think we should close this issue.
