### ISSUE TITLE
Numeric type problems for Rational

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#151]
```julia
julia> b = BallInf(ones(Rational, 2), 1//10)

LazySets.BallInf{Rational}(Rational[1//1, 1//1], 1//10)

julia> σ([1//2, 3//4], b)
ERROR: MethodError: no method matching σ(::Array{Rational{Int64},1}, ::LazySets.BallInf{Rational})
Closest candidates are:
  σ(::AbstractArray{N<:Real,1}, ::LazySets.ZeroSet) where N<:Real at /Users/forets/.julia/v0.6/LazySets/src/ZeroSet.jl:95
  σ(::AbstractArray{N<:Real,1}, ::LazySets.AbstractSingleton{N<:Real}) where N<:Real at /Users/forets/.julia/v0.6/LazySets/src/AbstractSingleton.jl:134
  σ(::AbstractArray{N<:Real,1}, ::LazySets.AbstractHyperrectangle{N<:Real}) where N<:Real at /Users/forets/.julia/v0.6/LazySets/src/AbstractHyperrectangle.jl:82
  ...
```

**Comment by schillic** [comment]
This seems not specific for `BallInf`.
I guess the problem is that `BallInf{Rational}` and `Array{Rational{Int64},1}` do not have the same numeric type, but the signature requires the same type.
Options I see:
* do not use `ones` or use it with `Rational{Int}`
* do not require the same numeric type

**Comment by mforets** [comment]
so `b = BallInf([1//1,2//1], 1//10)` works ok, good finding!

your 2nd option, i.e.

```julia
function σ(d::AbstractVector, B::AbstractHyperrectangle)
    return center(B) .+ sign_cadlag.(d) .* radius_hyperrectangle(B)
end
```

works ok with a set defined via `b = BallInf(ones(Rational, 2), 1//10)`.

**Comment by schillic** [comment]
Well, we could still require that both the vector and the set subtype `Real`, and that the result is a `Real` vector. They are just not required to be the same type.

**Comment by schillic** [comment]
I just started removing the numeric types, but now I see a problem. What if you want to use `N` in the function? Which one do you choose, `d`'s type or `B`'s type?

Additionally, it seems to me that `ones(Rational, n)` is actually a misuse since `Rational{T<:Integer} <: Real` has a numeric type parameter which should be defined.

Now I would opt for option 1, so to use `ones(Rational{Int}, n)`.
