### ISSUE TITLE
Bump Documenter version

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1511]
The `DocTestSetup` in `@meta` blocks should now be defined in `make.jl`. See https://github.com/JuliaDocs/Documenter.jl/blob/v0.23.0/CHANGELOG.md#version-v0230

**Comment by schillic** [comment]
Furthermore, doctests in the test suite now have better support.

> makedocs now accepts the doctest = :only keyword, which allows doctests to be run while most other build steps, such as rendering, are skipped. This makes it more feasible to run doctests as part of the test suite (see the manual for more information).

> Documenter now exports the doctest function, which verifies the doctests in all the docstrings of a given module. This can be used to verify docstring doctests as part of test suite, or to fix doctests right in the REPL.
