### ISSUE TITLE
Concrete reflection of a set

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1559]
Outsourced from [this comment](https://github.com/JuliaReach/LazySets.jl/issues/1478#issuecomment-517301621).

**Comment by ueliwechsler** [comment]
This simple algorithm should work for each set for which the `hrep` is available.

```julia
using LazySets
using Plots

function reflect(P::LazySet)
    F,g = tosimplehrep(P)
    return HPolytope(-F,g)
end

A = rand(Zonotope)
plot(A)
A_reflect = reflect(A)
plot!(A_reflect, aspect_ratio=1)
```
![image](https://user-images.githubusercontent.com/12156892/64112871-f0295e00-cd88-11e9-923b-120150678bb3.png)
