### ISSUE TITLE
Rejection sampling

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1589]
[Rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling) is good as a (very general) fallback, since it only needs `LazySets.Approximations.box_approximation`.

_Originally posted by @mforets in https://github.com/JuliaReach/LazySets.jl/issues/917#issuecomment-509178607_

cc: @ueliwechsler

**Comment by ueliwechsler** [comment]
I think I need to comment first. Can you assign me now?

**Comment by ueliwechsler** [comment]
Hi, I have implemented a preliminary version for the rejection sampling. 
I'd like to have an opinion on my first draft. Should I just do a pull request for you to have a look?
```julia
using Plots
P2 = rand(HPolytope, dim=2)
plot(P2)
plot!([Singleton(si) for si in rand(P2,1000)])
plot!(Singleton(rand(P2)), marker=(:pent,:yellow,:20))
```
![test jpg](https://user-images.githubusercontent.com/12156892/63167914-e981b380-c032-11e9-9455-1e85ce03fe46.png)

**Comment by mforets** [comment]
yes, you can go ahead and open a PR !
