### ISSUE TITLE
ispermutation works with different numeric types

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1593]
In #1484 we removed the requirement that the two arguments of `ispermutation` have the same numeric type. I think this was a mistake because now we are not warned about inconsistencies. Note that the function is exclusively used in tests.

https://github.com/JuliaReach/LazySets.jl/blob/1ff0a52c2214ae31273be632218c521108d0bb4c/src/comparisons.jl#L301

**Comment by schillic** [comment]
I would vote to close this issue.

**Comment by mforets** [comment]
sure go ahead :+1:
