### ISSUE TITLE
n-ary operations array field

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#161]
proposal: for n-ary Minkowski sum and for n-ary Cartesian product, rename the array field type as follows: `sfarray -> array`

**Comment by schillic** [comment]
I totally agree. Also change the name of `LinearMap`?
Caution: This will break all places where we access this field (also in the reachability application).

We could take this opportunity and add a function `array(set)`.

(side note: This is part of an old list of minor fixes; maybe I should add the list in an issue.)

**Comment by mforets** [comment]
> Also change the name of LinearMap?

change the name?

**Comment by schillic** [comment]
```julia
struct LinearMap{N<:Real, S<:LazySet{N}} <: LazySet{N}
    M::AbstractMatrix{N}
    sf::S
end
```
I meant "change the name of `sf`" :)

**Comment by schillic** [comment]
So should we rename `sf`? To `X`?

**Comment by mforets** [comment]
yes; we use `X` in other places as well to denote the wrapped set, such as in `SymmetricIntervalHull`, `MinkowskiSum` and `Intersection`

**Comment by mforets** [comment]
- [ ] rename `LinearMap`'s `sf -> X` field 
- [ ] rename `MinkowskiSumArray`'s `sfarray -> array` field
- [ ] rename `CartesianProductArray`'s `sfarray -> array` field
- [ ] add a getter function `array` for `MinkowskiSumArray` and `CartesianProductArray`

**Comment by mforets** [comment]
-> add to wiki
