### ISSUE TITLE
Add macros to automatically create boilerplate code

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#162]
I want to try [metaprogramming in Julia](https://docs.julialang.org/en/stable/manual/metaprogramming/#Code-Generation-1) for repeated patterns that we have such as defining algebraic laws like neutral/absorbing elements for operations. I imagine something like:
```julia
@commutative_monoid(ConvexHull, EmptySet)
@commutative_monoid_absorbing(MinkowskiSum, ZeroSet, EmptySet)
```
These macros are supposed to create the three (resp. six) constructors for the different combinations.
I think this is easier to both read and write, less error-prone, and easier to adapt to changes.

The only downside I see is that we cannot write documentation for such constructors anymore. But we should probably just mention this in the type's documentation anyway.

**Comment by schillic** [comment]
After merging #228 we still need to address [this](https://github.com/JuliaReach/LazySets.jl/pull/228#pullrequestreview-95613688) comment.

**Comment by schillic** [comment]
What should be the behavior of the following functions?
```julia
1. MinkowskiSum(X::MinkowskiSum, Y::MinkowskiSum)
2. MinkowskiSum(X::MinkowskiSumArray, Y::LazySet)
3. MinkowskiSum(X::MinkowskiSumArray, Y::MinkowskiSumArray)
4. MinkowskiSumArray(X::MinkowskiSum, Y::MinkowskiSum)
5. MinkowskiSumArray(X::MinkowskiSumArray, Y::LazySet)
6. MinkowskiSumArray(X::MinkowskiSumArray, Y::MinkowskiSumArray)
```
Note that 1.-3. and 4.-6. are identical up to the function name. Should they have the same behavior?
Currently this is inconsistent: We usually modify the argument set, except for `CH(cha1::ConvexHullArray, cha2::ConvexHullArray) = ConvexHullArray(vcat(cha1.array, cha2.array))` which creates a new array. I think for efficiency reasons we should rather append (this is why we have these array types), but it can be confusing that the argument changes.

**Comment by mforets** [comment]
i would suggest (i think this corresponds to what you are proposing) that `MinkowskiSumArray` plays well with `MinkowskiSum`, since the former is just another lower level implementation of the latter. however, i wouldn't instantiate `MinkowskiSumArray`'s with elements of type `MinkowskiSum`, because this is an optional optimization.

if we follow this line:

- no , 1 would not append or create array, thus behave differently that the implementation that uses arrays,`MinkowskiSumArray`
-  yes i would append and allow modifying arguments if `MinkowskiSumArray` belongs to the equation.

what do you think?

**Comment by schillic** [comment]
Let me repeat to avoid confusions:
1. `MinkowskiSum(X::MinkowskiSum, Y::MinkowskiSum)` is not different from `MinkowskiSum(X::LazySet, Y::LazySet)`, thus resulting in a nested `MinkowskiSum` instance.
2. `MinkowskiSumArray(X::MinkowskiSum, Y::MinkowskiSum)` becomes a two-element `MinkowskiSumArray` instance (i.e., the arguments are not "flattened").
3. As soon as one argument is an array type, both functions modify that array and return it.

This is a good solution because we do not have to change the way `Reachability.jl` works.
