### ISSUE TITLE
Efficient way to obtain precise Interval bounds in 1D

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1638]
The overapproximation with `Interval` is precise unless the support function overapproximates. This is currently the case for a lazy `Intersection`. In 1D it should be possible to determine the bounds precisely.

**Comment by mforets** [comment]
This one is a bit tricky because the dimension is not a type parameter..

**Comment by schillic** [comment]
I do not think a type parameter would help. If you overapproximate with `Interval`, you know that the set is 1D. And you can dispatch on `Interval`.
```julia
function overapproximate(cap::Intersection{N}, ::Type{<:Interval}) where {N<:Real}
    X = overapproximate(cap.X, Interval)
    Y = overapproximate(cap.Y, Interval)
    return intersection(X, Y)
end
```
