### ISSUE TITLE
Bump CDDLib to v0.5.3

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1666]

**Comment by schillic** [comment]
(It is not published yet.)
We also need to update `JuMP` and hence `Polyhedra`.

**Comment by ueliwechsler** [comment]
We should be able to update them since both `CDDLib` `v0.5.3` and `Polyhedra` `v0.5.4` are `JuMP` `v0.20.0` compatible.

**Comment by schillic** [comment]
Yes, my point was that they are *only* compatible with `JuMP v0.20.0`.
