### ISSUE TITLE
Add CI for Windows

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1667]
Can be fixed by restoring AppVector, see https://github.com/JuliaReach/LazySets.jl/pull/1582
I have now access to a windows machine so it simplifies things if we have to debug.

**Comment by schillic** [comment]
> Can be fixed by restoring AppVector

Why not stick to [Travis-CI](https://docs.travis-ci.com/user/reference/windows/)?

> see #1582

This file was very old, so it might be outdated.

**Comment by mforets** [comment]
[Supported language](https://docs.travis-ci.com/user/reference/windows/#supported-languages) does not mention Julia :/

**Comment by mforets** [comment]
> This file was very old, so it might be outdated.

We can compare with https://github.com/JuliaCI/Appveyor.jl#usage

**Comment by schillic** [comment]
> Supported languages does not mention Julia :/

[Julia is now available on Travis Windows builds](https://discourse.julialang.org/t/julia-is-now-available-on-travis-windows-builds/27187)
