### ISSUE TITLE
Rejection sampling follow-up

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1669]
cf. https://github.com/JuliaReach/LazySets.jl/pull/1612

**Comment by ueliwechsler** [comment]
Just as a quick reminder, the following things are left to do in a first iteration.
- [ ] rename `Sampler` to something more specific, e.g. `BoxSampler` or `RejectionSampler`.
-  [ ]  replace`_canonical_length` with 
- [ ] Adjust documentation in several places
