### ISSUE TITLE
Implement vertices_list for HPolytope

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#168]
We have `HPolytope <: AbstractPolytope`, but this interface requires an implementation of `vertices_list`. Consequently, some operations break.

There is a bug in the interface checking function, hence we did not detect that this function is missing.

Actually, if we have `vertices_list`, we might as well add `VPolytope` because we get `tovrep` for free (we can leave `tohrep` open for now).

**Comment by mforets** [comment]
yes; this is an instance to use the polyhedra manipulation library.
