### ISSUE TITLE
Function to check for set-independent equality of sets

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/LazySets.jl#1688]
It would be convenient and helpful for readability to have a function that does 
`𝒫⁺ ⊆ 𝒫 && 𝒫 ⊆ 𝒫⁺`in one operation. 

The implementation could be straightforward. I am wondering what operator or function name makes sense, since `==` already is used for type-dependent equality checks. 

I would suggest something like overloading `Base.isequal` and call `==`  if the type of the arguments is identical.

**Comment by schillic** [comment]
See #1586.
