### ISSUE TITLE
Turn mutable structs into normal (immutable) structs

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#17]
Just need to review where we actually use mutability and otherwise change it...

**Comment by schillic** [comment]
I reviewed and found these places:
```julia
ExponentialMap.jl: mutable struct SparseMatrixExp
ExponentialMap.jl: mutable struct ExponentialMap <: LazySet
ExponentialMap.jl: mutable struct ProjectionSparseMatrixExp
ExponentialMap.jl: mutable struct ExponentialProjectionMap <: LazySet
CartesianProduct.jl: mutable struct CartesianProductArray <: LazySet
MinkowskiSum.jl: mutable struct MinkowskiSumArray <: LazySet
Polygon.jl: mutable struct HPolygon <: LazySet
Polygon.jl: mutable struct HPolygonOpt <: LazySet
Polygon.jl: mutable struct VPolygon <: LazySet
Polyhedron.jl: mutable struct Polyhedron <: LazySet
```
Most of the types just wrap an array.
If we remove the `mutable`, we may still modify the array; we are only not allowed to assign a new array anymore, which I think is fine (more docs [here](https://docs.julialang.org/en/stable/manual/types/#Composite-Types-1)).

I expect that in `Polyhedron.jl` the dimension `dim` should not change.

The only place where I am not confident that the change is save is in `HPolygonOpt.jl`:
Do we want to be able to modify the field `ind`?

One more thing: We have one occurrence of `type`, which should probably also become a `struct`:
```julia
LinearMap.jl: type LinearMap <: LazySet
```

**Comment by mforets** [comment]
>  If we remove the mutable, we may still modify the array; we are only not allowed to assign a new array anymore, which I think is fine (more docs here).

good point, let's do that.

> I expect that in Polyhedron.jl the dimension dim should not change.

yes. we wanted `dim` to be the ambient dimension, i.e. even this is square patch in 3d-space

> The only place where I am not confident that the change is save is in HPolygonOpt.jl: Do we want to be able to modify the field ind?

yes, i think that `ind` should be modified because it is updated at each iteration. @viryfrederic  do you agree?

> One more thing: We have one occurrence of type, which should probably also become a struct:

yes we should update that for future versions

**Comment by schillic** [comment]
I pushed the changes on top of the branch of PR #21.
Let us see how this works 😼

**Comment by mforets** [comment]
Cool. Then your proposed changes for this issue are already on `mater` branch, or some but not all of them?

**Comment by schillic** [comment]
Nope, they are in a separate branch which I based on the other branch.
I fear that the merging will be a mess, but I wanted to try.
I will add the PR later and merge it directly after the tests have passed.

**Comment by mforets** [comment]
i think you can just rebase `t/schilllic/17` into the current `master`, see the [network graph](https://github.com/JuliaReach/LazySets.jl/network)

**Comment by schillic** [comment]
You are right, I have just queried the PR.
