### ISSUE TITLE
Add check for empty set after concrete Minkowski difference

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaReach/LazySets.jl#1704]
The function minkowski_difference should throw an error, if the resulting set is empty.

**Comment by schillic** [comment]
Why? I think this is a legitimate result.

**Comment by ueliwechsler** [comment]
Maybe, throwing an error is too harsh, but I think it is reasonable to discuss if we return some feedback if the Minkowski Difference returns an empty set. 

There are two reasons that made me write this issue yesterday evening.
1. I'd like to know if my computation was reasonable. I think, normally you don't want your result of `C = P - Q` to be empty. 
2. If I want to plot the resulting empty set.
```
P = BallInf(zeros(2), 5.0)
Q = BallInf(zeros(2), 10.0)
C = P - Q
isempty(C)
plot(C)
```
 I got the error message `MethodError: no method matching iterate(::Nothing)` that was confusing, because I did not see the warning message `received a polyhedron with no vertices during plotting`

**Comment by schillic** [comment]
Checking emptiness of a polytope is nontrivial, so I would not invoke this check every time when computing the difference.

> 1. I'd like to know if my computation was reasonable.

You can always define a wrapper function that does the `isempty` for you. Since you anyway define `-`, you can just do:

```julia
function -(P::LazySet, Q::LazySet)
    diff = minkowski_difference(P, Q)
    if isempty(diff)
        error("difference is empty")
    end
    return diff
end
```

> I got the error message MethodError: no method matching iterate(::Nothing) that was confusing

That is a bug (#1705).

> because I did not see the warning message `received a polyhedron with no vertices during plotting`

Hopefully it will be more prominent after the crash is fixed.

**Comment by ueliwechsler** [comment]
> Checking emptiness of a polytope is nontrivial, so I would not invoke this check every time when computing the difference.

👍 You did convince me. I close the issue.
