### ISSUE TITLE
Maximum volume ellipsoid in a polyhedral set

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1712]
https://systemanalysisdpt-cmc-msu.github.io/ellipsoids/doc/chap_ellcalc.html#maximum-volume-ellipsoids

https://github.com/blegat/SetProg.jl

https://github.com/blegat/SetProg.jl/issues/5

underapproximation

**Comment by schillic** [comment]
X-ref for the overapproximation: #1653
