### ISSUE TITLE
Use SingleEntryVector in box overapproximation

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1745]
The computation of a box overapproximation of a general LazySet evaluates the support function along the canonical directions. Hence we may benefit from micro-optimizations using `SingleEntryVector`. See also [this comment](https://github.com/JuliaReach/LazySets.jl/pull/1716#discussion_r329722155).

cc: @dfcaporale

**Comment by schillic** [comment]
Note that creating many `SingleEntryVector` objects might actually be less efficient than what we did before (we saw this with sparse vectors). It might only be more efficient if the support function for the underlying set dispatches on `SingleEntryVector`.
