### ISSUE TITLE
Add upper bounds for dependencies

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1781]
See https://discourse.julialang.org/t/announcement-automatic-merging-for-the-general-registry/29961.

**Comment by schillic** [comment]
In principle I see two ways:
1. Only allow the most recent package versions (i.e., upper bound = lower bound).
2. Have a range of available package versions.

The disadvantage of 1. is that `LazySets` only works with the current environment of packages. If you have to go back to an older version of `LazySets` (e.g., to investigate a regression), you need to reinstall old package versions. And similarly if you need to use an older version of some package, you cannot use the new versions of `LazySets` anymore.
The disadvantage of 2. is that we do not actually test the older versions (Travis always uses the most recent versions that are compatible).

So 1. is too restrictive and 2. is too generous.

I tend to go for 2. For some packages we do not know a lower bound, so we should not specify it. For other packages we do know a lower bound, but it is usually not the most recent version. We can have a Travis build with the lowest dependency versions to alleviate the disadvantage of 2.

**Comment by mforets** [comment]
This was done in [v1.22.0](https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.22.0), implementing option 2.
