### ISSUE TITLE
Fallback implementation for inclusion between polytopic sets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1792]
```julia
julia> typeof.([Rt, Tg])

2-element Array{DataType,1}:
 Zonotope{Float64}                                                         
 MinkowskiSum{Float64,Singleton{Float64,Array{Float64,1}},BallInf{Float64}}

julia> Rt ⊆ Tg

MethodError: no method matching iterate(::MinkowskiSum{Float64,Singleton{Float64,Array{Float64,1}},BallInf{Float64}})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:604
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:604
  iterate(!Matched::ExponentialBackOff) at error.jl:214
  ...

Stacktrace:
 [1] in(::Array{Float64,1}, ::MinkowskiSum{Float64,Singleton{Float64,Array{Float64,1}},BallInf{Float64}}) at ./operators.jl:1055
 [2] ∉(::Array{Float64,1}, ::MinkowskiSum{Float64,Singleton{Float64,Array{Float64,1}},BallInf{Float64}}) at ./operators.jl:1068
 [3] issubset at /home/mforets/.julia/dev/LazySets/src/ConcreteOperations/issubset.jl:229 [inlined]
 [4] issubset(::Zonotope{Float64}, ::MinkowskiSum{Float64,Singleton{Float64,Array{Float64,1}},BallInf{Float64}}) at /home/mforets/.julia/dev/LazySets/src/ConcreteOperations/issubset.jl:226
 [5] top-level scope at In[187]:1
```

but

```julia
julia> Tg_poly = HPolytope(constraints_list(Tg));
julia>Rt_poly = HPolytope(constraints_list(Rt));
julia>Rt_poly ⊆ Tg_poly 

true
```

cc: @dfcaporale, @SebastianGuadalupe

**Comment by schillic** [comment]
The problem is in the membership (see the top of the stack trace).

**Comment by mforets** [comment]
True, dispatch is trying to use the function the uses the vertices ([this one](https://github.com/JuliaReach/LazySets.jl/blob/master/src/ConcreteOperations/issubset.jl#L224)). However, in general it is more efficient and less error-prone to use the support function ([this function](https://github.com/JuliaReach/LazySets.jl/blob/master/src/ConcreteOperations/issubset.jl#L41)) which is triggered if one swaps the containment check.

I would add an algorithm choice for `⊆(P::AbstractPolytope{N}, S::LazySet{N})`, such that `algorithm='vertices'` and `algorithm='constraints'` allows to choose the method, letting the `constraints` algorithm to be the default one.

**Comment by mforets** [comment]
For a new method to handle the computation in [1] of the stack trace, i've opened https://github.com/JuliaReach/LazySets.jl/issues/1793

**Comment by schillic** [comment]
> I would add an algorithm choice for ⊆(P::AbstractPolytope{N}, S::LazySet{N}), such that algorithm='vertices' and algorithm='constraints' allows to choose the method, letting the constraints algorithm to be the default one.

Sounds good.
