### ISSUE TITLE
Membership between singleton and lazy m-sum

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1793]
Cf. https://github.com/JuliaReach/LazySets.jl/issues/1792#issue-527564541

**Comment by schillic** [comment]
I think this is the same as #1562.

**Comment by mforets** [comment]
The method that failed can be handled more simply without ICP, as 

```julia
 [1] in(::Array{Float64,1}, ::MinkowskiSum{Float64,Singleton{Float64,Array{Float64,1}},BallInf{Float64}}) at ./operators.jl:1055
```
can be decided by checking if the point `p-s` belongs to the given polytope.
