### ISSUE TITLE
Inconsistent inclusion check

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1809]
```julia
X = BallInf([0.1, 0.2, 0.1], 0.3)
Y = convert(HPolytope, X)
X ⊆ Y    # true
Y ⊆ X    # false
```

Reported by @ueliwechsler in https://github.com/JuliaReach/LazySets.jl/issues/1586#issuecomment-561201760_

**Comment by mforets** [comment]
A quick comment: the method dispatched by `X ⊆ Y` (the `_issubset_constraints_list`) is much faster than the method dispatched with `Y ⊆ X` (which consists of taking the interval hull of `Y` and then using the inclusion test for a pair of hyperrectangles). The difference is 400ns vs 76us, and most of the time in the second case is spent taking the interval hull.

**Comment by mforets** [comment]
The explanation is that evaluating the support function of the polytope `Y` takes ~10us, as it is solving an LP. While the evaluation of the support function for the box `X` takes ~25ns as it just uses the support function formula.

**Comment by schillic** [comment]
I am not surprised because the problem is not symmetric. (That does not mean that there is no faster algorithm of course.)

**Comment by mforets** [comment]
Yeah; one can hope of using a different solver (GLPK is known to be slow compared to other existent LP solvers, especially for large systems).
