### ISSUE TITLE
Documentation nondeterministically breaks due to missing eltype function

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1871]
See #1866, which did not actually solve the problem.

```
[ Info: CheckDocument: running document checks.
┌ Warning: 1 docstring potentially missing:
│ 
│     Base.eltype :: Union{Tuple{Type{#s21} where #s21<:LazySet{N}}, Tuple{N}} where {N}
└ @ Documenter.DocChecks ~/.julia/packages/Documenter/IGqbY/src/DocChecks.jl:63

```

**Comment by mforets** [comment]
In my machine, building the docs is always failing and taking ~40 minutes.

**Comment by schillic** [comment]
You can remove the `man` folder and remove the section from `make.jl`. Then  it takes only ~1 minute.

**Comment by mforets** [comment]
Strange answer. Why would i want to remove the `man` folder? Suddenly, building the docs have started to be super long, i have no idea what is the cause. I assume it works fine in your machine (without having to delete the `man` folder?). I'll try again after we merge #1872.

**Comment by schillic** [comment]
Building the whole docs also takes ~20 minutes for me (and on Travis) and this is not new (remember that we added the longer timeout a while ago for building the docs here). The long building time is due to the manual (from the `man` folder) and I think the reason is that it needs to compile many of our methods, which just takes time.
