### ISSUE TITLE
AbstractPolytope list of constraints

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#188]
proposing to extend:

```
Every concrete `AbstractPolytope` must define the following functions:
- `vertices_list(::AbstractPolytope{N})::Vector{Vector{N}}` -- return a list of
    all vertices
```

such that it also defines a list of constraints (`constraints_list`).

both for the vertices and the constraints case, it can be done with and without using iterators.

**Comment by schillic** [comment]
* For `AbstractHPolygon` we already have this function.
* For `HPolytope` it is be trivial.
* For `VPolygon` it is also rather simple.
* Remaining: `VPolytope`, `AbstractHyperrectangle`, `Zonotope`, `Ball1`.

**Comment by mforets** [comment]
I've updated the list with the issues for each set type that is missing `constraints_list`. Also adapted the title of this issue because it is only about `constraints_list` (no iterators yet).

**Comment by schillic** [comment]
Before we close this one, let me add `constraints_list` to the interface, including a check that the function is implemented by all subtypes.
