### ISSUE TITLE
Change type unions to common supertype

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#19]
Quite often we have the following code patterns:
```julia
d::Union{Vector{Float64}, SparseVector{Float64,Int64}}
M::Union{Matrix{Float64}, SparseMatrixCSC{Float64,Int64}}
```
We should use instead the common supertype:
```julia
d::AbstractVector{Float64}
M::AbstractMatrix{Float64}
```
This is easier to read and gives more flexibility (e.g., allow `SubArray`s if not already mentioned).
I do not expect negative performance impact; we should of course validate this.

**Comment by mforets** [comment]
yep, i agree that we should do this! please go ahead with these changes

**Comment by mforets** [comment]
you can either push to master directly, or we get used to filing a new PR each time, so we can detect if sth was broken

**Comment by schillic** [comment]
There will be a merge conflict with #18, so I would like to finish that one first.
