### ISSUE TITLE
Deactivate sanity checks in library code

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#1961]
This is a generalization of the idea in #1960.

Example: Whenever we create a new `Zonotope` in library code, we should deactivate the check for zero generators, provided that the particular code cannot introduce additional zero generators.

This idea generalizes to any other function call in the library. The principle is the following: We have sanity checks at the user interface (the public constructors) and so  we can assume that the sets that we receive as input are well-behaved according to our assumptions. There is no need to check these assumptions at every step.

It would be good to have a unified way to call those internal constructors. Here are some possible approaches:

* Pass the arguments manually (not good because it is hard to read and there may be additional arguments in the future).
* For each constructor introduce another constructor with a prefix `L`. Example: `LZonotope(c, G)` just calls the `Zonotope(c, G, args=...)` constructor with the right arguments.
* Add a type for dispatch and then add a constructor `Zonotope(c, G, LibraryMode())` that again calls the `Zonotope(c, G, args=...)` constructor with the right arguments.
Have a macro `@library Zonotope(c, G)` that again calls the `Zonotope(c, G, args=...)` constructor with the right arguments. It is not clear how hard that would be.

Note that the examples above may only work for constructors and not for other function calls. And there may be additional work required if multiple constructors exist.

**Comment by mforets** [comment]
> We have sanity checks at the user interface (the public constructors) and so we can assume that the sets that we receive as input are well-behaved according to our assumptions.

Hmm I tend to disagree with this principle. The library can't take such assumptions on the user code. I think it is more reasonable to use constructor defaults for the features defaults.

**Comment by schillic** [comment]
We would keep the checks at the input level. But once you have constructed a `Zonotope` (using the constructor with the sanity check), you can assume that it is good. So a function that receives a `Zonotope` can assume this (and actually we never check for this property in our functions). If we call the `Zonotope` constructor from a function like in #1960, we can assumpe that the result does not contain zero generators.

**Comment by mforets** [comment]
I'm not sure to let the package make all these assumptions on the user level. The zonotope *can* be modified by appending zero generators (for whatever reason).
