### ISSUE TITLE
Add getter function for center at a specific index for hyperrectangular sets

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#1969]
`center(H)[i]` (use in `AbstractHyperrectangle.jl` for example) allocates a vector; we should consider a better fallback requiring `center(H::AbstractHyperrectangle, i::Int)` to be part of the `AbstractHyperrectangle` interface and use it.

**Comment by schillic** [comment]
duplicate of #1578

**Comment by mforets** [comment]
Ooops, i didn't see the other issue, thanks.
