### ISSUE TITLE
Make HPolygonOpt a subtype of HPolygon

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#20]
The only type union not affected by #19 exists in `Polgyon.jl` to handle `HPolygon`s and `HPolygonOpt`s simultaneously.

We should probably just make `HPolygonOpt` inherit from `HPolygon`.
This makes sense both from the code and from the conceptual side to me.
I am, however, not sure if Julia finds the correct function if one argument is an array of a subtype; I guess it does, but this has to be tested.

@mforets: What do you think?

**Comment by mforets** [comment]
hmm.. i dunno... otherwise we can group them all into a new`abstract type LazyPolygon <: LazySet end` in the sense that `HPolygon <: LazyPolygon`, `VPolygon <: LazyPolygon` and `HPolygonOpt <: LazyPolygon`.

**Comment by schillic** [comment]
My motivation was that all functions that handle `HPolygon` can automatically handle `HPolygonOpt`.
There is no structural difference.

This is not true for `VPolygon`.

**Comment by mforets** [comment]
that makes sense. ok, then let me do that. today i'll be working on this one and on #13. (i'll put in the same PR).

**Comment by schillic** [comment]
Sorry, subtyping is not allowed in Julia ([source](https://discourse.julialang.org/t/inheritance-in-julia/5416)).
