### ISSUE TITLE
Remove constructor of VPolytope from VPolygon

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2009]
IIRC we've been removing creating of types from other types, users should do instead `convert(target_type, type)` (or `overapproximate`). The following still remains in `VPolytope.jl`:

```julia
# constructor from a polygon in V-representation
function VPolytope(P::VPolygon, share::Bool=false)
    v = vertices_list(P)
    if !share
        v = copy(v)
    end
    return VPolytope(v)
end
```
Should we remove it?

**Comment by schillic** [comment]
> Should we remove it?

I agree, but the sharing is an important option.
