### ISSUE TITLE
Add hybrid reach example

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#201]

**Comment by schillic** [comment]
Should we put our new example? I am in favor of fixing the problem with `b` in the affine example and then put that.

**Comment by mforets** [comment]
👍 ; i think that with `b=0` is good.

**Comment by schillic** [comment]
Do you mean the homogeneous version example?

**Comment by mforets** [comment]
yes, the extension of the example already in the manual, but with 2 dynamical matrices.

moreover, the current example operates with lazy set types; in the new section for hybrid example, it will use only zonotopes and concrete operations on them.

**Comment by schillic** [comment]
> moreover, the current example operates with lazy set types; in the new section for hybrid example, it will use only zonotopes and concrete operations on them.

What do you want to say here? Is this a problem? Should we change one of the examples?

**Comment by mforets** [comment]
just a comment that i wouldn't change the [existent section (that uses symbolic) ](https://juliareach.github.io/LazySets.jl/latest/man/reach_zonotopes.html). in sandbox/reach_hybrid branch we can create a new section  "Hybrid reachability example", if you like
