### ISSUE TITLE
Optional algorithms for <=

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#202]
In #198 we introduced an alternative method to sort directions with the right-hand rule after checking the quadrant of each direction (in particular it doesn't use `atan2`). It could be added as an alternative `algorithm=...` for the `<=`.

A quick test shows that it can be faster too: for `1000` random directions, the  times are approx. `130us` vs. `70us`.

---

The comparison that uses `quadrant` is more general:

```julia
julia> using LazySets

julia> u, v = [1., 0], [0, 1.];

julia> @which u <= v
<=(u::AbstractArray{N,1}, v::AbstractArray{N,1}) where N<:AbstractFloat in LazySets at /Users/forets/.julia/v0.6/LazySets/src/AbstractPolygon.jl:107

julia> u, v = [1//1, 0//1], [0//1, 1//1];

julia> @which u <= v
<=(u::AbstractArray{N,1}, v::AbstractArray{N,1}) where N<:Real in LazySets at /Users/forets/.julia/v0.6/LazySets/src/AbstractPolygon.jl:169
```

Test:

```julia
julia> using Compat, BenchmarkTools

julia> @inline function quadrant(w::AbstractVector{N})::Int where {N<:Real}
           dwx = w[1] >= zero(N) ? 1 : 0
           dwy = w[2] >= zero(N) ? 1 : 0
           return (1 - dwx) + (1 - dwy) + ((dwx & (1 - dwy)) << 1)
       end
quadrant (generic function with 1 method)

julia> function cquadrant(u::AbstractVector{N}, v::AbstractVector{N})::Bool where {N<:Real}
           qu, qv = quadrant(u), quadrant(v)
           if qu == qv
               # same quadrant, check right-turn with center 0
               ans = u[1] * v[2] - v[1] * u[2] >= zero(N)
           else

               # different quadrant
               ans = qu < qv
           end
           return ans
       end
cquadrant (generic function with 1 method)

julia> @inline function jump2pi(x::N)::N where {N<:AbstractFloat}
           x < zero(N) ? 2 * pi + x : x
       end
jump2pi (generic function with 1 method)

julia> function cjump(u::AbstractVector{N},
                   v::AbstractVector{N})::Bool where {N<:AbstractFloat}
           return jump2pi(atan2(u[2], u[1])) <= jump2pi(atan2(v[2], v[1]))
       end
cjump (generic function with 1 method)

julia> u = [rand(2) for i in 1:1000]; v = [rand(2) for i in 1:1000];

julia> @btime cjump.(u, v)
  132.405 μs (23 allocations: 5.13 KiB)

julia> @btime cquadrant.(u, v)
  31.329 μs (23 allocations: 5.13 KiB)

julia> cquadrant.(u, v) == cjump.(u, v)
true
```

**Comment by schillic** [comment]
Related, but not the same: The main application is to find the next constraint in an `HPolygon` for a given constraint. That means that we may ask many such queries where one of the directions remains constant. So we could remember the quadrant without recomputing it over and over.

But this requires a bit of thinking how to adapt the code - at the moment I do not see how.

**Comment by mforets** [comment]
ok, we could look to having some cache, and that could be an addon to the `HPolygonOpt` type

**Comment by mforets** [comment]
We now have `_leq_quadrant` and `_leq_trig`, and the faster version (quadrants) is used in HPolygons, ref. https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.30.0.

> So we could remember the quadrant without recomputing it over and over.

Should we open a new issue?

**Comment by mforets** [comment]
I mean, it is not clear what it means how is the cache is supposed to behave.
