### ISSUE TITLE
Make `+` lazy for Intervals

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2020]
When we wrote the `Interval` type we left `+` to be "particular" as taking the concrete m-sum, with the idea that it is fast to do for intevals.. I changed my mind, and i think that `+` should use the lazy, as with the other set types. (but note #2019).

**Comment by schillic** [comment]
I agree that the behavior of `+` should be consistent for all set types.
It might be useful to have a global option to switch the meaning of the arithmetic operators to a concrete behavior, but this is a different story.

**Comment by mforets** [comment]
> I agree that the behavior of + should be consistent for all set types.

Alright, thanks for the feedback.

> It might be useful to have a global option to switch the meaning of the arithmetic operators to a concrete behavior, but this is a different story.

Yes, i agree. We have discussed about this in another issue (https://github.com/JuliaReach/LazySets.jl/issues/175), and in the end i commented that this can be done with *contextual dispatch* This is a proof of that principle:

```julia
using LazySets, Cassette
Cassette.@context ConcreteMinkowskiSumCtx
const concrete_minkowski_sum_ctx = Cassette.disablehooks(ConcreteMinkowskiSumCtx())

Cassette.overdub(::ConcreteMinkowskiSumCtx, ::typeof(+), X::LazySet, Y::LazySet) = LazySets.minkowski_sum(X, Y)

concrete_minkowski_sum(f) = Cassette.overdub(concrete_minkowski_sum_ctx, f)

concrete_minkowski_sum() do
    X, Y = rand(VPolygon), rand(VPolygon)
    X + Y
end

VPolygon{Float64,Array{Float64,1}}(Array{Float64,1}[[-4.387680426840783, 2.877203090673391], [...]]
```

**Comment by mforets** [comment]
On a related note, `-(x::Interval{N}, y::Interval{N}) where {N<:Real}` could be replaced by the lazy Minkowski difference, but that type is not yet available.
