### ISSUE TITLE
Move triangulation to new file

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2078]
Currently the triangulation code `delaunay` resides in `init.MiniQhull.jl`. It should go to ~a separate file in `ConcreteOperations/`~ ~`Interfaces/AbstractPolyhedron_functions.jl`~ `Interfaces/LazySet.jl`.

**Comment by mforets** [comment]
At some point we said to only keep *binary* functions in [that folder](https://github.com/JuliaReach/LazySets.jl/tree/master/src/ConcreteOperations), but i agree to also put some unary concrete operations there.

**Comment by schillic** [comment]
Good point, I updated the OP.

**Comment by mforets** [comment]
Actually, I think that any of these is better than `AbstractPolyhedron_functions.jl`:

-  `ConcreteOperations`.
- `init_MiniQhull.jl`.
- `LazySet.jl` since it's a fallback implementation.

**Comment by schillic** [comment]
True, we use the `vertices_list` function but the required type is `LazySet`.
