### ISSUE TITLE
Conflict with Distributions.sample

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2079]
```julia
julia> using LazySets, Distributions
WARNING: both Distributions and LazySets export "sample"; uses of it in module Main must be qualified
```
I tried around a bit but could not get it to work with a simple `import .Distributions: sample`. The reason may be that we have a `sample` function outside the `@require` block.

**Comment by mforets** [comment]
yes, that's the reason

**Comment by mforets** [comment]
this is less of an issue now because of https://github.com/JuliaReach/LazySets.jl/pull/2480. im in favor of closing this one.
