### ISSUE TITLE
Check for empty intersection of zonotope with hyperplane

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#208]
* [x] check for intersection
* [ ] produce a witness

**Comment by schillic** [comment]
How to check for a witness?
* I see that the problem can be posed as a linear program with domain constraints. Is there a better way?
* For a `Ball2` we could just compute the point on the hyperplane that is closest to the ball's center. This does not work for zonotopes in general, but could be a quick heuristics.
* I think that one can characterize the intersection as follows: At least one vertex must be on one side of the hyperplane and the corresponding point-symmetric vertex must be on the other side. So a naive algorithm could just enumerate all vertices. The witness would be the intersection of the hyperplane and the connecting line between the vertices.

**Comment by mforets** [comment]
I wonder how does the current

```julia
function is_intersection_empty(Z::Zonotope{N},
                               H::Hyperplane{N},
                               witness::Bool=false
                              )::Union{Bool, Tuple{Bool, Vector{N}}} where {N<:Real}
```

compares to the new

```julia
function is_intersection_empty(X::LazySet{N},
                               hp::Union{Hyperplane{N}, Line{N}},
                               witness::Bool=false
                              )::Union{Bool, Tuple{Bool,Vector{N}}} where N<:Real
```

And in the second case, witness production is supported.

**Comment by schillic** [comment]
It looks to me that the (old) specialized implementation is more efficient (roughly equivalent to one support vector query, compared to two such queries), which does not come as a surprise. But as you mentioned, it does not support witness generation.
We could outsource the code for the witness generation and call it from the old implementation. The line should go through the zonotope's center and the vertex `x` that lies most deeply on the other side of the hyperplane. (`x` should be computable as the sum of the center and each generator direction either with -1 or 1, depending on the direction wrt. the hyperplane's normal.)
