### ISSUE TITLE
Documentation redefinition in require blocks

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2080]
Some of the documentation is only added in an `@require` block. This leads to warnings with newer `Documenter` versions when loading the corresponding optional packages. Example:

```julia
julia> using LazySets, Polyhedra
┌ Warning: Replacing docs for `LazySets.HPolytope :: Union{Tuple{Union{HRepresentation{N}, Polyhedron{N}}}, Tuple{N}} where N` in module `LazySets`
└ @ Base.Docs docs/Docs.jl:223

┌ Warning: Replacing docs for `LazySets.HPolyhedron :: Union{Tuple{Union{HRepresentation{N}, Polyhedron{N}}}, Tuple{N}} where N` in module `LazySets`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Polyhedra.polyhedron :: Union{Tuple{Union{HPolyhedron{N,VN} where VN<:AbstractArray{N,1}, HPolytope{N,VN} where VN<:AbstractArray{N,1}}}, Tuple{N}} where N<:Real` in module `LazySets`
└ @ Base.Docs docs/Docs.jl:223
┌ Warning: Replacing docs for `Polyhedra.polyhedron :: Union{Tuple{VPolytope{N,VN} where VN<:AbstractArray{N,1}}, Tuple{N}} where N<:Real` in module `LazySets`
└ @ Base.Docs docs/Docs.jl:223
```

We should instead define the functions and document them outside the block.

Here is the corresponding place for the documentation of `HPolyhedron` (second entry above):

https://github.com/JuliaReach/LazySets.jl/blob/a53c47ca6fd8516b60365cb5997bf816e7eb1143/src/Sets/HPolyhedron.jl#L680-L696

(As an aside, this specific method should actually be removed.)

**Comment by mforets** [comment]
i agree to document functions outside require blocks, so they are visible and show up in the docs. otoh i don't have warnings with `using LazySets, Polyhedra`. perhaps im using another setting than you(julia v1.3 and Documenter v1.24.5)
