### ISSUE TITLE
export Approximations module automatically

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#210]
We already have `export Approximations`, but this does not seem to work. This should also be removed if it is not needed.

**Comment by schillic** [comment]
I searched for a while and only found the `Reexport` solution.

In `LazySets.jl` add:
```julia
using Reexport
...
@reexport using .Approximations
```

@mforets: What do you think? Is another dependency worth saving the additional `using`?

**Comment by mforets** [comment]
> We already have export Approximations, but this does not seem to work.

what usage do you have in mind? if we add the line `export Approximations` just after the include "Approximations.jl", then:

in `master`:

```julia
julia> using LazySets
INFO: Recompiling stale cache file /Users/forets/.julia/lib/v0.6/LazySets.ji for module LazySets.

julia> Approximations
LazySets.Approximations
```

for me that's the correct behavior.

**Comment by schillic** [comment]
I meant this:
```julia
julia> using LazySets

help?> box_approximation
search:

Couldn't find box_approximation
Perhaps you meant Factorization
  No documentation found.

  Binding box_approximation does not exist.

julia> using LazySets.Approximations

help?> box_approximation
search: box_approximation

  box_approximation(S::LazySet)::Hyperrectangle
...
```
But maybe this is not the goal?

**Comment by mforets** [comment]
indeed, if we want to (re)-export the names defined in the Approximations, the `@reexport` helps to do just that.

in pple i wouldn't be favorable of reexporting all of Approximations, but to put (back?) the `export Approximations` should be done IMO.

**Comment by schillic** [comment]
okay...
