### ISSUE TITLE
Empty intersection in HPolygon's addconstraints! resp. isredundant

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2102]
The intersection of the lines corresponding to two-dimensional constraints can be empty due to numerical issues. Instead of raising an exception, we should add the constraint, making the polygon empty.
In the example below, constraints `Hs[2]` and `Hs[3]` are parallel, and so are `Hs[1]` and `H`. Here the intersection is nonempty.

```julia
julia> Hs = [HalfSpace([0.05125918978413134, 0.0], 0.956012965730266),
 HalfSpace([-0.0363879863894044, 0.3036279569180349], -0.370213880061176),
 HalfSpace([0.03529692609786872, -0.2945239519959644], 0.36249837124872736)];

julia> H = HalfSpace([-0.012707966980287463, 3.809113859067846e-15], -0.2348665397215645);

julia> addconstraint!(Hs, H)
ERROR: AssertionError: $(Expr(:escape, :(cap isa Singleton)))
Stacktrace:
 [1] macro expansion at /.julia/dev/LazySets/src/Assertions/Assertions.jl:23 [inlined]
 [2] isredundant(::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}, ::HalfSpace{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:320
 [3] #addconstraint!#315(::Bool, ::Bool, ::typeof(addconstraint!), ::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::HalfSpace{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:460
 [4] addconstraint!(::Array{HalfSpace{Float64,Array{Float64,1}},1}, ::HalfSpace{Float64,Array{Float64,1}}) at /.julia/dev/LazySets/src/Interfaces/AbstractHPolygon.jl:436
 [5] top-level scope at REPL[31]:1
 [6] eval(::Module, ::Any) at ./boot.jl:330
 [7] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.2/REPL/src/REPL.jl:86
 [8] run_backend(::REPL.REPLBackend) at /.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [9] top-level scope at none:0
```

**Comment by mforets** [comment]
> The intersection of the lines corresponding to two-dimensional constraints can be empty due to numerical issues. Instead of raising an exception

somehow related, the current implementation for the intersection of lines is *terrible*, https://github.com/JuliaReach/LazySets.jl/blob/master/src/ConcreteOperations/intersection.jl#L71 -- we should reason with the determinant.

**Comment by schillic** [comment]
Can you open a new issue? I want to close this one soon.

**Comment by mforets** [comment]
the issue exists: https://github.com/JuliaReach/LazySets.jl/issues/697

since the OP talks about raising an exception with the intersection of lines, i thought it was related to that issue.

about your OP, what behavior do you propose just after `addconstraint!(Hs, H)`?

**Comment by mforets** [comment]
just add the constraint?

**Comment by schillic** [comment]
The problem in the end was numerical instability. After fixing that, the old code detects that the constraints are parallel and the new constraint is added (which is the expected result).

**Comment by mforets** [comment]
hmm sorry but i'm a bit puzzled about the statement in the doctring pasted below. given that you didn't use `prune=false`, seem like a conflict with

>  the constraints are parallel and the new constraint is added 

and

> In the example below, constraints Hs[2] and Hs[3] are parallel, and so are Hs[1] and H.

if Hs[1] and H are parallel, shouldn't the function *not* add the constraint ?

```
- `prune`          -- (optional, default: `true`) flag for removing redundant
                      constraints in the end

### Algorithm

If `prune` is active, we check if the new constraint is redundant.
If the constraint is not redundant, we perform the same check to the left and to
the right until we find the first constraint that is not redundant.
```

**Comment by schillic** [comment]
Sorry, the description in the OP does not exactly capture the real problem (it was only my guess at the time of reporting it). The set in the example above is actually not empty but a normal parallelogram. During construction of this polygon when it contains three of the four constraints and you want to add the fourth one, that constraint should be added (because it is not redundant). The problem was that the code did not detect that two of the existing constraints are parallel and hence we reached a line in the code where that case was supposed to be handled.

**Comment by mforets** [comment]
ok, got it :100:
