### ISSUE TITLE
Volume of polytope

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2111]
Computing the volume of a polytope is hard. But there are polynomial-time approximation algorithms (see [here](https://mathoverflow.net/questions/979/algorithm-for-finding-the-volume-of-a-convex-polytope)). There is also a randomized algorithm based on membership queries [here](https://en.wikipedia.org/wiki/Convex_volume_approximation).

X-ref: #1806

**Comment by mforets** [comment]
There is https://juliapolyhedra.github.io/Polyhedra.jl/latest/utilities/#Polyhedra.volume, i would begin by adding

**Comment by schillic** [comment]
I checked that first but there is only a method for intervals at the moment.

**Comment by mforets** [comment]
it is implemented in solvers, such as `QHull`, see https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/191
