### ISSUE TITLE
Robust comparison for disjointness check between intervals

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2114]
https://github.com/JuliaReach/LazySets.jl/blob/2c637151709be5968415449769da3d42bb86be25/src/ConcreteOperations/isdisjoint.jl#L161

**Comment by mforets** [comment]
some details about this issue can be found here: https://github.com/mforets/escritoire/blob/master/2020/Week15/Invariant_INT.ipynb

i've been thinking what is the optimal way of integrating this into LazySets such that we have both correct type inference *and* the possibility to activate or deactivate the witness check.

my final proposal is along these lines:

```julia
function is_intersection_empty(I1::Interval{N}, I2::Interval{N}) where {N<:Real}
    return _is_intersection_empty(I1, I2, Val(false))
end

function is_intersection_empty(I1::Interval{N}, I2::Interval{N}; witness::Bool=false) where {N<:Real}
    if witness
        return _is_intersection_empty(I1, I2, Val(true))
    else
        return _is_intersection_empty(I1, I2, Val(false))
    end
end

function _is_intersection_empty(I1::Interval{N}, I2::Interval{N}, witness::Val{false}) where {N<:Real}
    return !_leq(min(I2), max(I1))  || !_leq(min(I1), max(I2))
end

function _is_intersection_empty(I1::Interval{N}, I2::Interval{N}, witness::Val{true}) where {N<:Real}
    check  = _is_intersection_empty(I1, I2, Val(false))
    return (check, [max(min(I1), min(I2))])
end
```

**Comment by schillic** [comment]
> related question: https://discourse.julialang.org/t/branch-in-dispatch-on-values/37465

In that question, `foo` was type stable but here `is_intersection_empty` is not. Have you benchmarked if that helps? I would be surprised if there is a difference.

**Comment by mforets** [comment]
the code above helps in the sense that the following 3 do not have inference problem:

```julia
@inferred is_intersection_empty(x, y) # passes
@inferred LazySets._is_intersection_empty(x, y, Val(true)) # passes
@inferred LazySets._is_intersection_empty(x, y, Val(false)) # passes
```
in `master`, it is not possible to call the sencond and third without this refactoring.

**Comment by schillic** [comment]
I can see that each `_is_intersection_empty` method is type stable. But each branch of the `if` has a different result (even a different number of results), so the combined function should not be type stable unless the compiler creates different code for different values of `witness`, in which case I would expect the original code to be type stable as well :thinking:
Do you have an explanation?

(I am fine with having these extra methods if that is needed for type stability. I just want to understand things.)

**Comment by mforets** [comment]
> I can see that each _is_intersection_empty method is type stable.

yes. and also as observed above, the combined `is_intersection_empty(x, y)` doesn't show inference problems  with `@inferred`, which is quite good in practice.

> Do you have an explanation?

no.

**Comment by mforets** [comment]
> (I am fine with having these extra methods if that is needed for type stability. I just want to understand things.)

the forums (discourse, slack) are a great place to ask such technical questions.

**Comment by schillic** [comment]
I commented in the PR that the change did not actually have an effect.

**Comment by mforets** [comment]
what effect do you expect to have? as said above the change allows https://github.com/JuliaReach/LazySets.jl/issues/2114#issuecomment-612816416

**Comment by schillic** [comment]
See [here](https://github.com/JuliaReach/LazySets.jl/pull/2119#pullrequestreview-392071194).
