### ISSUE TITLE
Do not depend on Plots.jl for testing

### ISSUE THREAD

**Issue by giordano** [JuliaReach/LazySets.jl#2139]
`Plots.jl` is a huge dependency.  As far as I can see, in [`test/unit_plot.jl`](https://github.com/JuliaReach/LazySets.jl/blob/c12e313e445f0e350250761c409f387f9c75c1e0/test/unit_plot.jl) you are not even testing anything.  I recommend you to look at what [I do](https://github.com/JuliaPhysics/Measurements.jl/blob/2ef7fadf7c2644408cff555781b9c10adfca26f6/test/plots.jl) in `Measurements.jl` to test plotting functionalities simply using `RecipesBase.jl`, so that you can remove `Plots.jl` and actually test something meaningful.

**Comment by mforets** [comment]
Thanks for the tip @giordano, we'll consider it. In this library a full run of CI usually takes like ~40minutes on Travis :tired_face: So if this can reduce such runtimes while having some tests for the plotting stuff it would already be a win.

**Comment by schillic** [comment]
We also need `Plots` for the documentation. I am not sure that this would resolve #2098 (I just commented there).

**Comment by giordano** [comment]
> In this library a full run of CI usually takes like ~40minutes on Travis tired_face So if this can reduce such runtimes while having some tests for the plotting stuff it would already be a win.

Well, not sure if it'll reduce sensibly from 40 minutes, but in a smaller project I was able to shave off 3 minutes per job by moving from Plots to RecipesBase

> We also need Plots for the documentation.

That's one job out of the 5 total, no?

**Comment by giordano** [comment]
Also, consider caching artifacts in CI: https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484.  That would help in jobs for Julia v1.3+

**Comment by mforets** [comment]
thanks @giordano for all the tips :100:
