### ISSUE TITLE
convert -> Zonotope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#214]
We can extend Bases' `convert` function to a subset of `LazySet` types, e.g. practical to convert `BallInf` (or `Hyperrectangle`) to `Zonotope`.

**Comment by schillic** [comment]
So this is "from specific to general". The other direction would be more complicated, but maybe also worth thinking about.

We could also add a conversion for any polytope type to `HPolytope`/`VPolytope`, which might be interesting for using `Polyhedra.jl`. This way we can add (inefficient) default implementations for functions between polytopic types (first convert the operands and then solve the problem for general polytopes).

**Comment by mforets** [comment]
> We could also add a conversion for any polytope type to HPolytope/VPolytope, which might be interesting for using Polyhedra.jl.

good point, i'll think about Zonotopes.

**Comment by schillic** [comment]
In #225 we added conversion from `AbstractHyperrectangle` to `Zonotope`.
@mforets: Should we close or do you want to have more conversions?

**Comment by mforets** [comment]
this type of conversion:

```julia
julia> Z
LazySets.Zonotope{Float64}([1.0, 0.0], [0.1 0.0; 0.0 0.1])
julia> convert(Zonotope{Rational{Int}}, Z)
...
```

we want to put this in `convert.jl` or in `Zonotope.jl`?

**Comment by schillic** [comment]
Since this is a same-type conversion, it could stay in the type-specific file.
Whatever you prefer.
It is a pity that this does not work out of the box...

**Comment by mforets** [comment]
Should we close this issue? The type of conversion that i mentioned above, if useful, should be sent to a new issue.
