### ISSUE TITLE
minor list

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#215]
This is an old list that I wrote down some time ago. We may want to pick some elements and create new issues, and drop the others. I just wanted to not forget them.

- i wanted to write a faster implementation for `BallInf.radius` that does not create the vector of same values explicitly
   but it did not work because julia expects an `AbstractVector`
   if we hit this issue more often, we might want to implement a `SameValueVector` type (takes time because we need to implement lots of methods from `AbstractVector`)

- do we want to add a constructor of the polygons/polyhedron with empty array but with size hint (as we do for `MinkowskiSumArray` and `CartesianProductArray`)?

- rename `iterative_refinement.jl` → `polygon_approximation.jl` (and respectively the function `approximate`)?

discussed:

- rename? **-> no**
   addconstraint! → add_constraint!
   tovrep/tohrep → to_vrep/to_hrep

- should we remove the constructor for a `CartesianProduct` from an array?
  this is what `CartesianProductArray` is for **-> has been done at some point**

- we could add specific versions of `box_approximation`/`ballinf_approximation` for simple types such as `Hyperrectangle`/`BallInf` **-> has been done at some point except for `BallInf` (but I do not consider that important)**

- pull out `MinkowskiSumArray`, `CartesianProductArray`, `SparseMatrixExp` to their own files?
  we did this for `HPolygonOpt` **-> https://github.com/JuliaReach/LazySets.jl/issues/215#issuecomment-565158151**

**Comment by mforets** [comment]
> rename? addconstraint! → add_constraint!   tovrep/tohrep → to_vrep/to_hrep

imo these are better without the _  and similarly i prefer issubset, etc -- but this is just an opinion, see discussion wrt julia Base in discourse. eventually we can have both aliased :)

**Comment by schillic** [comment]
Is there a rule when to add an underscore? For me this is not consistent. But this seems also the opinion of some people in that thread. So let us keep them.

**Comment by mforets** [comment]
> pull out MinkowskiSumArray, CartesianProductArray, SparseMatrixExp to their own files?

I think this is still valid, so if you didn't change your mind let's do this refactoring. I've opened
