### ISSUE TITLE
Implement rectification operation using zonotopes

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2155]
cf. Fig. 7 in AI2 paper

**Comment by SebastianGuadalupe** [comment]
Here is a [notebook](https://github.com/SebastianGuadalupe/Julia/blob/master/Ai2.ipynb) with a first look into it.

**Comment by mforets** [comment]
see also: https://files.sri.inf.ethz.ch/website/papers/DeepZ.pdf
