### ISSUE TITLE
Follow up of 2d zonotope vertex enum

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2208]
Mostly refactoring / internal changes. See

_Originally posted by @mforets in https://github.com/JuliaReach/LazySets.jl/pull/2199#issuecomment-650632317_

**Comment by yupbank** [comment]
thank you for the issue! since I have a general 2d vertex enum algo too, might worth doing them altogether.

**Comment by mforets** [comment]
this issue is about refactoring, which i can handle. for the new algorithm, i've opened https://github.com/JuliaReach/LazySets.jl/issues/2209.
