### ISSUE TITLE
Linear map by an interval matrix

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#221]
[IntervalMatrices.jl](https://juliareach.github.io/IntervalMatrices.jl/latest/) defines types for matrices whose coefficients are intervals. 

it would be nice to accept multiplying this by sets (which actually subtype `AbstractMatrix`), as in:

```julia
julia> using LazySets, IntervalMatrices

julia> A = IntervalMatrix([-0.9±0.1 0±0; 0±0 -0.9±0.1])
2×2 IntervalMatrices.IntervalMatrix{Float64,IntervalSets.ClosedInterval{Float64}}:
 -1.0..-0.8  0.0..0.0
 0.0..0.0    -1.0..-0.8

julia> b = BallInf(zeros(2), 1.);

julia> A * b
ERROR: MethodError: no method matching LazySets.LinearMap(::IntervalMatrices.IntervalMatrix{Float64,IntervalSets.ClosedInterval{Float64}}, ::LazySets.BallInf{Float64})
Closest candidates are:
  LazySets.LinearMap(::AbstractArray{N<:Real,2}, ::S<:LazySets.LazySet{N<:Real}) where {N<:Real, S<:LazySets.LazySet{N<:Real}} at /Users/forets/.julia/v0.6/LazySets/src/LinearMap.jl:16
Stacktrace:
 [1] *(::IntervalMatrices.IntervalMatrix{Float64,IntervalSets.ClosedInterval{Float64}}, ::LazySets.BallInf{Float64}) at /Users/forets/.julia/v0.6/LazySets/src/LinearMap.jl:43
```

**Comment by mforets** [comment]
i think the problem is that the current `LinearMap` constructor expects that the coefficients of the matrix are real numbers (`N <: Real` )

**Comment by schillic** [comment]
Agreed, we could weaken that constraint to just `N`.

**Comment by mforets** [comment]
it doesn't work with:

```julia
struct LinearMap{N, S<:LazySet{N}} <: LazySet{N}
    M::AbstractMatrix{N}
    X::S
end
```

for the example of above since `Ball1` is `Float64` and the linear map is 

```julia
julia> eltype(A)
IntervalSets.ClosedInterval{Float64}
```

**Comment by schillic** [comment]
`where N`?

**Comment by schillic** [comment]
Okay I see, then just replace `S<:LazySet{N}` by `S<:LazySet`?

**Comment by mforets** [comment]
i think we want to keep the concrete type `N`, no? in this example i would expect that the resulting linear map `A * b` is of type `IntervalSets.ClosedInterval{Float64}`. seems like we need some form of coercion.

**Comment by schillic** [comment]
Okay, then we just need two parameters (maybe `NM` and `NS` for matrix and set).
