### ISSUE TITLE
Problems with equation rendering in documentation

### ISSUE THREAD

**Issue by pauljurczak** [JuliaReach/LazySets.jl#2256]
The equations starting with `\[\begin` on https://juliareach.github.io/LazySets.jl/dev/man/polyhedral_approximations/ page do not render as expected with Chrome browser:

![ls](https://user-images.githubusercontent.com/4933032/88085612-52c34e00-cb43-11ea-9367-44153196c4b6.png)

**Comment by mforets** [comment]
oh indeed, thanks for reporting! strange, that used to display properly. we'll fix it...

**Comment by mforets** [comment]
in the meantime, you can see the displayed math from a previous release, eg. https://juliareach.github.io/LazySets.jl/v1.36/man/polyhedral_approximations/

**Comment by schillic** [comment]
This is an intended regression in `Documenter` (their issue `#1217`). We recently switched to the new version.
