### ISSUE TITLE
Overapproximate polynomial zonotope with zonotope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#230]
in #184 we add the polynomial zonotope type. we would like to add overapproximation with zonotope, this can be an overload of `overapproximate` with target set `Zonotope`.

This transformation is investigated in "Reachability analysis of nonlinear systems using conservative polynomialization and nonconvex sets", M. Althoff, HSCC'13

**Comment by mforets** [comment]
follow up in [PolynomialZonotopes.jl](https://github.com/JuliaReach/PolynomialZonotopes.jl/issues/1).

**Comment by mforets** [comment]
💀

**Comment by lucaferranti** [comment]
@mforets is this covered by #2972 ?
