### ISSUE TITLE
add LineSegment type

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#231]

**Comment by mforets** [comment]
in 2d? it could be implemented by holding the pair of points `p1`, `p2`, no?

**Comment by schillic** [comment]
This is exactly the idea. I need this for the intersection of polygons. So I also need the intersection of line segments, which is why I do not want to use `VPolygon` here but introduce an extra type.

**Comment by mforets** [comment]
alright! what we can do now is:

```julia
julia> p1, p2 = zeros(2), ones(2);
julia> plot(CH(Singleton(p1), Singleton(p2)), .1)
```
<img width="588" alt="screen shot 2018-02-10 at 07 44 49" src="https://user-images.githubusercontent.com/12424594/36061236-5fe27704-0e36-11e8-8cf4-06cb378ee51a.png">

or `VPolygon([p1, p2])`. for the new type it could plot the extreme points.
