### ISSUE TITLE
Treatment of unbounded intervals

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2349]
I realized that `IntervalArithmetic` allows to create unbounded `IA.Interval`s. However, we have the assumption that our `LS.Interval`s are bounded.

```julia
julia> x = Interval(-Inf, Inf)
Interval{Float64,IntervalArithmetic.Interval{Float64}}([-∞, ∞])

julia> isbounded(x)
true
```

Allowing for unbounded intervals would break many things because we would have to downgrade `LS.Interval` from `AbstractHyperrectangle` to `AbstractPolyhedron`.

I suggest that we add a check to the `LS.Interval` constructor and raise a warning or error if this assumption is violated.

Alternatively we could create a 1D `HalfSpace` resp. `Universe` in the `LS.Interval` constructor if one resp. both sides are unbounded, but that would make the constructor type unstable. Maybe we want to add a type-unstable convenience constructor. We can even also add specialized types for `HalfSpace1D` and `Universe1D` but I do not see why they would be useful.

**Comment by mforets** [comment]
wouldn't changing the implementation of isbounded solve the issue?

**Comment by schillic** [comment]
No, we have the assumption that `AbstractHyperrectangle`s are bounded. I cannot point to a specific example but I am rather confident that this assumption is used in many places. I would rather create a new type for unbounded intervals if there is a need for them.
