### ISSUE TITLE
Random set generation functions

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#235]
Sometimes it is helpful to create a random instance of a set type. What about a function
```julia
random(S::LazySet; N=Float64, dim::Int=2, rng=GLOBAL_RNG, seed=nothing)
```
that we would have to implement for each set type.

I am not sure how rng works in Julia; this needs to be figured out ([starting point](https://docs.julialang.org/en/stable/stdlib/numbers/#Random-Numbers-1)) (reproducibility could be important for experiments/testing).

**Comment by mforets** [comment]
Or:

```julia
random(X::Type{S}; N=Float64, dim::Int=2, rng=GLOBAL_RNG, seed=nothing) where {S<:LazySet}
```

**Comment by schillic** [comment]
Since here no default implementation exists, there is no difference in practice between the two :wink:
But I realized that we should use `rand`, which is the standard method name in Julia.

**Comment by schillic** [comment]
There is also a [random API](https://docs.julialang.org/en/stable/stdlib/Random/#Hooking-into-the-Random-API-1) in newer Julia versions.
