### ISSUE TITLE
Support vector computation for a polynomial zonotope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#239]

**Comment by schillic** [comment]
How complicated is it? It would be good to have that before the next release because it violates a general assumption of the library.

**Comment by schillic** [comment]
From a discussion: we can overapproximate with a `Zonotope`, so we do not necessarily need the support vector for plotting etc.

**Comment by schillic** [comment]
@mforets: Should we remove this one? We removed the con-convex sets anyway.

**Comment by mforets** [comment]
yep, i'm moving this to [PolynomialZonotopes.jl](https://github.com/JuliaReach/PolynomialZonotopes.jl/issues/3).

**Comment by schillic** [comment]
I close this because we cannot compute the exact support vector. The support function can be overapproximated.
