### ISSUE TITLE
Builds Failing

### ISSUE THREAD

**Issue by mileslucas** [JuliaReach/LazySets.jl#2392]
LazySets has recently (has to have been past few weeks) become broken during the build step.

Here is an example of this causing entire CI failures: https://github.com/JuliaHCI/ADI.jl/runs/1319135019?check_suite_focus=true#step:5:324 (this project depends on Photometry.jl which depends on LazySets.jl)

On slack it was pointed out that https://github.com/JuliaReach/LazySets.jl/blob/d1c38b4d6021121281b7cb6e1c70c27d2501077c/deps/build.jl#L1 causes the issues since it is depending on Pkg without actually having Pkg as a dependency of LazySets.jl.

This seems to only break the build step (i.e. I can still import and use the code on julia 1.4+)

I'm not really sure how this happened, though, since this wasn't failing even a week or two ago. I haven't bumped the minor version for LazySets.jl on Photometry.jl, either, so this must have slipped in during a patch release.

**Comment by schillic** [comment]
As far as I remember, this script was supposed to only be executed during *our* Travis build, which installs `Pkg` first:

https://github.com/JuliaReach/LazySets.jl/blob/e3f5507b22312bdaa0b1c200abe3d93c3d4a2940/.travis.yml#L31

But apparently a build script `deps/build.jl` is loaded automatically... :disappointed:

What about we rename the file and hope it is not found by the auto-build?

**Comment by mileslucas** [comment]
> But apparently a build script deps/build.jl is loaded automatically

As far as I know `deps/build.jl` gets auto-loaded by the package manager. I'm not sure where this is documented exaclty, especially now that artifacts are de-facto for vendoring libraries.

I think renaming it to anything else should fix it!

**Comment by schillic** [comment]
@mileslucas: There is a new release of `LazySets` that incorporates the fix. Can you check if the problem is gone?

**Comment by mileslucas** [comment]
@schillic problem is gone! Thanks for the quick fix.

**Comment by schillic** [comment]
Thanks for reporting!
