### ISSUE TITLE
Update `abstract type LazySet` docstring

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#240]
because:

- we there is a substype of LazySet which is not necessarily convex (polynomial zonotope),
- i think that calling `ConvexHull` "convex sets" can be confusing at first

i think we could rework the docstring of `abstract type LazySet` in the lines of:

> Abstract type for set representations and binary and n-ary operations between sets. Most subtypes of `LazySet` correspond to convex sets, i.e., sets characterized by a (possibly infinite)
intersection of halfspaces, or equivalently, sets ``S`` such that for any two
elements ``x, y ∈ S`` and ``0 ≤ λ ≤ 1`` it holds that ``λ x + (1-λ) y ∈ S``. However, convexity is not a restriction for subtyping `LazySet`.

**Comment by schillic** [comment]
> there is a substype of LazySet which is not necessarily convex (polynomial zonotope)

Then the library is inconsistent at the moment because in at least one place we assume convexity. We should first discuss how we want to mark convex sets (see #185) to make it consistent again.

Note that we have to change the description of this repository and several places in the docs as well.

**Comment by schillic** [comment]
Closed as "will not fix", see #185.
