### ISSUE TITLE
Add macro to create symmetric functions

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#241]
```
@symmetric function myfunction(arg1::T1, arg2::T2)
    (code)
end
```
should produce
```
function myfunction(arg1::T1, arg2::T2)
    (code)
end
function myfunction(arg2::T2, arg1::T1)
    (code)
end
```
Careful: There are method ambiguities for `myfunction(::T1, ::T1)` and `myfunction(::T2, ::T2)`.

**Comment by mforets** [comment]
> There are method ambiguities

there *can* be method ambiguities if either `T1` or `T2` is a `LazySet`, or i am missing sth?

**Comment by schillic** [comment]
Unless `T1 == T2` (in which case `@symmetric` does not make sense and will produce a warning of a redefined function), there *will* be ambiguities.
Just pretend you are the compiler: Which of the two functions should `myfunction(::T1, ::T1)` choose?

**Comment by mforets** [comment]
yes, ok i see. i had in mind the function `minkowski_sum(pz::PolynomialZonotope, z::Zonotope)`. here, if i do `minkowski_sum(z, z)` it will prompt the specialized m-sum for zonotopes, and if `minkowski_sum(pz, pz)` it should break, i think

**Comment by mforets** [comment]
It would be nice if `@symmetric` also produces the docstring.

**Comment by mforets** [comment]
.. or, for symmetric functions, we just document one version of the function.

**Comment by schillic** [comment]
> It would be nice if @symmetric also produces the docstring.

Sounds quite complicated :face_with_head_bandage:

> .. or, for symmetric functions, we just document one version of the function.

Yeah, let's stick to this rule for now. In 20 years, when all else is done, we can do this stuff :stuck_out_tongue:

**Comment by mforets** [comment]
Here is an implementation of the OP using the package [ExprTools](https://github.com/invenia/ExprTools.jl) (note: it's possible to roll our own macro, as explained in [this question](https://discourse.julialang.org/t/macro-that-defines-function/42969), though i think using ExprTools is more robust, and that package should be light to load and doesn't have dependencies).

```julia
macro commutative(f)
    def = splitdef(f)
    def[:args] = Any[def[:args][2], def[:args][1]]
    _f = combinedef(def)
    return quote
        $(esc(f))
        $(esc(_f))
     end
end
```
Usage:

```julia
@commutative function _intersection(S::AbstractSingleton{N}, X::LazySet{N}) where {N<:Real}
    return element(S) ∈ X ? S : EmptySet{N}(dim(S))
end
_intersection (generic function with 2 methods)

methods(_intersection)

# 2 methods for generic function _intersection:
_intersection(S::AbstractSingleton{N}, X::LazySet{N}) where N<:Real in Main at In[14]:1
_intersection(X::LazySet{N}, S::AbstractSingleton{N}) where N<:Real in Main at In[14]:1
```
```

**Comment by mforets** [comment]
Here is an implementation of the OP using the package [ExprTools](https://github.com/invenia/ExprTools.jl) (note: it's possible to roll our own macro, as explained in [this question](https://discourse.julialang.org/t/macro-that-defines-function/42969), though i think using ExprTools is more robust, and that package should be light to load and doesn't have dependencies).

```julia
macro commutative(f)
    
    # split the function definition expression
    def = splitdef(f)
    fargs = copy(def[:args])

    # swap arguments 1 and 2
    aux = def[:args][1]
    def[:args][1] = def[:args][2]
    def[:args][2] = aux
    
    # the new function calls f with swapped arguments
    def[:body] = quote ($(def[:name]))($(fargs...)) end

    _f = combinedef(def)
    return quote
        $(esc(f))
        $(esc(_f))
     end
end
```
Usage:

```julia
@commutative function _intersection(S::AbstractSingleton{N}, X::LazySet{N}) where {N<:Real}
    return element(S) ∈ X ? S : EmptySet{N}(dim(S))
end
_intersection (generic function with 2 methods)

methods(_intersection)

# 2 methods for generic function _intersection:
_intersection(S::AbstractSingleton{N}, X::LazySet{N}) where N<:Real in Main at In[14]:1
_intersection(X::LazySet{N}, S::AbstractSingleton{N}) where N<:Real in Main at In[14]:1


@macroexpand @commutative function _intersection(S::AbstractSingleton{N}, X::LazySet{N}) where {N<:Real}
    return element(S) ∈ X ? S : EmptySet{N}(dim(S))
                    end
               
                    quote
    #= In[80]:25 =#
    function _intersection(S::AbstractSingleton{N}, X::LazySet{N}) where N <: Real
        #= In[86]:1 =#
        #= In[86]:2 =#
        return if element(S) ∈ X
                S
            else
                EmptySet{N}(dim(S))
            end
    end
    #= In[80]:26 =#
    function _intersection(X::LazySet{N}, S::AbstractSingleton{N}) where N <: Real
        #= In[80]:13 =#
        _intersection(S::AbstractSingleton{N}, X::LazySet{N})
    end
end
                    
                    ```

**Comment by schillic** [comment]
Here is a new idea: if we define a total order on set types `T<:LazySet` (e.g., by assigning a unique number), the implementation of binary operations `foo(X, Y)` can be:

```julia
function foo(X::SX, Y::SY, args...; kwargs...)
    if SX < SY
        return _foo_oneway(X, Y, args...; kwargs...)
    else
        return _foo_oneway(Y, X, args...; kwargs...)
    end
end
```

And then we only need one method `_foo_oneway` for each combination.

The downside is that this order is only applicable inside the library. If you create a new set type (inside or outside the library), you have to come up with a new number and there is a risk that some other package already chose that number. So I suggest something slightly more complicated. We have a function (e.g., `register_lazyset`) that you have to call after the creation of a new subtype. This function chooses a fresh number for the type for you. Maybe one can even register an automatic process when a new type is created at compile time to make this automatic, but it does not sound like a lot of work.

**Comment by mforets** [comment]
Have you checked `@commutative` in [this PR](https://github.com/JuliaReach/LazySets.jl/pull/2286)? It should be easy to use and to extend (it was hold by Julia v1.0).

**Comment by schillic** [comment]
I forgot about that. It looks nice but when I played around with it, I could not get it to work in v1.0.

One way out is to have a helper function with individual name for each current documented method. I would actually prefer that for two reasons:
1. For disambiguation we usually want to refer to one particular method.
2. Right now `?intersection` is not helpful at all and [the Julia documentation recommends only documenting the function](https://docs.julialang.org/en/v1/manual/documentation/#Functions-and-Methods) for that reason.

But that would be a bit more work.

**Comment by mforets** [comment]
>  I could not get it to work in v1.0.

The easiest solution may be to wait 1 month or 2 until v1.6 is the new LTS.

**Comment by mforets** [comment]
> Right now ?intersection is not helpful at all

why is that? i find it helpful to see the docstring of each different implementation
