### ISSUE TITLE
Use box_approximation instead of overapproximate(X, Hyperrectangle)

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2415]
In #1556 we unified `box_approximation` and `overapproximate(X, Hyperrectangle)`:

```julia
box_approximation(X) = overapproximate(X, Hyperrectangle)
```

I suggest that we actually swap them:

```julia
overapproximate(X, Hyperrectangle) = box_approximation(X)
```

The motivation is to bring some order into the `overapproximate.jl` file where we have too many methods and it is very hard to find out which special cases of the box approximation we have implemented. I find it easier to go to `box_approximation.jl` and search for the signature `box_approximation(X::MySetType)`.

**Comment by mforets** [comment]
> I suggest that we actually swap them:

:+1:  sounds good, no objections
