### ISSUE TITLE
Revise `overapproximate`

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#242]
- if `X` is any `LazySet`, we can do: `overapproximate(Y)` that calls `overapproximate(S, HPolygon)` and this is in turn a box overapproximation

- there is `overapproximate(Y, 1e-3)` that overapproximates with a polygon for the given tolerance

- we started to add specialized functions `overapproximate(S, set_type)` (eg. convex hull of two zonotopes)

proposal: add `overapproximate(Y, HPolygon, error_tolerance)`

**Comment by schillic** [comment]
`overapproximate(Y, HPolygon, error_tolerance)`? What is the behavior? Why do we need the argument `HPolygon`?

**Comment by mforets** [comment]
there is `overapproximate(S, HPolygon)` that makes a box overapprox, but there is no `overapproximate(S, HPolygon, error_tol)` that gives a better tolerance

**Comment by schillic** [comment]
Yes there is? `overapproximate(Y, 1e-3)`!

**Comment by mforets** [comment]
proposal: make this change

```julia
function overapproximate(S::LazySet, ::Type{<:HPolygon}, ɛ::Real)::HPolygon
    @assert dim(S) == 2
    return tohrep(approximate(S, ɛ))
end

# iterative refinement using polygons; HPolygon is assumed
overapproximate(S::LazySet, ɛ::Real) = overapproximate(S::LazySet, ::Type{<:HPolygon}, ɛ::Real)
```

**Comment by schillic** [comment]
Ah okay.
The last line should be `overapproximate(S::LazySet, ɛ::Real) = overapproximate(S, ::HPolygon, ɛ)`

**Comment by schillic** [comment]
I just saw that we have `decompose(S::LazySet, ɛ::Real, [set_type]::Type=HPolygon)`. Can we make the order consistent with both functions? I have no preference.

**Comment by mforets** [comment]
good, i didn't see that.

**Comment by mforets** [comment]
@schillic, having updated `decompose`, is the proposed change in this thread still valid?

**Comment by schillic** [comment]
Yes, except that we should change the order of the arguments and make both arguments optional.
