### ISSUE TITLE
Plotting large samples is slow

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2464]
I found that plotting samples of sets (eg. long lists of singletons) is very inefficient to the extent that it takes an extremely long time to plot only ~5000 points using the plot recipe for a list of singletons.
 
```julia
B = (1 .. 2) × (3 .. 4)
Bs = sample(convert(Hyperrectangle, B), 1000);

@time Plots.plot(Singleton.(Bs))
  0.681963 seconds (1.96 M allocations: 97.579 MiB, 3.95% gc time)

x = [p[1] for p in Bs];
y = [p[2] for p in Bs];
@time plot(x, y, seriestype=:scatter, lab="")
  0.002430 seconds (2.96 k allocations: 189.648 KiB)

```

**Comment by schillic** [comment]
If I remember correctly, our plot recipe for a list of sets works as follows:

* Obtain the list of the vertices.
* Obtain the x and y coordinates for each vertex.
* Concatenate the lists of x and y coordinates for all sets, separated by a `NaN` entry.
* Use the `:shape` plot.

I do not understand how it finds out that it can use a scatter plot after this conversion :thinking:

**Comment by mforets** [comment]
True. The method in https://github.com/JuliaReach/LazySets.jl/pull/2465 is to write a plot recipe plot recipe for singletons. I tried it and it works as expected and now I can plot ~5000 samples quickly.
