### ISSUE TITLE
Inplace array n-ary constructors

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#250]
Example: to introduce `ConvexHull!(a, b)` such that if `a` is a set and `b` is a `ConvexHullArray`, it modifies in-place the array of `b`.

Similarly, introduce a `MinkowskiSum!` as a shortcut of the lazy operation (`+`) followed by modifying the array.

**Comment by schillic** [comment]
Do you mean that `+` should use the modifying version?

**Comment by mforets** [comment]
> Do you mean that + should use the modifying version?

no, i wouldn't change `+(X::LazySet, Y::LazySet) = MinkowskiSum(X, Y)` and  `⊕(X::LazySet, Y::LazySet) = +(X, Y)`, as it is now.

**Comment by schillic** [comment]
Okay thanks, then I know what to do.
