### ISSUE TITLE
Make ready for Julia v1.6

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2503]
See https://github.com/JuliaReach/LazySets.jl/pull/2502

**Comment by schillic** [comment]
All normal tests pass in #2507, so I think we are (almost) good. The only necessary change is in the doctests: `Array{T,1}` becomes `Vector{T}` and `Array{T,2}` becomes `Matrix{T}`. This can be fixed with a script.

**Comment by mforets** [comment]
thanks :mage_man: , i'll try that and send the PR

**Comment by schillic** [comment]
That would break the doctests with v1.5. These versions are unfortunately incompatible. I am not sure about already making the jump before the official release.

**Comment by mforets** [comment]
ah, true, we can't merge it till that time
