### ISSUE TITLE
Concrete projection a hyperrectangular cartesian product

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2521]
```julia
X = Interval(1, 2) × Hyperrectangle(zeros(2), ones(2))

LazySets.project(X, [1, 3])

AssertionError: package 'Polyhedra' not loaded (it is required for executing `linear_map with elimination`)
```
but the result is as hyperrectangle.

**Comment by schillic** [comment]
`project(X × Y, [1, 3]) could by default return a `CartesianProduct` of the individual projections (or only the individual projection if it only lives in one set). That would already be an improvement.

**Comment by mforets** [comment]
true. i'll mark that as a separate issue.
