### ISSUE TITLE
Implement an_element function for LinearMap

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#254]
We have a default implementation for this function, but it uses a support vector query.
For a `LinearMap` this should be simple: multiply with the (EDIT: wrong: inverse; right: original) map and call `an_element` for the wrapped set. This can be more efficient.

**Comment by mforets** [comment]
Like `L.M * an_element(L.X)`? we don't need the inverse map, no?

**Comment by schillic** [comment]
You are right :+1:

**Comment by mforets** [comment]
>  This can be more efficient.

Yes. For instance,

```julia
for n in [2, 10, 20]
    B = BallInf(ones(n), 1.)
    M = rand(n, n)
    L = M * B # lazy
    println("n = $n")
    @btime an_element($L)
    @btime an_element2($L)
end
```

where

```julia
function an_element2(lm::LinearMap)
    return lm.M * an_element(lm.X)
end
```

**Comment by mforets** [comment]
[this test](https://github.com/JuliaReach/LazySets.jl/blob/master/test/unit_LinearMap.jl#L58) works with `an_element2`
