### ISSUE TITLE
Make multiplication with a scalar fall back to scale

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2609]
```julia
julia> X = rand(Interval)
Interval{Float64,IntervalArithmetic.Interval{Float64}}([0.419371, 1.82231])

julia> 2 * X
LinearMap{Float64,Interval{Float64,IntervalArithmetic.Interval{Float64}},Int64,SparseArrays.SparseMatrixCSC{Int64,Int64}}(
  [1, 1]  =  2, Interval{Float64,IntervalArithmetic.Interval{Float64}}([0.419371, 1.82231]))
```

I would have expected that I get a scaled interval here.

I propose to redefine `*(α::Number, X::LazySet) = scale(α, X)`.

**Comment by mforets** [comment]
:+1:  why not. it is a special case. not sure about the general definition over `LazySet` though, because that needs to implement `scale` on every lazy set. on the other hand, the LinearMap only needs to have defined the support function so i think we should keep that behavior

**Comment by schillic** [comment]
Okay, maybe we can automatically define the methods for those sets that have `scale` defined.

**Comment by schillic** [comment]
I decided against that. This would make the library inconsistent.
