### ISSUE TITLE
Intersection of lines and line segments

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#262]
See also the book [Graphics Gems](
http://inis.jinr.ru/sl/vol1/CMC/Graphics_Gems_1,ed_A.Glassner.pdf) (eg. Goldman's chapter about Intersection of two lines in three-space, p. 304).

**Comment by schillic** [comment]
For the `LineSegment` we have `is_intersection_empty` but not `intersection`. In this case they are almost identical, so we should rather write the function for `intersection` and call this function from `is_intersection_empty` which then interprets the output.
