### ISSUE TITLE
Revise plot recipe for UnionSet

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2647]
Eg. 

```
julia> typeof(swept)
UnionSetArray{Float64, Zonotope{Float64, Vector{Float64}, Matrix{Float64}}}

julia> plot(swept; aspect_ratio=1.0, color=colorant"green", label="continuous over-approximated")
```
prints the label as many times as there are sets. Probably we need to review how are `UnionSetArray` plotting options handled.

**Comment by goretkin** [comment]
```julia
julia> using LazySets, Plots

julia> plot(UnionSetArray([BallInf([0.0, y], 0.25) for y =[1, 2, 3]]); aspect_ratio=1.0,  label="One Thing")
```

Current behavior:

![image](https://user-images.githubusercontent.com/581043/113734161-1b90cf00-96c9-11eb-8bab-e371eb1c3561.png)


Expected:
Three shapes, all with the same color, and only one label.

**Comment by mforets** [comment]
:+1:  I think that's a reasoable change. Same label (obvious) and same color: because they are all part of the same set.

**Comment by mforets** [comment]
(I would like to have an option for all distinct colors though, this is often useful when for example we plot the result of splitting a set).

**Comment by goretkin** [comment]
I think the behavior should match this, including how to get distinct colors or not:

```julia
julia> prob = @ivp(x' = zeros(2,2) * x + [0.1, 0.2], x(0) ∈ BallInf([0.0, 0.0], 0.5));

julia> sol = solve(prob, tspan=(0.0, 1.0), alg=GLGM06(δ=0.1));

julia> plot(sol.F; vars=(1,2), label="One Thing")
```

![image](https://user-images.githubusercontent.com/581043/113735705-8098f480-96ca-11eb-9656-975e8becddc2.png)
