### ISSUE TITLE
How to Get high/low or max/min of a LazySet

### ISSUE THREAD

**Issue by chelseas** [JuliaReach/LazySets.jl#2667]
I performed some operations on a LazySet:

`h::HyperRectangle{...} * 1.5 + Interval(1.0, 1.0)`

Where the hyperrect is 1D. The result should be a hyperrect too. And I would like to take high() and low() of the resulting hyperrect. But it says

`ERROR: MethodError: no method matching high(::MinkowskiSum{Float64,LinearMap{Float64,Hyperrectangle{Float64,Array{Float64,1},Array{Float64,1}},Float64,SparseArrays.SparseMatrixCSC{Float64,Int64}},Interval{Float64,IntervalArithmetic.Interval{Float64}}})
Closest candidates are:
  high(::MyHyperrect) at /Users/Chelsea/Dropbox/AAHAA/src/OVERT/MIP/src/mip_utils.jl:31
  high(::InfiniteHyperrectangle) at /Users/Chelsea/Dropbox/AAHAA/src/OVERT/models/problems.jl:53
  high(::AbstractSingleton{N}) where N<:Real at /Users/Chelsea/.julia/packages/LazySets/85DMr/src/Interfaces/AbstractSingleton.jl:86
  ...`

How do I do this?

**Comment by mforets** [comment]
In the latest release we added `low(X, i)` and `high(X, i)` for any LazySet `X`. After you update to the latest release (`] up LazySet`), you can try `low_vals = [low(X, i) for i in 1:dim(X)]` and similarly for `high`.

**Comment by schillic** [comment]
The problem is that `h::Hyperrectangle{...} * 1.5 + Interval(1.0, 1.0)` is not a `Hyperrectangle` again. We define `+` as the lazy Minkowski sum. You can do `minkowski_sum(X, Y)` to compute the concrete Minkowski sum.
