### ISSUE TITLE
Checking equality of Complements Unexpected Behavior.

### ISSUE THREAD

**Issue by castrong** [JuliaReach/LazySets.jl#2686]
The following code comparing two complements which I would expect to be equal prints out false. 
`        
HS = HalfSpace([-1.0, -1.0], 0.0)
println(Complement(HS) == Complement(HS))
`
Is this an issue or is it expected behavior?

**Comment by schillic** [comment]
This works now.

```julia
julia> HS = HalfSpace([-1.0, -1.0], 0.0)
HalfSpace{Float64, Vector{Float64}}([-1.0, -1.0], 0.0)

julia> Complement(HS) == Complement(HS)
true
```
