### ISSUE TITLE
Interval set type

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#270]
We need:
* multiply interval vs interval
* multiply interval vs scalar
* take Minkowski sum of interval and interval
* `overapproximate` (no-op)
* `decompose`

**Comment by mforets** [comment]
we can approach this by: treating a real interval as a numeric type, and the no-ops can be defined for scalars.

**Comment by schillic** [comment]
It is not clear to me what you mean by numeric type. Do we want to have `BallInf{Interval}`?
The no-op can simply be achieved by defining `overapproximate(I::Interval) = I`.

**Comment by mforets** [comment]
i mean to not add a new set type; just use them as scalars. all the operations of above work out of the box; the no-op is `overapproximate(x::N) = x where {N <:Real}`

**Comment by schillic** [comment]
But we call `overapproximate` for sets.

**Comment by mforets** [comment]
well, that is a problem of overloading functions names, overapproximate is doing nothing!

**Comment by schillic** [comment]
But the result is a `CartesianProduct` of ... intervals, right? For this they must subtype `LazySet`.

**Comment by mforets** [comment]
ultimately we'll see if we hit some issue doing [#74](https://github.com/JuliaReach/Reachability.jl/issues/74)

**Comment by mforets** [comment]
> But the result is a CartesianProduct of ... intervals, right? For this they must subtype LazySet.

point taken. let's do one LazySet extension (wrapper) around an existing interval arithmetic element 👍

**Comment by mforets** [comment]
type proposal:

```julia
using LazySets, IntervalArithmetic

const IA = IntervalArithmetic

"""
    Interval{N, IN <: IA.AbstractInterval{N}} <: LazySet{N}

Type representing an interval on the real line. 
"""
struct Interval{N, IN <: IA.AbstractInterval{N}} <: AbstractPointSymmetricPolytope{N}
   dat::IN
end
# type-less convenience constructor
Interval{N, IN <: IA.AbstractInterval{N}}(interval::IN) = Interval{N, IN}(interval)
```

**Comment by schillic** [comment]
Looks good. It could also be a `AbstractPolygon`. Implementing `AbstractPointSymmetricPolytope` is simpler. Apart from that I do not see any arguments for one choice over the other.

**Comment by schillic** [comment]
What does `dat` stand for?

**Comment by mforets** [comment]
> Looks good. It could also be an AbstractPolygon. Implementing AbstractPointSymmetricPolytope is simpler.

yes, and actually `dim(P::AbstractPolygon) = 2` so let's go for `AbstractPointSymmetricPolytope`.

> What does dat stand for?

the field name with the data but we could use another name. should be used only internally.

**Comment by schillic** [comment]
Is `dim(I::Interval)` not `2`?

**Comment by schillic** [comment]
Maybe `import IntervalArithmetic.AbstractInterval` to avoid the namespace stuff.

**Comment by mforets** [comment]
think about it as a unidimensional interval over the real line.

the definition in the library is:

```julia
abstract type AbstractInterval{T} <: Real end

struct Interval{T<:Real} <: AbstractInterval{T}
    lo :: T
    hi :: T

    function Interval{T}(a::Real, b::Real) where T<:Real

        if validity_check

            if is_valid_interval(a, b)
                new(a, b)

            else
                throw(ArgumentError("Interval of form [$a, $b] not allowed. Must have a ≤ b to construct interval(a, b)."))
            end

        end

        new(a, b)

    end
end
```

**Comment by schillic** [comment]
Oh, silly me, it is 1D of course :+1:

**Comment by mforets** [comment]
i've updated the previous comment within `@require` block. that type can be used as


```julia
julia> using LazySets, IntervalArithmetic
INFO: Precompiling module LazySets.

julia> x = LazySets.Interval(IA.Interval(0.0, 1.0))

LazySets.Interval{Float64,IntervalArithmetic.Interval{Float64}}([0, 1])
```

what i dislike is that one needs to use the `LazySets` and `IA` at each time you create the object, but i don't see another approach.

**Comment by schillic** [comment]
You can define a type alias for each of them.
```julia
IN = IA.Interval
ITV = LazySets.Interval
```
But I agree that this is bogus.
Maybe also add a constructor that takes two numbers.

**Comment by mforets** [comment]
>  Maybe also add a constructor that takes two numbers.

that's a good idea.
