### ISSUE TITLE
Adjusting DEFAULT_PLOT_LIMITS?

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#2700]
Is it possible to fix this behavior? Idk what goes wrong, since [_bounding_hyperrectangle](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Plotting/plot_recipes.jl#L86) uses information on the current limits.

```julia
# the set should go up to 1200
plot(HalfSpace([1.0, 0.0], 1200.), c=:red, alpha=.4, xlims=(0, 2600), ylims=(0, 650))
```

![Screenshot from 2021-05-18 06-55-54](https://user-images.githubusercontent.com/12424594/118631689-2188ce00-b7a6-11eb-8bab-4df42064113f.png)

**Comment by schillic** [comment]
My guess is that the old plot limits are used (and if there are none, then we use the box with radius 1000 I think).¹ So we would need to check whether the call passes `xlims`/`ylims` and respect those as well. I am not sure whether we have access to these, though.

¹`plot(xlims=(0, 2600), ylims=(0, 650)); plot!(HalfSpace([1.0, 0.0], 1200.), c=:red, alpha=.4)` works.
