### ISSUE TITLE
Fix hyperrectangle plot

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#272]
for example, `h = Hyperrectangle(center=[0.005, 1.1], radius=[0.005, 0.861785])` displays two triangles.

**Comment by schillic** [comment]
Blind guess: `vertices_list` returns the vertices neither in clockwise nor counter-clockwise fashion.
If this is the problem, I see two solutions:
1. Change the `vertices_list` implementation (also of all other `AbstractPolytope` types).
2. Change the plot recipe such that it sorts the vertices. Algorithm: Start with any vertex, compute the angle to all other vertices, choose the smallest one, and draw the line.

**Comment by mforets** [comment]
good, i would try with your solution 2 relying on `convex_hull`.
