### ISSUE TITLE
Warning shown when Makie is installed

### ISSUE THREAD

**Issue by fcdimitr** [JuliaReach/LazySets.jl#2748]
I guess there is no longer an `AbstractPlotting` submodule in `Makie`; the line

https://github.com/JuliaReach/LazySets.jl/blob/6c26d0903fbf61593041166328a1e4fef8958f7f/src/Plotting/mesh.jl#L16

raises a warning when importing `LazySets`. 

```julia
┌ Warning: Error requiring `Makie` from `LazySets`
│   exception =
│    LoadError: UndefVarError: AbstractPlotting not defined
│    Stacktrace:
│      [1] top-level scope
│        @ ~/.julia/packages/LazySets/offKF/src/Plotting/mesh.jl:16
│   ...
└ @ Requires ~/.julia/packages/Requires/7Ncym/src/require.jl:49
```

Probably related to https://discourse.julialang.org/t/ann-makie-v-0-13/61522

If I am not mistaken, the only use of the submodule is to get the `min/max` color ranges.

**Comment by mforets** [comment]
Ok, thanks for raising this issue. Do you care to send a quick PR?

**Comment by schillic** [comment]
Thanks, I will send a fix now.

**Comment by schillic** [comment]
Thanks again for reporting, @fcdimitr! We have released a new version just now.

**Comment by fcdimitr** [comment]
I updated my projects to the new version and can verify that the issue has been resolved.

Thank you very much for the quick fix!
