### ISSUE TITLE
Inclusion check for Ball2 in polyhedron

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#2805]
The following are equivalent for Euclidean ball `B` and polyhedron `P`:

1. `B` is contained in `P`.
2. For each of `P`'s constraints, `B`'s corresponding support vector is contained in `P`.
3. For each of `P`'s constraints, `B`'s corresponding support value is smaller. (This is more efficient to check than 2.)

**Comment by mforets** [comment]
The third method is the one used by default (`_issubset_constraints_list`)

```julia
julia> P = convert(HPolyhedron, rand(Hyperrectangle, dim=6));

julia> B = rand(Ball2, dim=6);

julia> B ⊆ P
false

julia> @which B ⊆ P
issubset(X::LazySet, P::AbstractPolyhedron) in LazySets at /home/mforets/.julia/dev/LazySets/src/ConcreteOperations/issubset.jl:273
```
