### ISSUE TITLE
Generalize dimension of overapproximate(S, ::Hyperrectangle)

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#287]
Currently it only works for dimension two. However, we should have at least one type of higher dimension, and it would be rather simple in this case.

**Comment by mforets** [comment]
If i'm not mistaken it amounts to calling [box_approximation](https://juliareach.github.io/LazySets.jl/latest/lib/approximations.html#LazySets.Approximations.box_approximation) from `Approximations.`

**Comment by schillic** [comment]
Do we even need the 2D version? I think not.

**Comment by mforets** [comment]
Yes.
