### ISSUE TITLE
Deprecated GLPKMathProgInterface brings forward compatibility issues of LazySets with other packages

### ISSUE THREAD

**Issue by project-torrey-pines** [JuliaReach/LazySets.jl#2922]
https://github.com/JuliaOpt/GLPKMathProgInterface.jl is a deprecated package, which limits GLPK to version <0.13

This is an issue for packages that rely on more modern versions of GLPK, such as ConstructiveGeometry (https://github.com/plut/ConstructiveGeometry.jl) which requires GLPK to version =0.14

![image](https://user-images.githubusercontent.com/94212550/150017419-86ee39a6-44a8-4736-a0f0-4cbf0398e621.png)

**Comment by mforets** [comment]
Thanks for raising the issue, which we are aware of. Unfortunately, we haven't got around updating LazySets to the new interface. 

Well, this is not actually true; there is an old PR addressing this issue https://github.com/JuliaReach/LazySets.jl/pull/1701 but would probably require a major update. Perhaps we should upgrade to https://github.com/jump-dev/MatrixOptInterface.jl directly.

If you have interest, contribution is welcome.

**Comment by schillic** [comment]
FYI we are working on a fix in #2923 but we hit some external problem.

**Comment by mforets** [comment]
Fixed in https://github.com/JuliaReach/LazySets.jl/pull/2923
