### ISSUE TITLE
mean, center, meta-functions 

### ISSUE THREAD

**Issue by ga72kud** [JuliaReach/LazySets.jl#2947]
Thank you for the really awesome package. I am testing a bit with the sets and I am wondering if there is a possibility to get additional functionality to get the center of a transformed set. For example I have the following code 

```julia
using LazySets, ReachabilityAnalysis
using Plots
plot()
plot(layout=(3,1), aspect_ratio=:equal)

A=ReachabilityAnalysis.BallInf([2.0;2.0], 2.0)
Ra=ReachabilityAnalysis.ReachSet(A, 0.0..1.0)
B=ReachabilityAnalysis.BallInf([3.0;2.0], 3.0)
Rb=ReachabilityAnalysis.ReachSet(B, 1.0..2.0)
F=ReachabilityAnalysis.Flowpipe([Ra,Rb])
plot!(F, vars=(1,2), lab="F", subplot=1)



C=Hyperrectangle([0.0;0.0], [1.0;2.0])
Rc=ReachabilityAnalysis.ReachSet(C, 0.0..1.0)

D=Hyperrectangle([0.0;4.0], [2.0;1.0])
Rd=ReachabilityAnalysis.ReachSet(D, 1.0..2.0)

NewF=F=ReachabilityAnalysis.Flowpipe([Rc, Rd])
plot!(NewF, vars=(1,2), lab="F", subplot=2)

B=Ball2([3.0;4.0], .2)
B3=Ball2([1.0;4.0; 1.0], .2)
X=Hyperrectangle([3.0;4.0], [1.0; 1.2])
RX=ReachabilityAnalysis.ReachSet(X, 0.0..1.0)
M=[1.0 0.0; 0.0 1.0]
newRX=linear_map(M, RX)

TX=Translation(RX.X, [1.0, 2.0])
BX=Bloating(TX, 0.2, 2.0)
BMX=Bloating(TX, -0.5, 2.0)
plot!(B, vars=(1,2), lab="B", subplot=3)
plot!(X, vars=(1,2), lab="X", subplot=3)
plot!(TX, vars=(1,2), lab="TX", subplot=3)
plot!(BX, vars=(1,2), lab="BX", subplot=3)
plot!(BMX, vars=(1,2), lab="BMX", subplot=3)
plot!(project(B3, [1, 2]),vars=(1,2), lab="B3", subplot=3)

```

In the last few  lines, I have for example the set BX from a translation and a bloating. I am wondering why there is no functionality for center(BX) to get the center other mean of the set.

**Comment by mforets** [comment]
> I have for example the set BX from a translation and a bloating. I am wondering why there is no functionality for center(BX) to get the center other mean of the set.

Because it is a feature which hasn't been implemented, but I agree that would be nice to add. The implementation should be straightforward: first, define `center` for the lazy translation (in case it is not yet available), and do the same for the lazy bloating.

**Comment by ga72kud** [comment]
ok, I see. is there any possibility to overapproximate the sets or to simplify it. I agree that if I would do a single translation and bloating it is quite obvious to compute it on my own code. If I have more complex sequences it would be nice to have something like <<single set>> instead of  complex set = operationX(...operationB(operationA(single set))). 

does simplify(complex set) or overapproximate(complex set) exist or something to simplify it. I am trying to use a workaround but it would be a nice feature request.

**Comment by mforets** [comment]
No need to close the issue; we shall keep it open until such feature is added.

> If I have more complex sequences it would be nice to have something like <> instead of complex set = operationX(...operationB(operationA(single set))).

This is not a problem due the way composition of sets is implemented in this library. In other words, the center of a `Translation` doesn't need to reason about the actual set that is wrapped (can also a a lazy operation); it just implements the operation of summing the center of the translated set `X` and the translation vector `v`.

**Comment by mforets** [comment]
> does simplify(complex set) or overapproximate(complex set) exist or something to simplify it. I am trying to use a workaround but it would be a nice feature request.

Yes, these things exist depending on what type of output you would like. If you haven't done so I suggest you look at the documentation of `overapproximate` in the online docs, our article ([here](https://proceedings.juliacon.org/papers/10.21105/jcon.00097)), or otherwise ask :)

**Comment by ga72kud** [comment]
Ok thanks

**Comment by mforets** [comment]
@ga72kud The new release has the functionality to get the center of a translated set; try it after updating the package (`] up`).

**Comment by ga72kud** [comment]
@mforets @schillic awesome !!!
