### ISSUE TITLE
Issue calling convex_hull with new LazySets version

### ISSUE THREAD

**Issue by castrong** [JuliaReach/LazySets.jl#2973]
In NeuralVerification.jl when calling convex_hull at

[https://github.com/sisl/NeuralVerification.jl/blob/789e3a2bfbb2a2bfe25c6f0455888205b0af8394/src/reachability/ai2.jl#L75-L77](https://github.com/sisl/NeuralVerification.jl/blob/789e3a2bfbb2a2bfe25c6f0455888205b0af8394/src/reachability/ai2.jl#L75-L77)

we are getting the following error

```
MethodError: no method matching removevredundancy!(::Polyhedra.Interval{Float64, StaticArrays.SVector{1, Float64}, StaticArrays.Size{(1,)}}; ztol=1.4901161193847656e-7)
  Closest candidates are:
    removevredundancy!(::Polyhedra.Interval) at /Users/castrong/.julia/packages/Polyhedra/NGGvZ/src/interval.jl:201 got unsupported keyword argument "ztol"
    removevredundancy!(::Polyhedra.Polyhedron; strongly, planar) at /Users/castrong/.julia/packages/Polyhedra/NGGvZ/src/redundancy.jl:119 got unsupported keyword argument "ztol"
    removevredundancy!(::CDDLib.Polyhedron) at /Users/castrong/.julia/packages/CDDLib/izPqs/src/polyhedron.jl:244 got unsupported keyword argument "ztol"
```

 If we restrict LazySets = "< 1.57.0" then the error goes away. In the most recent version notes for LazySets, I saw  the enhancement "Pass ztol to removevredundancy!" which seems related to this error. Is there something I'm missing in updating this call to accommodate the new LazySets version?

I currently have CDDLib v0.7.0 and Polyhedra v0.6.17

**Comment by schillic** [comment]
There was a fix that relies on an API change in `Polyhedra` v7. Since we use `Polyhedra` only as an optional dependency, we generally cannot enforce to use that new version. So you need to make sure to use the new version yourself, sorry.

**Comment by castrong** [comment]
That makes sense, thank you!
