### ISSUE TITLE
Index problems with convex_hull

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#298]
`ERROR: LoadError: BoundsError: attempt to access 58-element Array{Array{Float64,1},1} at index [52:60]`

```julia
using Reachability, Plots

compute(o::Pair{Symbol,<:Any}...) = compute(Options(Dict{Symbol,Any}(o)))

function compute(input_options::Options)
    # =====================
    # Problem specification
    # =====================
    n = 10
    n_by_2 = div(n, 2)

    # dynamics matrix
    A = [0.0 0.0 0.0 0.38899 0.0 0.0 0.264754 0.0 0.0 0.359651;
        0.753939 0.315801 0.963512 0.0 0.84734 0.542319 0.0 0.0288624 0.997182 0.0;
        0.330064 0.706121 0.0 0.652576 0.0 0.0 0.0 0.0564377 0.0 0.958416;
        0.0 0.454368 0.0 0.22354 0.416214 0.996172 0.0 0.0 0.0213008 0.0;
        0.463892 0.416456 0.201901 0.483932 0.0 0.00284869 0.247812 0.0 0.458052 0.0;
        0.373961 0.0224056 0.0 0.00731102 0.940357 0.550507 0.421588 0.762804 0.95225 0.174703;
        0.00352107 0.00179379 0.256352 0.0157392 0.030967 0.0 0.324303 0.352399 0.0 0.0;
        0.0 0.0 0.751047 0.0 0.0 0.0 0.568179 0.0 0.0 0.864433;
        0.376129 0.968669 0.254797 0.557744 0.337848 0.858118 0.958182 0.0366442 0.0 0.561499;
        0.0 0.0 0.421189 0.617612 0.0 0.0 0.753434 0.645403 0.0 0.0]

    # initial set
    X0 = Singleton(zeros(n))

    # input set
    m = 2
    B = sparse(1:n, [(i % m + 1) for i = 0:n-1], -ones(n), n, m)
    U = B * Hyperrectangle(ones(m), zeros(m))

    # instantiate continuous LTI system
    S = ContinuousSystem(A, X0, U)

    # ===============
    # Problem solving
    # ===============
    problem_options = Options(:vars => [1, 2],
                              :partition => [(2*i-1:2*i) for i in 1:n_by_2], # 2D blocks
                              :set_type => HPolygon,
                              :ε => 1e-5,
                              :plot_vars => [1, 2])

    result = solve(S, merge(input_options, problem_options))

    # ========
    # Plotting
    # ========
    if input_options[:mode] == "reach"
        println("Plotting...")
        tic()
        plot(result)
        @eval(savefig(@relpath "point_X0.png"))
        toc()
    end
end # function

# Reach tube computation in dense time
compute(:δ => 1e-1, :N => 3, :mode=>"reach", :verbosity => "info");
```

**Comment by mforets** [comment]
quick workaround: `plot(result.Xk)`.

**Comment by mforets** [comment]
the problem is that `vertices_list` of a polygon do *not* come sorted, as i erroneously assumed [here](https://github.com/JuliaReach/Reachability.jl/blob/master/src/plot_recipes.jl#L73).

i would propose that we add the (optional, default, true) application of `convex_hull` to `vertices_list` of an hpolygon.

**Comment by mforets** [comment]
side comment: it is interesting how strong it depens on epsilon. are you sure you need that much precision? on the eye, eps = 0.01 is already OK.

**Comment by schillic** [comment]
> the problem is that vertices_list of a polygon do not come sorted

When I look at the code, they look sorted.

> are you sure you need that much precision?

There are more experiments with smaller `δ`.

**Comment by mforets** [comment]
> When I look at the code, they look sorted.

check for example `v = vertices_list(result.Xk[j])` and `c = convex_hull(v)` for j = 1 or j=2; there are smaller number of vertices in the `convex_hull` case. i would expect at most 2, because the algorithm goes in counterclockwise order intersecting the constraints, and these are already sorted.

**Comment by schillic** [comment]
> the algorithm goes in counterclockwise order intersecting the constraints, and these are already sorted

Exactly, so how can it happen?

**Comment by mforets** [comment]
¯\_(ツ)_/¯

**Comment by schillic** [comment]
But maybe we have a bug in the constraint sorting?

**Comment by mforets** [comment]
`vertices_list` doesn't sort the constraints nor does the constructor of `HPolygon`; it could be a good optional feature. here the polygon is being being from the constraints of an iterative refinement. in the last update we did remove spare constraints (before there were much more redundant vertices!).

**Comment by schillic** [comment]
If the constraints of `HPolygon` are not sorted, we are in bigger trouble. I think iterative refinement inserts the constraints in a sorted way. I would like to understand what is wrong here.

**Comment by schillic** [comment]
Interestingly, I cannot reproduce the problem anymore. I reset both `LazySets` and `Reachability` to the old state, but it works.

**Comment by schillic** [comment]
The problem is that during iterative refinement we can get redundant constraints. They should be removed.
The set X0 looks like this:
![s1](https://user-images.githubusercontent.com/9656686/37433663-08ecb7f0-27dd-11e8-8856-e612c6616b8c.png)
The constraints polygon representation is this:
```julia
julia> s[1].constraints
6-element Array{LazySets.HalfSpace{Float64},1}:
 LazySets.HalfSpace{Float64}([1.0, 0.0], 0.0)           
 LazySets.HalfSpace{Float64}([0.0, 1.0], 0.0)           
 LazySets.HalfSpace{Float64}([-0.581061, 0.81386], 0.0) 
 LazySets.HalfSpace{Float64}([-1.0, 0.0], 0.105416)     
 LazySets.HalfSpace{Float64}([0.0, -1.0], 0.124737)     
 LazySets.HalfSpace{Float64}([0.796828, -0.604206], 0.0)
```
Clearly, the first two constraints (expressing that the set is in the lower left quadrant) are redundant. I have not checked if this can only happen for the initial box constraints or also for new constraints.

The `vertices_list` implementation just intersects the constraints one by one. Since there are redundant constraints, this can give redundant vertices.
```julia
julia> vertices_list(s[1])
6-element Array{Array{Float64,1},1}:
 [0.0, 0.0]             
 [-0.0, 0.0]            
 [-0.105416, -0.0752626]
 [-0.105416, -0.124737] 
 [-0.0945838, -0.124737]
 [0.0, -0.0]
```

**Comment by mforets** [comment]
OK, this explains the behavior. What is the set X0 input to `approximate`?

The idea [here](https://github.com/JuliaReach/LazySets.jl/pull/30) was to get rid of redundant constraints on-line, and in [unit_overapproximate.jl](https://github.com/JuliaReach/LazySets.jl/blob/master/test/unit_overapproximate.jl#L17) we have some tests, it would be interesting to see what happens with this input.

**Comment by mforets** [comment]
Ah, you gave the set X0 as a picture so we should be able to test an similar example.

**Comment by schillic** [comment]
The input model is at the very top, but as you said we should rather construct this set manually.

**Comment by schillic** [comment]
This is now resolved. We sort constraints (and remove redundant ones) by default in the `HPolygon` constructor.
