### ISSUE TITLE
should `genmat(::Hyperrectangle)` return a diagonal matrix?

### ISSUE THREAD

**Issue by lucaferranti** [JuliaReach/LazySets.jl#2997]
IIUC `Hyperrectangle` is the same of an `IntervalBox`, that is the sides are parallel to the axes, in that case I think the generator matrix will always be diagonal? should `genmat(Hyperrectangle)` return a diagonal matrix?

**Comment by schillic** [comment]
There is a problem if the `Hyperrectangle` has flat dimensions. See #1878. I close this as a duplicate.
