### ISSUE TITLE
Review SPZ `remove_redundant_generators`  (compact)

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#3029]
see `compact` operation in Niklas' thesis (prop 3.1.7) and compare it with our implementation. (if they match, update the docstring with a link if its not there already.)

**Comment by lucaferranti** [comment]
and also check when it needs to be called in the operations with SPZ: An alternative would be to always call it in the constructor

**Comment by mforets** [comment]
since it's not super cheap i'd rather do it on demand or on certain operations

**Comment by lucaferranti** [comment]
looking at proposition 3.1.7 of the thesis (page 36), it seems to me that `compat` does the following:

- adds generators whose corresponding column in E is zero to the center (that is sum constant terms)
- aggregates generators that have identical corresponding columns in E (that is sum monomials that can be summed)

this is a subset of `remove_redundant_generators`, which also removes zero columns from `G`

**Comment by lucaferranti** [comment]
since this is needed both for SPZ and SSPZ (the only difference is that for SPZ you also remove zero columns from the independent matrix), we might have a common helper function `compat!(c, G, E)` called by `remove_redundant_generator` for both types
