### ISSUE TITLE
`ERROR: AssertionError: package 'Polyhedra' not loaded (it is required for executing tohrep)` despite it being present

### ISSUE THREAD

**Issue by lassepe** [JuliaReach/LazySets.jl#3062]
I'm loading LazySets and Polyhedra (in that order) in some of my code to compute the `LazySets.constraints_list` of a `VPolytope`. This used to work but now it errors with:

```julia
ERROR: AssertionError: package 'Polyhedra' not loaded (it is required for executing `tohrep`)
Stacktrace:
  [1] require(mod::Module, package::Symbol; fun_name::String, explanation::String)
    @ ReachabilityBase.Require ~/.julia/packages/ReachabilityBase/VQJKD/src/Require/Require.jl:47
  [2] #require#1
    @ ~/.julia/packages/ReachabilityBase/VQJKD/src/Require/Require.jl:41 [inlined]
  [3] tohrep(P::LazySets.VPolytope{Float64, Vector{Float64}}; backend::Polyhedra.DefaultLibrary{Float64})
    @ LazySets ~/.julia/packages/LazySets/OP742/src/Sets/VPolytope.jl:487
  [4] tohrep
    @ ~/.julia/packages/LazySets/OP742/src/Sets/VPolytope.jl:481 [inlined]
```

**Comment by schillic** [comment]
I cannot reproduce:

```julia
julia> using LazySets

julia> import Polyhedra

julia> P = rand(VPolytope);

julia> constraints_list(P)
3-element Vector{HalfSpace{Float64, Vector{Float64}}}:
 HalfSpace{Float64, Vector{Float64}}([-0.008885939139337553, 1.0], 0.15474025010699877)
 HalfSpace{Float64, Vector{Float64}}([-0.995134172813695, -0.5475872735571988], 0.5302388851399702)
 HalfSpace{Float64, Vector{Float64}}([0.5121433979951575, -1.9406443827240492], 0.3953548707454585)
```

My guess is that you call the function from inside another module and the way I implemented the `require` stuff without the `@__MODULE__` apparently does not work when called from other modules. I created a branch `schillic/3062` to test this hypothesis. Do you mind trying out if that fixes the problem for you? You can do
```julia
julia> ]

pkg> add LazySets#schillic/3062
```
to use that branch, and when you are done, you do
```julia
julia> ]

pkg> free LazySets
```

**Comment by lassepe** [comment]
Yes, that's exactly the situation and indeed your branch fixes the problem. Thanks for the quick response :rocket: 

FWIW, here is a reproducer that triggered the issue:

```julia
using TrajectoryGamesBase: TrajectoryGamesBase

environment = TrajectoryGamesBase.PolygonEnvironment()
constraints = TrajectoryGamesBase.get_constraints(environment)
```

**Comment by schillic** [comment]
Great, thanks. I realized that modules are a problem in another package, but hoped that it would just affect submodules.
I will fix the problem then for all places here.

**Comment by schillic** [comment]
The latest release contains the fix.
