### ISSUE TITLE
Add method `eye` for `SparseMatrixExp`

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#308]
something like:

```
Base.eye(spmexp::SparseMatrixExp) = eye(spmexp.M)
```

**Comment by schillic** [comment]
Is this particular function of interest? I bet there are dozens of other functions that are useful...

**Comment by mforets** [comment]
i propose to make `eye(::SparseMatrixExp)` return another `SparseMatrixExp`. since `e^0 = 1`, we can let `Base.eye(spmexp::SparseMatrixExp) = SparseMatrixExp(zeros(spmexp.M))`.
