### ISSUE TITLE
Add point in nonconvex `Polygon` check

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#3126]
cc @mvanzulli

**Comment by David-davidlxl** [comment]
I wanted to see if there's any progress on this. I'm working with a nonconvex polygon and I'd really like to have the membership-check functionality.
For example, I'd like the following code to run without error:
```
using LazySets
polygon = Polygon([[0, 0],
    [2.1314, 0.9141],
    [1.8282, 1.2219],
    [0.9141, 0.9141],
    [0.6063, 1.5251],
    [-0.6063, 2.1360],
    ])
println([0, 1] ∈ polygon)
```

**Comment by schillic** [comment]
@David-davidlxl: I added an implementation in #3628. It will likely take some time until this gets reviewed and merged, so I suggest you check out the branch or copy the code.
Also, I tried to cover every edge case, but there might be one missing. So feel free to beta-test it :)

**Comment by David-davidlxl** [comment]
@schillic Thank you so much!
I copied your `∈(x::AbstractVector, P::Polygon)` function and tested it with my polygon, and it seems to work perfectly! #3628 
![image](https://github.com/user-attachments/assets/059ddbe8-e1fc-46c7-b795-010f25582318)
