### ISSUE TITLE
Add cache to ExponentialMap and related types

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#315]
In the `lazy_expm` mode of `Reachability.jl`, we compute parts of the matrix (some block rows) and then multiply the matrix with another lazy matrix (in fact the same as from the beginning). This is all repeated inside a loop.
Question: Can we cache the computed numbers (block rows) and use them later (matrix multiplication) instead of recomputing?

**Comment by mforets** [comment]
this is interesting. if you add a matrix field, say `val` with the computed values of `e^M` this will give faster access to `get_row(s)` and `get_column(s)`. 

```julia
struct SparseMatrixExp{N} <: AbstractMatrix{N}
    M::SparseMatrixCSC{N, Int}
    val::SparseMatrixCSC{N, Int}
end
```

in pseudocode:

```julia
function get_column(spmexp::SparseMatrixExp{N}, j::Int)::Vector{N} where {N}
    % check if the matrix spmexp.val has column j
    % if it does => return spmexp.val[:, j]
    % otherwise, compute:
    n = size(spmexp, 1)
    aux = zeros(N, n)
    aux[j] = one(N)
    return expmv(one(N), spmexp.M, aux)
end
```

**Comment by schillic** [comment]
Does it only make sense for columns? Maybe more fine-grained (e.g., blocks) would be more beneficial.

In the "otherwise" case it should not just return the value but also store it (otherwise we never store anything :wink:).

**Comment by mforets** [comment]
the rows, or blocks would be relevant too but we should think about an efficient way to store and retrieve them.

> In the "otherwise" case it should not just return the value but also store it (otherwise we never store anything 😉).

yes!

**Comment by schillic** [comment]
One way would be to have two cache matrices: One with the values (`val`) and one with Boolean entries (`cached`) determining whether the entry in `val` is valid (if there is a way to signal "invalid" entries in `val`, we can drop the second matrix).
Usage: Whenever the user queries some entry/entries, we check for each entry whether it is invalid. If it is invalid, we compute and store it. In the end we just return the respective entries in `val`.

**Comment by schillic** [comment]
I realized that `expmv` can only be called with vectors, thus making it not so important to store single entries.

**Comment by schillic** [comment]
I realized that in our application we never compute a value twice, so this idea does not help.
