### ISSUE TITLE
Depend on `MathOptInterface` directly instead of referencing the internal variable of `JuMP`

### ISSUE THREAD

**Issue by lassepe** [JuliaReach/LazySets.jl#3238]
Currently, `MathOptInterface` is loaded through the `JuMP` module scope:

https://github.com/JuliaReach/LazySets.jl/blob/b11803321cd10ce904198d8abcf19759f9257f1d/src/Initialization/init_JuMP.jl#L1

The latest release of `JuMP` has renamed `MathOptInterface` internally to MOI. Thus, `LazySets` now fails to load.

I suggested in https://github.com/jump-dev/JuMP.jl/issues/3233 to keep an alias around until a breaking release is tagged. Nonetheless, it would be good to make the changes here now to depend on `MathOptInterface` directly instead of "stealing" it from `JuMP`.

**Comment by schillic** [comment]
Yep, there is #3237 already. I am busy now but will take a look in a couple of days. Thanks for the suggestion.
