### ISSUE TITLE
Overapproximation with template directions

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#326]
Consider an overapproximation of an n-dim set using "template polyhedra" in `Fx <= c`, the template matrix `F` is given and one determines the coefficients of the vector `c` using support functions.

For instance, one can take the matrix `F` whose columns are the 2^n vertices of the n-dimensional hypercube. There are other useful examples, eg. boxes or octogons in higher dimensions, see below.

For example, let

```julia
using LazySets, Plots, Polyhedra, IterTools

A = [1 2; 0 4.]
X0 = BallInf(ones(2), .1)
S = A * X0
plot(S, 1e-2)
```

<img width="567" alt="screen shot 2018-05-14 at 12 54 32" src="https://user-images.githubusercontent.com/12424594/40008583-06be8ba2-5776-11e8-980d-b2730f359ff8.png">

```julia
rhomb(n) = IterTools.product([[1., -1.] for i = 1:n]...)

box(n) = IterTools.chain(Iterators.take(IterTools.iterate(x -> circshift(x, 1), eye(n)[:, 1]), n),
                         Iterators.take(IterTools.iterate(x -> circshift(x, 1), -eye(n)[:, 1]), n))

octagon(n) = IterTools.chain(rhomb(n), box(n))

function overapproximate(X::LazySet{N}; template=rhomb) where {N}
    n = LazySets.dim(X)
    halfspaces = Vector{LazySets.HalfSpace{N}}()
    for ti in template(n)
        d = collect(ti)
        push!(halfspaces, LazySets.HalfSpace(d, ρ(d, X)))
    end
    return HPolytope{N}(halfspaces)
end

P = overapproximate(S, template=rhomb);
plot!(VPolygon(vertices_list(P)), alpha=0.1)
```

<img width="558" alt="screen shot 2018-05-14 at 12 58 20" src="https://user-images.githubusercontent.com/12424594/40008776-93e5c93c-5776-11e8-9261-71df08a31109.png">

**Comment by nikos-kekatos** [comment]
Btw, everyone is using T and d for template polyhedra nowadays. It might worth considering it :).

Currently, SpaceEx supports fixed directions that are predefined by the users. In the web interface, there are three options: (i) boxes, (ii) octagons, and (iii) arbitrary uniform distributed constraints (e.g. 16, 50, 100). If you use the source code/executable, you can explicitly select the directions you want in the .cfg file. Note that they should set as equalities constraints, separated by & symbols.

There is ongoing work towards dynamic template directions. We have been working on time-varying directions. As I will probably never finish this work before I graduate :), let me refer you to work in the spirit of CEGAR, e.g. [interpolants](https://repository.ist.ac.at/1010/1/space-time_interpolants.pdf).

**Comment by nikos-kekatos** [comment]
Indeed, it is not clear how you can avoid having negative directions, even if you have template polyhedra (or any form of (convex) halfspace representation). For parallelotopes, the same problem should hold, e.g. [Lemma 6](https://mediatum.ub.tum.de/doc/1287515/893367.pdf).

Redundancy checking should be straightforward for [polyhedra](http://people.ee.ethz.ch/~mpt/2/downloads/MPTmanual.ps). However, would it make any real difference if you have a predefined number of directions? Since you are doing reachability analysis and in the next step (considering your example) you will have again octagonal directions.  I guess it should reduce the computation but you add an extra check. That said, if you have a very high number of directions, which is not typically the case, it would probably worth it.

On a separate note, it might worth considering normalizing the directions; similar to what SpaceEx is doing.

**Comment by mforets** [comment]
@schillic  sorry for the confusion, i forgot to fix the definition of `rhom(n)` here. i also get the crash etc. the correct definition is:

```
rhomb(n) = IterTools.product([[1., -1.] for i = 1:n]...)
```

**Comment by schillic** [comment]
> i also get the crash, etc.

Then how could you draw? :confused:

**Comment by schillic** [comment]
> `julia> rhomb(n) = IterTools.product([[1., -1.] for i = 1:n]...)`

This is the `Ball1` approximation, right? Then we should implement this for
`overapproximate(S, ::Type{Ball1})`.

**Comment by mforets** [comment]
> This is the Ball1 approximation, right? Then we should implement this for
overapproximate(S, ::Type{Ball1}).

Yes!

> Then how could you draw? 

I had updated the draw but didn't fix the function def..

For the octagonal directions in n-dim, i think it is:

```julia
julia> octagon(n) = IterTools.chain(IterTools.product([[1., -1.] for i = 1:n]...),
                             Iterators.take(IterTools.iterate(x -> circshift(x, 1), eye(n)[:, 1]), n),
                             Iterators.take(IterTools.iterate(x -> circshift(x, 1), -eye(n)[:, 1]), n))

julia> octagon(2)
8-element Array{Any,1}:
 (1.0, 1.0)  
 (-1.0, 1.0) 
 (1.0, -1.0) 
 (-1.0, -1.0)
 [1.0, 0.0]  
 [0.0, 1.0]  
 [-1.0, -0.0]
 [-0.0, -1.0]

julia> octagon(3)
14-element Array{Any,1}:
 (1.0, 1.0, 1.0)   
 (-1.0, 1.0, 1.0)  
 (1.0, -1.0, 1.0)  
 (-1.0, -1.0, 1.0) 
 (1.0, 1.0, -1.0)  
 (-1.0, 1.0, -1.0) 
 (1.0, -1.0, -1.0) 
 (-1.0, -1.0, -1.0)
 [1.0, 0.0, 0.0]   
 [0.0, 1.0, 0.0]   
 [0.0, 0.0, 1.0]   
 [-1.0, -0.0, -0.0]
 [-0.0, -1.0, -0.0]
 [-0.0, -0.0, -1.0]
```

Draw:

<img width="498" alt="screen shot 2018-05-15 at 09 00 05" src="https://user-images.githubusercontent.com/12424594/40055513-8595cf00-581e-11e8-8a0b-effcd3b35b5e.png">

**Comment by schillic** [comment]
> > This is the Ball1 approximation, right? Then we should implement this for
    overapproximate(S, ::Type{Ball1}).
> >
> Yes!

Sorry, I was wrong, your rhomb does not have to be symmetric in the ball sense.

**Comment by mforets** [comment]
> I had updated the draw but didn't fix the function def..

To be clear when i use the wrong def, the plot i get is sort of a triangle. It is broken (it is not an overapproximation). Maybe because one of the directions taken is the null (0,0) direction..

<img width="493" alt="screen shot 2018-05-15 at 09 00 01" src="https://user-images.githubusercontent.com/12424594/40055584-d76c589e-581e-11e8-800d-3a8f8fed371a.png">

**Comment by mforets** [comment]
> Sorry, I was wrong, your rhomb does not have to be symmetric in the ball sense.

Ok. We can also add "box directions" analogue to the infinity norm (but again does not have to be symmetric), like

```julia
julia> box(n) = IterTools.chain(Iterators.take(IterTools.iterate(x -> circshift(x, 1), eye(n)[:, 1]), n),
                                                   Iterators.take(IterTools.iterate(x -> circshift(x, 1), -eye(n)[:, 1]), n))
```

**Comment by mforets** [comment]
How would `overapproximate(X::LazySet{N}; template=rhomb) where {N}` work in harmony with the existing `overapproximate(S::LazySet, ɛ::Real)` functions? Do we keep the signature i proposed or there is a better alternative?

**Comment by schillic** [comment]
`rhomb isa Real` does not hold, so it should always try your version in this case. But for future extensions I would still add a type like `Vector{Vector{<:Real}}`.

Maybe we should create a helper type `AbstractTemplateDirections` which contains some instances `OctagonDirections` etc. and then internally we translate this to the intended array of directions.
