### ISSUE TITLE
Revisit Line

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#332]
1. `Line` cannot be used out of the box, although it is exported.
```julia
julia> using LazySets

julia> Line
ERROR: UndefVarError: Line not defined

help?> Line
search: Line lines LinearMap linetype LinesHull linespace linear_map LineSegment LineNumberNode

Couldn't find Line
Perhaps you meant Line, lines, [...] # Yes, I meant Line!
```
2. Furthermore, `Line` needs a `Vector`. We should either allow `AbstractVector` or add a constructor from an `AbstractVector`.

**Comment by mforets** [comment]
1) In a fresh session it can be used. There is a name when you load `Polyhedra` but i think this is normal:

```julia
julia> using LazySets

julia> Line
LazySets.Line

julia> using Polyhedra
WARNING: using Polyhedra.Line in module Main conflicts with an existing identifier.
```

**Comment by mforets** [comment]
2. agreed.

**Comment by schillic** [comment]
I swear I tried a fresh session, but now it works... Heisenbug :stuck_out_tongue_winking_eye:
