### ISSUE TITLE
Plot recipe for HPolytope/VPolytope in 2D 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#335]
Proposal: given a `P::HPolytope` make `plot(P)` work and plot exactly by converting it to a `HPolygon`.

This applies to `VPolytope`.

**Comment by mforets** [comment]
This functionality is already supported with 

```julia
@recipe function plot_polytope(P::AbstractPolytope;
                               color="blue", label="", grid=true, alpha=0.5)
```

The caveat is that it require one to load `Polyhedra`, since it calls `vertices_list`. I think we can either keep it as is, or preprocess the `P` with a call to `convert(HPolygon, P))`. But this will be weird/unnecessary if eg. say the `vertices_list(V)` is easy to get. For instance, if you are going to plot a `VPolytope` you don't want to call `convert(HPolygon, P))`

**Comment by schillic** [comment]
This 2D issue is really unnerving. I would like to get this working, best with a general solution.

We could pull the `vertices_list` methods out of the `@require` blocks and add a switch like this (example for `HPolytope`, but the same idea applies for `VPolytope`):
```julia
if dim == 2
    return vertices_list(convert(HPolygon, P))
elseif !polyhedraloaded
    error("you need to load the package Polyhedra for working with HPolytopes")
end
# old code
```
(`polyhedraloaded` is the condition that `Polyhedra` is loaded.)

**Comment by schillic** [comment]
This works now.
