### ISSUE TITLE
Implement length in template directions with BigInt's

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#338]
In #330 we added templated directions. Since the number of directions is exponential in the dimension, the `length` method can easily overflow, although in principle, there is no such problem since `AbstractDirections` subtypes implement iterators. 

Does using `n::BigInt` in the definition of `UnitVector` provide a quick fix?

**Comment by schillic** [comment]
I would say that we should not change this. If there are more directions than (positive) `Int64`s, you have other problems anyway.
