### ISSUE TITLE
Revise octagon template directions

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#343]
In #326 we introduced what we thought were octagon template directions. However, they grow exponentially with the dimension.
[SpaceEx has a different interpretation.](http://spaceex.imag.fr/sites/default/files/introduction_to_spaceex_0.pdf) It seems to be "all permutations of (1,1,0,...,0), (1,-1,0,...,0), (-1,1,0,...,0), (-1,-1,0,...,0)" (i.e., always exactly two variables in the vector are +-1, all other entries are 0).
In fact, octagon constraints should subsume box constraints, so it should probably be "at most two variables" instead of "exactly two variables" above.

**Comment by mforets** [comment]
i would keep the existent `OctDirections`, maybe changing its name. the interpretation given in SpaceEx grows only quadratically 👍

**Comment by schillic** [comment]
@mforets found this SpaceEx code:
```C++
/** Return the normal vectors of a bounding box.
 *
 * The vectors are normed with the infinity norm. */
template<class T> void add_octagonal_directions(unsigned int dim, std::list<
        math::vector<T> >& directions) {
    /**
     * Chooses directions so as to compute the octagon of the set.
     * An octagon has two nonzero coefficients, which leads to
     * directions of the form:
     * x_i \in {-1,+1}
     * x_j \in {-1,+1}
     * for i,j in 0,...,dim.
     * Note that bounding box directions are contained as the
     * case i=j.
     */
    math::vector<T> l = math::vector<T>(dim, T(0));
    for (unsigned int i = 0; i < dim; i++) {
        for (unsigned int j = i; j < dim; j++) {
            l[i] = T(1);
            l[j] = T(1);
            directions.push_back(l); // 1 1
            l[i] = T(-1);
            directions.push_back(l); // -1 1
            if (i != j) { // otherwise, these are redundant
                l[j] = T(-1);
                directions.push_back(l); // -1 -1
                l[i] = T(1);
                directions.push_back(l); // 1 -1
            }
            l[j] = T(0);
        }
        l[i] = T(0);
    }
}
;
```
