### ISSUE TITLE
Recipes for 3D Plots

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#35]
For arbitrary 3D lazy sets, we lack an `overapproximate` in that dim that can be used for visualization. That would need a generalization of the Lotov-like algorithm, but in 3D.

In the meantime, we could:

- plot the result from ball-inf approximations (`eps = Inf` case)
- plot the cartesian decomposition of the given set, as valid (2+1 dim) overapproximation

*Note:* for the `Singleton` type this already works, e.g.

```julia
julia> using IterTools
julia> plot([Singleton(collect(vi)) for vi in IterTools.product([[1, -1] for i = 1:3]...)])
```  

<img width="422" alt="screen shot 2017-11-13 at 14 06 11" src="https://user-images.githubusercontent.com/12424594/32727194-edc5b758-c87b-11e7-9c6b-03790330dd09.png">

--

## Edit 

useful links:

- https://discourse.julialang.org/t/pyplot-3d-plotting/30838
- https://www.geeksforgeeks.org/how-to-draw-3d-cube-using-matplotlib-in-python/
- https://stackoverflow.com/questions/65482345/plotting-a-3d-surface-in-julia-using-either-plots-or-pyplot
- https://discourse.julialang.org/t/plotting-a-3d-surface/17143/16
- https://matplotlib.org/2.0.2/mpl_toolkits/mplot3d/api.html
- https://github.com/JuliaPy/PyPlot.jl#3d-plotting

**Comment by schillic** [comment]
A scatter plot is easy for polytopes:
```julia
julia> using LazySets, Plots

julia> H = Hyperrectangle(zeros(3), ones(3));

julia> v = vertices_list(H);

julia> plot([e[1] for e in v], [e[2] for e in v], [e[3] for e in v], seriestype=:scatter)
```
![plot3d](https://user-images.githubusercontent.com/9656686/52788179-72a63680-3060-11e9-8e42-f025674dedd3.png)

**Comment by mforets** [comment]
👍  I don't know if there is a command to plot the convex hull of the points, but it certainly can be done with [Makie](http://juliaplots.org/MakieGallery.jl/stable/).

**Comment by schillic** [comment]
With the change in #3260 we can add a recipe like this:

```julia
using LazySets, Plots
import MiniQhull

B = BallInf(zeros(3), 1.0)

V, C = LazySets.delaunay_vlist_connectivity(B; compute_triangles_3d=true)
C = Matrix{Int}(C .- 1)  # -1 for zero indexing; convert to Int64 on 64-bit systems

x = [v[1] for v in V]
y = [v[2] for v in V]
z = [v[3] for v in V]

i = [C[1, j] for j in 1:size(C, 2)]
j = [C[2, j] for j in 1:size(C, 2)]
k = [C[3, j] for j in 1:size(C, 2)]

plot(x, y, z, seriestype=:mesh3d; connections=(i, j, k))
```

![3d](https://user-images.githubusercontent.com/9656686/229616389-7baa1826-7b8e-4008-bf94-da47f3e6a1db.png)
