### ISSUE TITLE
Light Minkowski sum array

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#350]
#349 adds caching for the M-sum array, quoting from @schillic's comment:

> Possible future work: Currently the sum stores all sets, which takes a lot of memory. In applications where we always query the same support vector(s) and then add a new set in a loop, we could also provide a variant that only stores the newest sets.

**Comment by schillic** [comment]
We need this to analyze the FOM model. The lazy sets become too big otherwise.
