### ISSUE TITLE
Caching lazy set operations

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#351]
(outsourced from a comment by @mforets in [#342](https://github.com/JuliaReach/LazySets.jl/issues/342#issuecomment-391092388))
Generalize the approach of `CacheMinkowskiSum` to other set representations. As a design strategy, in a future revision we could use composition like:

```julia
struct CachedLazySet{N, ST<:LazySet{N}, CT} <: LazySet
    X::ST
    cache::CT
end
```
This could possibly be outsourced to a macro.

**Comment by mforets** [comment]
For the macro approach, we should check [Mixers](https://github.com/rafaqz/Mixers.jl), this package is providing such technology for type extensions.

**Comment by schillic** [comment]
> The cached MinkowskiSumArray turned out to give very good results in practice. I think this feature is worth adding, since it can be interesting for other applications.

Note that it was only so efficient because we could remove the sets again and thus skip repeated computations. This is because of the linearity of the support vector for the sum. Without this property I do not expect good performance.

**Comment by schillic** [comment]
I close this issue because I think it is unclear what to do.
