### ISSUE TITLE
Add BenchmarkGroup

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#356]
Use [PkgBenchmark](https://juliaci.github.io/PkgBenchmark.jl/latest/) that allows to define a benchmark suite, compare execution time between branches and commits, etc.

We can build the benchmarks incrementally, starting from simple things such as support function evaluation for different set types.

**Comment by schillic** [comment]
Can this be closed?

**Comment by mforets** [comment]
Yes! When i have some time i'll make a script that runs the benchmarks and prints them on the webpage (https://github.com/JuliaReach/JuliaReach-website), but have to think how to automate this somehow..
