### ISSUE TITLE
Automatically check for existence of required subtype specific methods

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#36]
We have a lot of subtypes, e.g., of `LazySet`.
We want all of them to provide a method for the function `σ`.
Hence we should check that those methods exist to prevent new types that may break things.

We can get all subtypes with the help of `subtypes(LazySet)` and use the `method_exists` function to check for existence:
```julia
for S in subtypes(LazySet)
    println(method_exists(σ, (Vector{Float64}, S)))
end
```

I propose that we add such tests for all abstract types, also in `Reachability`.

We could even create a function that automates this process if we have several common methods:
Add in `LazySets.jl`:
```julia
function require()::Vector{Function}
    return [
        S -> (σ, (Vector{Float64}, S)),
        S -> (my_func1, (S)),
        S -> (my_func2, (S, Real, Int))
    ]
end
```
Then in the unit tests we just have to go through this vector and apply the test to each of them.
We probably need a mechanism to allow several `require` methods for different abstract types, e.g., by changing the name.

(I have not tested the second one, the first one works.)

**Comment by schillic** [comment]
We want to have this, but do not need the `require` function.
Just add those functions that you want into a unit test.

Currently `VPolygon` does not work, so we wait a bit here.

**Comment by mforets** [comment]
> Currently VPolygon does not work, so we wait a bit here.

it does now.
