### ISSUE TITLE
Compare performance for copy(transpose(A))

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#360]
In [this commit](https://github.com/JuliaReach/LazySets.jl/pull/353/commits/f720856d09e7638eed4895f318d39ab699af4013#diff-1cfe0f3f5f3bd5ca6886b29c164d9266) we replaced `A.'` by `copy(transpose(A))` in `ExponentialMap.jl`.
We should check whether the `copy` is necessary (which is only the case if the transposed matrix is modified at all). If not, we should remove it.
Otherwise, we should check whether the `copy` has an effect on performance.
If so, we should outsource this `copy(transpose(A))` to a new function `transp` and use that instead.

**Comment by schillic** [comment]
For the second task, the answer is "yes".
```julia
julia> M = [1.0 2; 3 4];

julia> @time Mt = transpose(M);
  0.000006 seconds (5 allocations: 272 bytes)

julia> @time Mt = copy(transpose(M));
  0.000011 seconds (6 allocations: 384 bytes)
```

**Comment by mforets** [comment]
> We should check whether the copy is necessary 

i woud say that it is *not* necessary, because it is passed as an argument to `expmv(one_N, Mtranspose, aux)`, and `expmv` does not modify its arguments (actually internally it does a copy of its matrix argument and call a `expmv!`).

> If not, we should remove it.

agreed.

>  Otherwise, we should check whether the copy has an effect on performance.

in my machine: in v0.6.1,

```julia
julia> @btime Mt = transpose($M);
  41.582 ns (1 allocation: 112 bytes)

julia> @btime Mt = copy(transpose($M));
  72.386 ns (2 allocations: 224 bytes)
```

in v0.7.0-DEV.4524,

```julia
julia> @btime Mt = transpose($M);
  7.388 ns (1 allocation: 16 bytes)

julia> @btime Mt = copy(transpose($M));
  47.494 ns (1 allocation: 112 bytes)
```
