### ISSUE TITLE
Add concrete linear map operations for abstract hyperrectangles

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#371]
Each of these can have its own `linear_map(M, X)` implementation:

```julia
julia> subtypes(AbstractHyperrectangle)
4-element Array{Union{DataType, UnionAll},1}:
 LazySets.AbstractSingleton
 LazySets.BallInf
 LazySets.Hyperrectangle
 LazySets.SymmetricIntervalHull
```

**Comment by schillic** [comment]
We should have an implementation for `AbstractHyperrectangle` instead of `Hyperrectangle` because it then automatically works for the others as well.

**Comment by mforets** [comment]
I thought about this but then we need to add new constructors from another set (VPolytope)? Since
`M * vertices_list(X)` would work, but then we need to instantiate a new set of type `typeof(X)`

**Comment by schillic** [comment]
I do not understand. Can we not just use the implementation for `Hyperrectangle` that you had in mind? This is the most general way to do it, right?

**Comment by mforets** [comment]
Okay, i see. We can define a generic fallback method in the abstract interface that instantiates a `VPolygon` or a `VPolytope` depending on the dimension.
