### ISSUE TITLE
Add dimension as type parameter

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#372]
(definitely not a crucial feature)
Sometimes it would be good to have specialized implementations for, e.g., 1D or 2D sets. Then it would be useful to have this information available as a type parameter so we can write specialized methods.

**Comment by mforets** [comment]
I don't think it is a good idea to have the dimension as a type parameter. Polyhedra used to have it but removed it. See the discussion here: https://github.com/JuliaPolyhedra/Polyhedra.jl/issues/111
