### ISSUE TITLE
Concrete linear map for high dim axis-aligned boxes

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#383]
The current fallback (`AbstractPolytope`)  implementation  (see #373) performs the transformation of the `vertices_list`, and returns a `VPolytope`. 

Proposal: explore if we can do better in the particular case of axis-aligned boxes (esp in high dimensions, since the num vertices grows exponentially), by rotating the constraints and returning a `HPolytope` instead.

**Comment by schillic** [comment]
We should probably have an optional argument to control whether the inverse condition is checked.

**Comment by mforets** [comment]
Since [release v1.6.0](https://github.com/JuliaReach/LazySets.jl/releases/tag/v1.6.0) the concrete linear map decides which method to dispatch (constraints or vertices), given a polyhedron in H-representation, depending on the invertibility of the coefficients matrix.

Example: 

```julia
julia> H100 = rand(Hyperrectangle, dim=100);  # 2^100 vertices

julia> @time linear_map(rand(100, 100), H100);
  0.006962 seconds (1.83 k allocations: 736.344 KiB)

julia> typeof(ans)
HPolytope{Float64}
```

> We should probably have an optional argument to control whether the inverse condition is checked.


The optional argument is now called `check_invertibility`.
