### ISSUE TITLE
`vertices` and `vertices_list`

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#385]
I see some sort of asymmetry between `VPolygon`'s `vertices_list` field and `VPolytope`  `vertices` field, compared to `HPolygon` and `HPolytope` fields's `constraints`.  Note that we have methods `constraints_list` and `vertices_list`.

Proposal: change `VPolygon`'s field to `vertices`.

**Comment by schillic** [comment]
Good finding, I totally agree :+1:
