### ISSUE TITLE
Add cache to Intersection

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#397]
In #396 we implement the concrete intersection of two hyperrectangles. The issue with the lazy operation (`Intersection{N, <:AbstractHyperrectangle, <:AbstractHyperrectangle}`) is this: It needs to know whether the intersection is empty in advance. In the worst case this requires to compute the whole intersection, which to some extent breaks the point of the lazy operation.
Given that we have to compute this information with the first support vector query (or other queries like `isempty`), we should cache this result and only compute it once.
I guess that this observation is general for the intersection (in particular also for #375 and #262), so we should have a general caching mechanism for the lazy `Intersection` type. I cannot quite foresee how this cache would look like. For the moment it would suffice to have a new field `isempty::Tribool`. A `Tribool` would be a (mutable) type that can be `true`, `false`, or `unknown`. The field `isempty` would be initialized to `unknown` and later be set to `true` or `false` accordingly. (Note that `Intersection` would still be immutable.)
Later we may require more specific information for intersections, depending on the set types. Then we could replace the `isempty` field by a general caching field `cache::C` where `C` is a new type parameter of type `IntersectionCache`. The latter would be a new abstract type that we can instantiate for each respective combination of set types. In the instantiation we would store the respective information.

So the question is: Do we want to have the `isempty` field for now, or directly go for the general `IntersectionCache` type?

**Comment by mforets** [comment]
I like the idea of the `isempty` field (*). Besides or complementing this idea, what do you think if we ask that the lazy type at creation (it can be optional and true by default), it runs `is_intersection_empty` and in the case it is empty, it returns the `EmptySet`.

(*) not sure about this fields name, because this name is already taken..

**Comment by schillic** [comment]
> (*) not sure about this fields name, because this name is already taken..

For a function only, right? The idea would be that we only use this field internally. And to me it describes perfectly what it should do.

> what do you think if we ask that the lazy type at creation (it can be optional and true by default), it runs `is_intersection_empty` and in the case it is empty, it returns the EmptySet.

If it is optional, it is okay. But I hesitate to make it the default behavior because the `is_intersection_empty` check can be as expensive as the lazy version, which spoils everything. If you do not run this check, you at least save the computations if you never ask for a support vector - the only benefit I see with the `Intersection` wrapper.
