### ISSUE TITLE
Implement binary search for VPolygon support vector

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#40]
In #13 we implemented a O(n) algorithm to compute the support vector of a VPolygon. Since the vertices are sorted in CCW fashion by construction, we can do better than that using a binary search, see references below.

---

- [extreme points in convex polygons](http://geomalgorithms.com/a14-_extreme_pts.html#polyMax_2D()) in the geomalgorithms site
- Joseph O'Rourke, Computational Geometry in C (2nd Edition), Sect 7.9 "Extreme Point of  Convex Polygon" (1998).

**Comment by schillic** [comment]
Since the vertices are sorted, it should be sufficient to compare a vertex to its neighbors to detect that a maximizing vertex has been found. This optimization scheme is convex, i.e., local minima are global minima (however, there can be plateaus).
