### ISSUE TITLE
Documenter error with `convert`

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#400]
We need to add concrete types to `convert` in `conversion.md`. Otherwise `Documenter` tries to document *all* methods with the name `convert`.
As a side note, currently there is an error with one of them (which is why I found this issue).

**Comment by mforets** [comment]
good finding. if we did things correctly, all those methods live in `convert.jl`

**Comment by schillic** [comment]
Yes. Unfortunately, the error I saw first (building the docs locally crashes) seems completely unrelated. This is now #402.
