### ISSUE TITLE
Change intersection of two lines to set operation

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#405]
We have this concrete intersection function: [`intersection(L1::Line{N}, L2::Line{N})::Vector{N}`](https://github.com/JuliaReach/LazySets.jl/blob/master/src/concrete_intersection.jl#L34).
The return value (a vector) is inconsistent with intersection operations for other set types.
Proposal: Return a `Singleton` (resp. an `EmptySet`).

**Comment by mforets** [comment]
👍
