### ISSUE TITLE
Conversion from Zonotope to HPolytope

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#416]
See [this paper](http://www.i6.in.tum.de/Main/Publications/Althoff2009b.pdf) for an algorithm to convert (parallelotopes or) zonotopes to polytopes.

**Comment by mforets** [comment]
A default conversion from `Zonotope` to `HPolytope` is available since #631.

I don't propose to close this one since the conversion proposed here (Theorem 7) is more efficient.
