### ISSUE TITLE
Forbid degenerate cases

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#422]
Should we forbid degenerate cases of sets (see examples below) by checking the inputs in the constructor (with an `@assert`)? To me it  does not make sense to create such sets in the first place. The benefit is that we save some code to cover these nasty cases, and we probably do not handle these cases consistently everywhere anyway.

Proposed changes (for a start - there might be more cases):
1. `Line`s/`Hyperplane`s/`HalfSpace`s with normal vector 0
2. `LineSegment` with end points `p` and `q` such that `p == q`
3. `VPolygon`/`VPolytope` with no vertex

Exceptions (for now - I do not like them):
1. `HPolygon`/`HPolygonOpt`/`HPolytope` with no half-space (because we want to allow the creation via `addconstraint!`)
2. `Hyperrectangle`/`Interval`/`Ball`s/`Ellipsoid` with radius 0 (for `box_approximation`/`overapproximate` to have a consistent output type and to be even defined for a `Singleton`)

**Comment by mforets** [comment]
good idea; i haven't thought out but there are probably some other cases. although in general im not a fan of adding overheads such as calling a  `norm`  function for each time we make a `HalfSpace` of a polytope, at least, if we had a "super-safe" and a normal one.  

although `LineSegment`  with the same end points is a  "corner case", i don't think there is something essentially (or mathematically) wrong with it.  

i would move 3. to exception as well (although `VPolygon()` it is not currently implemented, but i think it should), for the same reason as it is useful sometimes to do `HPolygon()`

**Comment by schillic** [comment]
Hm, so you want to drop 1., 2., and 3.?

> im not a fan of adding overheads

The alternatives I see are:
1. Have these checks with every function call. For instance, when asking for the support vector of a "polygon" with no constraint (my interpretation would be that this set is the (non-compact) universal set) or no vertex (my interpretation would be that this set is the empty set), we check for these cases and throw an exception. This can actually be more expensive if you create a set once and call functions several times.
(Side note: The `VPolygon`'s `tohrep` function translates the "no vertex" case to the "no constraint" case. Does this make sense or should it rather throw the exception?)
Also recall that we can deactivate the `@assert` checks.
2. Have a good documentation that says "these are our implicit assumptions, and when using a function when not satisfying the assumptions, the output is undefined".

Currently we have a mix and sometimes assumptions are checked and sometimes not, which I find confusing at best.

> i don't think there is something essentially (or mathematically) wrong with it.

The idea was that there is nothing wrong with these cases, but some functions need extra code to handle them, and other functions silently assume that these cases do not exist.

**Comment by schillic** [comment]
I close this because this has to be decided on a case-by-case basis.
