### ISSUE TITLE
Move "Documentation guidelines" to its own repo

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#426]
Proposal: move the [wiki](https://github.com/JuliaReach/LazySets.jl/wiki/Documentation-Guidelines) of documentation guidelines to its own repository in the JuliaReach organization. Because these guidelines are used for other projects too and with an issue tracker we can discuss/track  changes, etc.

Should we call the repository `Guidelines`, or `DocsGudelines` (i slightly prefer the former because we also include guidelines or links to examples for coding style used in JuliaReach).

**Comment by schillic** [comment]
Yeah, we had this idea in #105, but then it died.

**Comment by schillic** [comment]
See also [Github's CONTRIBUTING info](https://github.com/JuliaReach/LazySets.jl/community).

**Comment by mforets** [comment]
🎉  See [JuliaReachDevDocs](https://github.com/JuliaReach/JuliaReachDevDocs) 🎉
