### ISSUE TITLE
Parametric numeric type of a LazySet 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#44]
In some cases we'd like to have `eltype(X)` where `X` is a `LazySet`, to return the underlying numeric type. Eg. `eltype(BallInf(ones(2), 0.1))` would be `Float64`.

In principle  this would just require

```
abstract type LazySet{N<:Number} end
```

But we should see if this makes sense for all LazySets, both set representations and operations.

**Comment by schillic** [comment]
Maybe better `numtype`.

**Comment by schillic** [comment]
Related: We should get rid of the `Int64` types at some places, e.g., in `HPolygonOpt`.
AFAIK this restricts the usage to 64-bit machines.

**Comment by schillic** [comment]
I tried to add type parameters to an abstract type today and it did not work.
Maybe I did a mistake; otherwise it just does not work in Julia.
We can still have this function for every subtype that does the trick, though.

**Comment by schillic** [comment]
There are TODOs for this for the box directions (`DIR_EAST` etc.).
