### ISSUE TITLE
Documenter v0.19 crashes when building the docs

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#440]
This issue was started in https://github.com/JuliaReach/LazySets.jl/issues/402 and a workaround fix is given in https://github.com/JuliaReach/LazySets.jl/pull/439.

However, this issue remains for version v0.19.

**Comment by schillic** [comment]
To be clear, it is not a bug on our side.

**Comment by schillic** [comment]
Interestingly, the problem does not exist in Julia v0.7.
