### ISSUE TITLE
Revise type parameters of LinearMap

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#451]
```julia
struct LinearMap{NM, N} <: LazySet{N}
```
Proposal:
```julia
struct LinearMap{N, NM} <: LazySet{N}
```
Reason: All other set types have the numeric type as their first argument. With this change we can do this:
```julia
function foo(X::LazySet{N}) where {N<:AbstractFloat}
    ...
    zero(N)
    ...
end
```
(We might actually do this already.)

**Comment by schillic** [comment]
While we are at it, should we add another type parameter for the set type, as we do for the other lazy operations?

**Comment by mforets** [comment]
yes, i agree. while we are at it, we can also add the parametric type of the linear map.

**Comment by schillic** [comment]
We could also change the second type argument from the matrix numeric type `NM` (which should usually be identical to `N` anyway) to the actual matrix type:
`struct LinearMap{N<:Real, MAT<:AbstractMatrix{N}, S<:LazySet{N}} <: LazySet{N}`

**Comment by mforets** [comment]
i think we should keep `MN`  possibly different to `N`. for example if you have an interval matrix the coefficients are intervals.

**Comment by schillic** [comment]
Good point. Then, would it be
`struct LinearMap{N<:Real, MAT<:AbstractMatrix{MN}, S<:LazySet{N}} <: LazySet{N}`
or drop just
`struct LinearMap{N<:Real, AbstractMatrix{MN}, S<:LazySet{N}} <: LazySet{N}`
as before?
Motivation: Julia can create more efficient code if it sees the matrix type in advance, but I am not completely sure if it cannot see it in the other case as well.

**Comment by mforets** [comment]
i would typically write out the full one:

```julia
julia> abstract type LazySet{N} end

julia> struct LinearMap{N<:Real, MN, MAT<:AbstractMatrix{MN}, S<:LazySet{N}} <: LazySet{N}
       end

julia> struct LinearMap2{N<:Real, MAT<:AbstractMatrix{MN}, S<:LazySet{N}} <: LazySet{N}
       end
ERROR: UndefVarError: MN not defined
```
