### ISSUE TITLE
Remove duplicate exports

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#452]
For instance, we have `export an_element` in `LazySet.jl`. This is sufficient.
However, it can also be helpful if we always write all exported functions at the top of each file in order to see what is public API and what are private functions. In that case we should be consistent and export *all* newly defined functions in each file.

If we go for removing the `export`s, should we also remove `export`s of methods that are defined in different concrete types, like `halfspace_left`? Here it would not be clear where to keep it and where to remove it.

Yet another idea is to collect all `export`s in one file, e.g., `LazySets.jl` in order to see all `export`s in one place.

**Comment by mforets** [comment]
> However, it can also be helpful if we always write all exported functions at the top of each file in order to see what is public API and what are private functions. In that case we should be consistent and export all newly defined functions in each file.

Yes, IMO in `LazySets` this approach looks sufficiently compact and understandable. The most common method that we omit is `export σ`, because all `LazySets` should implement it anyway, but it doesn't hurt to add it..

**Comment by mforets** [comment]
in other words, i think that some cases already under`LazySet.jl` can stay there, such as `export σ`, and so on, maybe `an_element` as well, since they are generic for all sets.

**Comment by schillic** [comment]
> in other words, i think that some cases already underLazySet.jl can stay there, such as export σ, and so on, maybe an_element as well, since they are generic for all sets.

Okay, so omit those defined in `LazySet.jl`. Does the same apply for other interfaces?

> Yet another idea is to collect all exports in one file, e.g., LazySets.jl in order to see all exports in one place.

And what about this one, in addition? I think this can be helpful.

**Comment by schillic** [comment]
See also the duplicate #874.
