### ISSUE TITLE
⊆ vs. is_subset

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#456]
Long ago we replaced `⊆` by `is_subset`. I do not recall the reason. I would go back to `⊆` if there is no argument against it. Note that `⊆` has an alias `issubset` already.

On a separate note, we currently have one function `⊆(x::Interval, y::Interval)` (which also does not occur in the docs list). We should be consistent and
* move it to `is_subset.jl`,
* add it to the docs list, and
* use the same function name as above.

**Comment by mforets** [comment]
Agreed. (we have ATM

```julia
@inline function issubset(S1::LazySet{N}, S2::LazySet{N}, witness::Bool=false
                         )::Union{Bool, Tuple{Bool, Vector{N}}} where {N<:Real}
    return is_subset(S1, S2, witness)
end
```
)

**Comment by mforets** [comment]
this is a side comment: we do in that file 

```julia
is_subset(P::AbstractPolytope{N}, S::LazySet{N}, witness::Bool=false
                  )::Union{Bool, Tuple{Bool, Vector{N}}} where {N<:Real}
```

an alternative (julian?) way is to dispatch on the value of the witness. and it seems here that it  would simplify these codes a bit.

**Comment by schillic** [comment]
:+1:, but I would create a new issue for that.
