### ISSUE TITLE
Convert AbstractHyperrectangle to polygon or polytope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#473]

**Comment by schillic** [comment]
Probably you mean the H-representation. For the V-representation, we should use the more general `AbstractPolytope` instead.

**Comment by mforets** [comment]
@kostakoida 

yes, i mean `convert(::Type{HPolytope}, H::AbstractHyperrectangle{N}) where {N}` and while we are at this, `convert(::Type{HPolygon}, H::AbstractHyperrectangle{N}) where {N}`
