### ISSUE TITLE
EmptySet of Rational{BigInt} is broken

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#475]
```julia
julia> N = Rational{BigInt}
julia> P = HPolygon([HalfSpace(N[1.0, 0.0], N(1.0)), 
                     HalfSpace(N[-1.0, 0.0], N(1.0)), 
                     HalfSpace(N[0.0, 1.0], N(1.0)), 
                     HalfSpace(N[0.0, -1.0], N(1.0))])

julia> vertices_list(P)

MethodError: no method matching element(::LazySets.EmptySet{Rational{BigInt}})
Closest candidates are:
  element(::LazySets.Singleton{N<:Real}) where N<:Real at /Users/mforets/.julia/v0.6/LazySets/src/Singleton.jl:34
  element(::LazySets.Singleton{N<:Real}, ::Int64) where N<:Real at /Users/mforets/.julia/v0.6/LazySets/src/Singleton.jl:52
  element(::LazySets.ZeroSet{N<:Real}) where N<:Real at /Users/mforets/.julia/v0.6/LazySets/src/ZeroSet.jl:39
  ...

Stacktrace:
 [1] vertices_list(::LazySets.HPolygon{Rational{BigInt}}, ::Bool) at /Users/mforets/.julia/v0.6/LazySets/src/AbstractHPolygon.jl:99
 [2] vertices_list(::LazySets.HPolygon{Rational{BigInt}}) at /Users/mforets/.julia/v0.6/LazySets/src/AbstractHPolygon.jl:93
```

**Comment by schillic** [comment]
There is no problem with `EmptySet`. You will also not be ableto use `element(::EmptySet{Float64})`. `element` is a function that is used for `Singleton`s.

**Comment by mforets** [comment]
hmm ... this can qualify as a wrong user input, because i didn't sort the given vector to `HPolygon`.

**Comment by schillic** [comment]
Should we sort the constraints by default?

**Comment by mforets** [comment]
that said, i would add to  `vertices_list(P::AbstractHPolygon{N},
                       apply_convex_hull::Bool=false
                      )::Vector{Vector{N}} where {N<:Real}`

everywhere that "Return the list of vertices of a polygon in constraint representation *such that its constraints are ordered in counter-clockwise fashion.*"

**Comment by mforets** [comment]
or in general, the interface `AbstractHPolygon` assumes that setting of sorted constraints.

**Comment by schillic** [comment]
I think this is rather a general assumption of the type. We should state this in the type's documentation, not necessarily in each function individually (although it may not hurt).

**Comment by mforets** [comment]
> Should we sort the constraints by default?

i like the idea; that would be analogue to the creation of `VPolygon`s

> I think this is rather a general assumption of the type. We should state this in the type's documentation, not necessarily in each function individually (although it may not hurt).

agreed.
