### ISSUE TITLE
Add type parameters to set types for array containers

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#481]
See [the explanation here](https://docs.julialang.org/en/v1/manual/performance-tips/index.html#Avoid-fields-with-abstract-containers-1).

Cross-references:
* `HalfSpace` (~#1031~)
* `LinearMap` (~#451~)
* Vector of linear constraints (~#1802~)
* `BallInf` (~#1870~)
* `Ball1` (~#1894~)
* `Zonotope` (~#1900~)
* `Ball2` (~#1999~)
* `VPolytope` (~#2004~)
* `Ellipsoid` (~#2006~)
* `HPolygon` (~#1851~)
* `HPolytope` (~#2035~)
* `HPolygonOpt` (~#2036~)
* `HPolyhedron` (~#1771~)
* `Ballp` (~#2116~)
* `Hyperplane` ~#2115~)
* `LineSegment` (~#2073~)
* `PolynomialZonotope` (~#2117~)

**Comment by mforets** [comment]
I've updated the list with the new #1802.

**Comment by mforets** [comment]
Also, it will be useful to have https://github.com/JuliaReach/LazySets.jl/issues/2032 to avoid code duplication for the usual vector/matrix representations.
