### ISSUE TITLE
Improved norm of hyperrectangular sets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#54]
Currently the norm of `BallInf` is implemented as follows.

```julia
return maximum(map(x -> norm(x, p), vertices_list(B)))
```

We could instead find the corner that is furthest from the origin (by simply adding/subtracting `radius` from `center[i]`, depending on the sign of `center[i]`, for each dimension `i`) and then immediately return the norm of this one vertex:

```julia
return norm((@. c + unit_step(c) * r), p)
```
EDIT: I had to change `sign` to `unit_step` for the 0 case.

@mforets: Am I right?

A similar idea should be applicable for `Hyperrectangle`.

**Comment by mforets** [comment]
Nice! I think is correct for any axis-aligned hyperrectangle. Start with
```
N = max_{x ∈ X} ‖ x ‖_p = max_{x ∈ vertices(X)} ‖ x ‖_p
```
(This can be seen a particular case of the fact that the optimum of any convex function over a polytope is attained in one of its vertices).  If the n-vectors center and radius of the hyperrectangle are denoted `c` and `r` respectively, then reasoning on the 2^n vertices we have that:

```
max_{x ∈ vertices(X)} ‖ x ‖_p = max_{α1, …, αn ∈ {-1, 1}} (|c1 + α1 r1|^p + ... |cn + αn rn|^p)^(1/p).
```

The function `x-> x^p`, `p >= 1`, is monotonically increasing and thus the maximum of `|ci + αi ri|^p` is given by `|ci + sign(ci) ri|^p` for each `i`. Hence, `x^* := argmax_{x ∈ X} ‖ x ‖_p` is achieved at `c + diag(sign(c)) r`.

This `norm` can dispatch on `AbstractHyperrectangle` as:

```julia
function norm(H::AbstractHyperrectangle, p::Real=Inf)::Real
    c, r = center(H), radius_hyperrectangle(H)
    return norm((@. c + LazySets.sign_cadlag(c) * r), p)
end
```

**Comment by mforets** [comment]
Actually `@assert p >= 1` is not needed because the argument that `x->x^p` is increasing also works if `0<p<1`.
