### ISSUE TITLE
Doctests fail in v0.7 due to missing prefix `LazySets.`

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#544]
In Julia v0.6, every type is preceded by the module name. In v0.7, this has changed. Example:
v0.6:
```julia
julia> Singleton([1.])
LazySets.Singleton{Float64}([1.0])
```
v0.7:
```julia
julia> Singleton([1.])
Singleton{Float64}([1.0])
```
Consequently, many doctests fail because the outputs do not coincide. What can we do here?

**Comment by mforets** [comment]
Maybe we should give up on trying to have a version with working doctests in **both** julia versions at the same time.

**Comment by schillic** [comment]
Okay. Then we have to adapt the doctests and add a guard to #467 that the doctests are only run for v0.7.
