### ISSUE TITLE
Revisit LinearConstraints.jl

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#57]
1. Rename the file to the singular form?
2. Outsource `Line` to a new file?
3. Should `Line`'s field `a::Vector{N}` become `a::Tuple{N, N}` because the constructor requires 2D input?
On the other hand, code-wise I do not see any problem with a `Line` having more than two dimensions. We only use it for 2D plots, but why should we restrict the general type? If we want to keep it 2D, I would rename it to `Line2` or so.
4. Should we promote `Line` to `LazySet`?
5. (related) Should we have a `LazySet` type for a half-space? This is inspired by the doc for `LinearConstraint`.

Action points here:
* [x] rename `LinearConstraints.jl` to `Line.jl` and promote `Line` to `LazySet`
* [x] add `LinearConstraint` as alias to `HalfSpace` and remove the type
* [x] outsource `intersection` function to a new file `concrete_intersection.jl`

**Comment by schillic** [comment]
From a discussion with @mforets:
This type is only used in `HPolygon(Opt).jl` and `iterative_refinement.jl` so far.
Maybe change the return type to `LazySet` which can here be either a `Singleton`, an `EmptySet` or a `Line` again.
We might even want to add a type `Point2D <: AbstractSingleton` of fixed size for this purpose.

**Comment by mforets** [comment]
1. ok
2. ok
3. `Line` is understood for 2d (or 3d). but for higher dims we should better use `Hyperplane` >> let's create a new issue?
4. ok -- what to return for its support vector?
5. ok -- new issue at #149

**Comment by schillic** [comment]
3. This is #150.

**Comment by schillic** [comment]
4. I have a similar problem for the half-space and the hyperplane. My thinking is that a solution only exists if the direction is either the zero vector or a normal of the line/plane. In those cases we can return any point `x` on the line/plane, i.e., such that `a⋅x = b`, as follows: Assuming that `a` is not the zero vector, we can choose `x[j] = 0` for all but one dimension `i` such that `a[i] ≠ 0`. For dimension `i` we can choose `x[i]` such that `x[i] = b / a[i]`. In other words, we return a scaled unit vector.
(Maybe we should check in the constructor that `a` is not the zero vector...)

**Comment by schillic** [comment]
Should we get rid of `LinearConstraint` and `Line` because they mean exactly the same as `HalfSpace` and `Hyperplane`?
We could have an alias `LinearConstraint` because it sounds more natural sometimes.

**Comment by mforets** [comment]
i would make `LinearConstraint` to be an alias for `HalfSpace` type, but keep `Line` since it is special for 2D, what do you think?

**Comment by schillic** [comment]
I updated the action points in the first post and also added "outsource `intersection` function to a new file `intersection.jl`".

**Comment by mforets** [comment]
ah ok you mean this one `intersection(L1::Line{N}, L2::Line{N})`. well but then we would have both `intersection.jl` for concrete ops and `Intersection.jl` for lazy ops .. i don't know, it sounds weird, even if it's clear within julia conventions.. (and what happens if the system files is not case sensitive). IMO we should better either add the concrete function into the associated type's file `Intersection.jl`, or to type-specific files such as with `minkowski_sum(Z1::Zonotope, Z2::Zonotope)` which belongs to `Zonotope.jl`. the advantage of the second choice is that everything around the type is in the same place (and you will often use functions defined in the file such as `order` etc), but a disadvantage is that one ends up with `minkowski_sum` functions dispersed in different files.

**Comment by schillic** [comment]
I think binary functions should go to their own files. Where do you put `minkowski_sum(Z::Zonotope, B::BallInf)`? We already did this for subset and intersection checks. You can still use `order` etc. in other files.
But you are right, having files that only differ in the case is confusing and dangerous, I did not think about that. I would not put concrete implementations also in `Intersection.jl` because this may end up in a huge file. Is there an alternative name? In the worst case, what about `concrete_intersection.jl`?

**Comment by schillic** [comment]
Making `LinearConstraint` an alias for `HalfSpace` is not so easy because we use it before this file is read. I will try to find out if one can use a symbol before it is defined.

**Comment by mforets** [comment]
when this happened in the past i was just swapping the order of the `includes`, but i don't know if that helps here..

**Comment by schillic** [comment]
Okay it would work with this order:
```
include("LazySet.jl")
include("HalfSpace.jl")
include("LinearConstraints.jl")
include("AbstractPolytope.jl")
```
But this would destroy the order completely :(

**Comment by mforets** [comment]
alphabetic? maybe we have to give up on that here :)

**Comment by schillic** [comment]
no, interfaces before set representations

**Comment by schillic** [comment]
Okay, actually we only need the `include("HalfSpace.jl")` above (I edited).
I could not find any way around, so I will go for it. 😭
