### ISSUE TITLE
Make sorting optional for convex hull algorithm

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#59]

**Comment by mforets** [comment]
One in particular? What type of application? As remarked [here](https://github.com/JuliaReach/LazySets.jl/issues/15), sorting is intended for the support vector of a VPolygon.

We could perhaps have an output-sensitive algorithm such as [Chan's](https://en.wikipedia.org/wiki/Chan%27s_algorithm) or [Kirkpatrick–Seidel algorithm](https://en.wikipedia.org/wiki/Kirkpatrick%E2%80%93Seidel_algorithm).

**Comment by mforets** [comment]
Another limitation is that we only have 2D now.

**Comment by schillic** [comment]
This is only saying: If the points are sorted, this can be more efficient. I have no application in mind where we can give this guarantee. This is just something I saw when I scanned through the code. Not important for me.

**Comment by mforets** [comment]
yes, if the given points are sorted (lexicographically) then the step `sort!(points, by=x->(x[1], x[2]))` can be avoided altogether. we could have  a keyword to let the user specify if this step is needed or not.
