### ISSUE TITLE
Intersection of a convex hull array with a halfspace

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#591]

**Comment by schillic** [comment]
Does it have to be an array?

**Comment by mforets** [comment]
i think that @kostakoida needs ti intersect `ConvexHullArray(Rsets.Xk)` with a halfspace or a hyperplane

**Comment by schillic** [comment]
We have a general implementation of the support function for `Intersection{N, <:LazySet{N}, <:Union{HalfSpace{N}, Hyperplane{N}, Line{N}}}`. I do not see a way to get a more specific algorithm for `ConvexHullArray`.
