### ISSUE TITLE
Specialized == for types

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#608]
In #604 we defined == generically to work on LazySet pairs.

From [this comment](https://github.com/JuliaReach/LazySets.jl/pull/604#issuecomment-418289213);

> this catch-all definition is not as fast as a function defined on each type. That is primarily because the for-loop creates variables which are Unions over all the field types in X, which is a little bit type unstable. So unrolling the loop manually will be faster.

**Comment by schillic** [comment]
Should we move this comment to #378?

**Comment by mforets** [comment]
duplicate of #378.
