### ISSUE TITLE
Plots in documentation became small

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#620]
Suddenly the plots shrank. I can reproduce locally with updated packages. A week ago or so the plots still had the right size.
This is likely an external issue, e.g., with `Plots` or `GR`, because we did not change any plot-related code.

**Comment by schillic** [comment]
This issue has been reported to the [`Plots.jl`](https://github.com/JuliaPlots/Plots.jl) people in their issue `#1738`.

**Comment by schillic** [comment]
The issue got closed.

> Oh, the issue is actually fixed on Plots master. We should tag a new release soon.

So we just have to wait for the next release here.

**Comment by schillic** [comment]
Unfortunately, all `Plots` releases after `v.0.17.4` only work with Julia `v1`, so we will never get this fixed before making the jump. Even in `v0.7` this issue remains.

**Comment by schillic** [comment]
According to a comment in `#1785` of [`Plots.jl`](https://github.com/JuliaPlots/Plots.jl):
> In Julia 0.7 you can set the output to png with gr(fmt=:png) to get normal size plots.

And indeed
```julia
julia> using Plots, LazySets

julia> plot(BallInf(ones(2), 1.))

julia> savefig("1.svg")

julia> savefig("1.png")
```
produces a small SVG but a big PNG.
However, for me this does not help when building the docs (I tried in different ways).
[Here](http://docs.juliaplots.org/latest/output/) is the documentation about the output format.

**Comment by mforets** [comment]
hmm if they work on 1.0, i would suggest to leave do nothing and live this in 0.7.

**Comment by schillic** [comment]
The thread explained that the change of behavior came with a change in `GR`. We can just pin `GR` to an older version (I just tested it) and it will work again :tada:

**Comment by mforets** [comment]
plots seem to be still small on the docs https://juliareach.github.io/LazySets.jl/latest/man/iterative_refinement.html

**Comment by schillic** [comment]
Huh, indeed. Reason from the Travis log:
```julia
ERROR: MethodError: no method matching pin(::String, ::VersionNumber)
Closest candidates are:
  pin(::Union{String, PackageSpec}; kwargs...) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/API.jl:192
```

**Comment by schillic** [comment]
Hm, [`pin` seems to be ignored by Julia](https://travis-ci.org/JuliaReach/LazySets.jl/jobs/444966194#L983). `GR` is first correctly downgraded, but then Julia performs an upgrade and installs the latest version again:
```julia
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [28b8d3ca] + GR v0.35.0
  Updating `~/.julia/environments/v0.7/Manifest.toml`
 [no changes]
 Resolving package versions...
 Installed GR ─ v0.33.1
  Updating `~/.julia/environments/v0.7/Project.toml`
  [28b8d3ca] ↓ GR v0.35.0 ⇒ v0.33.1 ⚲
  Updating `~/.julia/environments/v0.7/Manifest.toml`
  [28b8d3ca] ↓ GR v0.35.0 ⇒ v0.33.1 ⚲
  Building GR → `~/.julia/packages/GR/ztzRc/deps/build.log`
 Resolving package versions...
  Updating `~/.julia/environments/v0.7/Project.toml`
  [28b8d3ca] ↑ GR v0.33.1 ⚲ ⇒ v0.35.0 ⚲
```
My next try will be with moving the pinning to the very bottom.

**Comment by schillic** [comment]
Nope, did not work. I give up.

**Comment by schillic** [comment]
After switching to deploying the docs from v0.7 (last step done in #873), the plots are big again :tada:
