### ISSUE TITLE
false negative with `in`. HPolytope example

### ISSUE THREAD

**Issue by tomerarnon** [JuliaReach/LazySets.jl#621]
For an HPolytope H:
```
julia>issubset(H, H)
false

jula>issubset(H, H, true)[2]
 [-0.89358, -1.15394, -0.82035]

julia> vertices_list(H)
6-element Array{Array{Float64,1},1}:
 [-0.89358, -1.15394, -0.82035]        # <-- it doesn't get past the first point in the case.
 [-1.24182, -2.08865, -0.828531]  
 [-0.040599, 0.57888, -0.635292]
 [1.24182, 2.08865, 0.828531]   
 [0.040599, -0.57888, 0.635292] 
 [0.89358, 1.15394, 0.82035]   

julia> for p in vertices_list(H)  # turns out more points are problematic
           println(p in H)
       end
false
false
true
false
false
false
```

For the record, H was constructed as follows:
```
using LazySets, Polyhedra, CDDLib

Z = Zonotope(zeros(3), rand(3,3))
H = HPolytope(polyhedron(VPolytope(vertices_list(Z))))
```
The problem is clearly in `in`, but some vertices are correctly found to be in the Polytope, so I thought the full context would be helpful. I haven't yet dived into the source code to see what's going on, but given the nature of the problem of finding points on a boundary, perhaps there is a mistake with `<` vs `<=` somewhere? I am also tempted to think there could be a rounding error when calculating the points, but again I am only speculating.

**Comment by schillic** [comment]
I have not yet looked into this, but I suspect that the membership checks at a set's boundaries are subject to rounding errors when using floating point representation.
I had created #126 for that purpose a while ago, but never got to work on that.

**Comment by mforets** [comment]
Side comment: the following notation is equivalent to `HPolytope(polyhedron(VPolytope(vertices_list(Z))))`:

```julia
julia> H = tohrep(VPolytope(vertices_list(Z)))
```

With #214 we should provide the even shorter

```julia
julia> H = convert(HPolytope, Z)
```

**Comment by mforets** [comment]
I confirm that the problem is with the implementation of set membership function, `(x::AbstractVector{N}, P::HPolytope{N})::Bool where {N<:Real}`: [it is defined as a strict inequality](https://github.com/JuliaReach/LazySets.jl/blob/master/src/HPolytope.jl#L129):

```julia
julia> @which vertices_list(H)[1] ∈ H
in(x::AbstractArray{N,1}, P::LazySets.HPolytope{N}) where N<:Real in LazySets at /Users/forets/.julia/v0.6/LazySets/src/HPolytope.jl:126
```

I agree that it should be changed to `dot(c.a, x) ≥ c.b`.

**Comment by schillic** [comment]
I disagree. The test is for a negative answer.

**Comment by mforets** [comment]
Ooops, you're right. It is because of floating point errors:

```julia
julia> c = H.constraints[7]
LazySets.HalfSpace{Float64}([-4.32453, 9.13741, -1.0], 4.2003702543707515)

julia> dot(c.a, x) > c.b
true

julia> c.b
4.2003702543707515

julia> dot(c.a, x)
4.200370254370753
```

We should use a more robust way for this type of check.

**Comment by schillic** [comment]
I get this:
```julia
julia> c = constraints_list(H);

julia> v = vertices_list(H)[1];

julia> for i in 1:length(c)
       println(dot(v, c[i].a) <= c[i].b)
       end
true
true
true
false
true
true
true
true

julia> dot(v, c[4].a) 
2483547528179771630973188545003080719847663557//2483547528179766613641824151195489004931344471

julia> c[4].b
1//1
```

Actually, I do not understand this:
```julia
julia> for i in 1:length(c)
       println(c[i].b)
       end
1//1
1//1
1//1
1//1
1//1
1//1
1//1
1//1
```
So all constraints have normal vector 1, which sounds like a bug.

**Comment by tomerarnon** [comment]
I am not getting the same result as you for c.b. But still it seems like a strange "coincidence" to get all `1//1`s though:
```
julia> for i in 1:length(c)
           println(c[i].b)
       end
1//1
359495517682493915074861807175006873026590145//348901357518253381582522266304991802003816448
1797477588412469575374309035875034365132950725//1057311034721436615209096192387374431355273216
1797477588412469575374309035875034365132950725//450873332342013525694111135548882645776596992
1//1
359495517682493915074861807175006873026590145//348901357518253381582522266304991802003816448
1797477588412469575374309035875034365132950725//450873332342013525694111135548882645776596992
1797477588412469575374309035875034365132950725//1057311034721436615209096192387374431355273216


julia> for i in 1:length(c)
           println(BigFloat(c[i].b))
       end
1.000000000000000000000000000000000000000000000000000000000000000000000000000000
1.030364342058159752417270894108509612902020254522699452228166237687797214204652
1.700046182612706954584806395679215857233630580045478935090379571542381736584421
3.986657580912278840193955879000189945236442909854157253188503429950173374453396
1.000000000000000000000000000000000000000000000000000000000000000000000000000000
1.030364342058159752417270894108509612902020254522699452228166237687797214204652
3.986657580912278840193955879000189945236442909854157253188503429950173374453396
1.700046182612706954584806395679215857233630580045478935090379571542381736584421
```
For the record, running the example on a zonotope with 9 random constraints yielded no `1//1`s at all.

As for whether and how to add tolerance to the check, I can't say for sure... When I get the chance I will do some experimenting with manually bloating the polytope to better understand the errors involved.

However, the fact that we are seeing this with BigInt Rationals suggests this is indeed a bug, no? We should be seeing arbitrary precision, I think.

**Comment by schillic** [comment]
I found the problem with exact arithmetic. This happened because for `HPolytope`'s `vertices_list` above we did not specify `backend=CDDLibrary(:exact)`, so it used the default backend with floating points:
```julia
julia> H
LazySets.HPolytope{Rational{BigInt}}(LazySets.HalfSpace{Rational{BigInt}}[LazySets.HalfSpace [...]

julia> P = polyhedron(H)
Polyhedron CDDLib.CDDPolyhedron{3,Float64}:
8-element iterator of Polyhedra.HalfSpace{3,Float64,Array{Float64,1}}:
 HalfSpace([5.30783, -1.78506, -4.84037], 1.0)
 [...]
```
We did not see this because the function contract requests the same numeric type, so Julia automatically `convert`ed the result to `Rational{BigInt}` again.

If you instead use `v = vertices_list(H, backend=CDDLibrary(:exact))`, it works.

I am not sure if this should be considered a user error or not.

**Comment by tomerarnon** [comment]
Yes, using `vertices_list(H, backend=CDDLibrary(:exact))` returns all true! 
No bug then.

**Comment by schillic** [comment]
You might expect that a `HPolytope{Rational{BigInt}}` would use exact arithmetic by default, but it does not. This is at best confusing.
What is worse: The `issubset` check does not use exact arithmetic and will fail for the same reason. Currently there is no way to specify the backend for `issubset`, so the user has no way other than reimplementing the check. I created #623 for further discussion.

**Comment by schillic** [comment]
To conclude, this issue is related to floating point errors, which are inherent. But we discovered some new issue with exact arithmetic, to be continued in #623.

**Comment by mforets** [comment]
_Update_: with #623 for a better default  of concrete operations between polytopes and #631 for convenience type conversions (*) we can do:

```julia
julia> using LazySets, Polyhedra

julia> N = Rational{BigInt};

julia> Z = Zonotope{N}(zeros(3), rand(3,3));

julia> H = convert(HPolytope, Z);

julia> H ⊆ H
true
```

(*) A more efficient algorithm than the current one for`Zonotope` -> `HPolytope` is known (see #416) but hasn't been implemented in `LayzSets` yet.
