### ISSUE TITLE
Behavior of isempty for polytope in constraint representation

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#628]
See: https://github.com/JuliaReach/LazySets.jl/pull/624#discussion_r217891233

**Comment by mforets** [comment]
I agree; it has to run a feasibility LP. Maybe what i had in mind in that comment is to write it down in `HPolytope.jl`, instead of passing through the conversion to `polyhedron`.

**Comment by mforets** [comment]
Why close, shouldn't we add this? This implementation can be used for any set defined by a list of constraints.

**Comment by schillic** [comment]
Okay, I misunderstood you.

**Comment by schillic** [comment]
What is the benefit of reimplementing it (apart from independence of `Polyhedra`)?

**Comment by schillic** [comment]
This was added in #1056.
