### ISSUE TITLE
Add function that returns a point inside a set

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#63]
* A default implementation could just pick any direction and ask for a support vector.
* The empy set should throw an exception.
* What would be a good name for this function? `element`? CC: @mforets

**Comment by schillic** [comment]
I will use `element`, which is consistent with the function of `AbstractSingleton`.

**Comment by mforets** [comment]
+1 `element`, and +1.5 for `an_element`

**Comment by schillic** [comment]
@mforets: Should we add a default implementation for any `LazySet` as follows?
```julia
function an_element(S::LazySet)::Vector{<:Real}
    return σ(ones(dim(S)), S)
end
```
Problem: the direction has type `Float`.
If yes, where do we put this? Create a new file `LazySet_functions.jl`? Or a file `LazySet.jl` and move the type definition there as well?
There are already `norm`/`radius`/`diameter` in `box_approximations.jl`, so maybe we want to move those to this file, too.

**Comment by mforets** [comment]
> Problem: the direction has type Float.

this could be worked around if #44 gets in.

> If yes, where do we put this? 

also note the file `support_function.jl`, which just defines generic support vector for any `LazySet`. a file `LazySet.jl` for this group of definitions is not a bad idea.

**Comment by mforets** [comment]
.. or a file `AbstractLazySet.jl` , and in that case also export the type `AbstractLazySet` as an alias for `LazySet`. i'm ok with either way, what do you think?

**Comment by schillic** [comment]
> this could be worked around if # 44 gets in.

Good, then let us fix that one first.

> a file `LazySet.jl` for this group of definitions is not a bad idea.

I also like this.

> or a file `AbstractLazySet.jl`

What is an argument for this? (We can also rename the file later and just need to change one line.)

**Comment by mforets** [comment]
ok. 

> What is an argument for this? 

only that it goes in line with other files for abstract types such as `Abstractxyz`.

for the implementation we can take as well `σ([1.; fill(0, dim(S))], S)` which has more zeros :stuck_out_tongue:
