### ISSUE TITLE
Linear map should preserve input set type for polygons

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#631]
Proposal: the concrete linear map of a `HPolytope` (resp. `VPolytope`), should return a `HPolytope` (resp. `VPolytope`). See [linear_map](https://github.com/JuliaReach/LazySets.jl/blob/master/src/AbstractPolytope.jl#L71), that currently the return type depends on the dimension of the set.

I realized that keeping the input type (concrete polytopes) is convient when writing algorithms because you often want to keep the same family, eg. for intersecting polytopes. Conversion to a polygon can be done outside this function with a simple `convert(HPolygon, X)` (resp `convert(VPolygon, X)`).

The guiding principle is to return objects whose type only depends on the types of the inputs.

**Comment by schillic** [comment]
Okay, then we will have to replace `AbstractPolytope` by `T<:Union{VPolytope, VPolygon}` and remove the `if`.
Next we have to add implementations for the remaining types that are not covered anymore.

**Comment by mforets** [comment]
while we are in the interface, why not having a fallback implementation

```julia
function linear_map(M::AbstractMatrix, P::AbstractPolytope{N})::VPolytope{N} where {N<:Real}
    @assert dim(P) == size(M, 2)
    return (broadcast(v -> M * v, vertices_list(P))) |> VPolytope{N}
end

function linear_map(M::AbstractMatrix, P::AbstractPolygon{N})::typeof(P) where {N}
    @assert dim(P) == size(M, 2)
    V = VPolygon(broadcast(v -> M * v, vertices_list(P)))
     return convert(typeof(P), V)   #  keep this?
end
```

**Comment by schillic** [comment]
Okay, but let us simplify the second one:
```julia
function linear_map(M::AbstractMatrix, P::T)::T where T<:AbstractPolygon{N} where N
    @assert dim(P) == size(M, 2)
    V = VPolygon(broadcast(v -> M * v, vertices_list(P)))
    return convert(T, V)
end
```
