### ISSUE TITLE
Remove Plots from REQUIRE

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#647]
The library should not have the requirement `Plots.jl`, which is only used for plotting. We have `RecipesBase.jl` for defining the plot recipes.

**Comment by mforets** [comment]
does removing this requirement conflict with having `plot` commands in the unit tests?

**Comment by schillic** [comment]
We have to add it manually before running the tests/building the docs of course. But to use the package, it should not be required.

**Comment by mforets** [comment]
> But to use the package, it should not be required.

I am neutral on this one, because the user would need `Plots` in most use cases. But it's true that visualization is is as optional as `Polyhedra` for concrete polyhedra so i think it is consistent to make the user install it separately.
