### ISSUE TITLE
Higher dimensional line

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#652]
`Line` is currently 2D set, but one could take it to also mean the n-dim set defined by the points `p` such that `p = d*l + lo`, where `lo` is a point on the line, `d` is a real number, and `l` is the direction of the line.

**Comment by schillic** [comment]
So what is your proposal? Generalize this type? Add a new type?

**Comment by mforets** [comment]
generalize this type.

**Comment by schillic** [comment]
I suggest to also keep the old type for specializations. A name could be `Line2` (I have seen that before) or `Line2D`.

**Comment by mforets** [comment]
Do we have some examples that can use this specialization? I checked a bit and didn't see this advantage, then i said let's don;t specialize (yet).

**Comment by schillic** [comment]
> Do we have some examples that can use this specialization?

The `vertices_list(::AbstractHPolygon)` function. And we might have to remove the concrete `intersection` implementation if it only works in 2D (not sure).
