### ISSUE TITLE
vertices_list of Zonotope applies convex_hull!

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#669]
This only makes sense in 2D.
I wonder why this even works in higher dimensions. We should have an `@assert length(points[1]) == 2` in `convex_hull!`.

We actually do not need to sort the vertices. A user should do that if required (e.g., when creating a `VPolygon` in the 2D case).

**Comment by mforets** [comment]
yes i agree, `vertices_list(::Zonotope)` should `return vlist`.

i'm neutral in adding `@assert length(points[1]) == 2 in convex_hull!`. it checks the first element but doesn't check all of them.. and since there are potentially many points, i don't think it make sense to check all of them.

**Comment by schillic** [comment]
> I'm neutral in adding @assert length(points[1]) == 2 in convex_hull!. it checks the first element but doesn't check all of them

Yeah, it is only a necessary test, but I think it catches most problems.
