### ISSUE TITLE
Emptiness check of intersection of two sets

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#67]
Add a function `is_intersection_empty(S1, S2; witness=false)` that returns `true` if the sets `S1` and `S2` do not intersect.
If the flag `witness` is set, also produce a witness, i.e., a point (vector) `x` such that `x ∈ S1 ∩ S2` if the intersection is nonempty.
The table below tracks the current combinations that we support:

| ↓ ∩ → | Ball1 | Ball2 | Ballp | HRect | Polygon | Zonotope | Singleton |
|----------|--------|--------|--------|-----------|------------|-------------|--------------|
|Ball1     |  |  |  |  |  |  | x|
|Ball2     |  |  |  |  |  |  | x|
|Ballp     |  |  |  |  |  |  | x|
|HRect   |  |  |  | x|  |  | x|
|Polygon   |  |  |  |  |  |  | x|
|Zonotope  |  |  |  |  |  |  | x|
|Singleton | x| x| x| x| x| x| x|

Related: #139

**Comment by schillic** [comment]
Possibly helpful: [Boolean operations on polygons](https://en.wikipedia.org/wiki/Boolean_operations_on_polygons)

**Comment by schillic** [comment]
For convex polygons this is not too complicated, but also not trivial.

* [Sutherland-Hodgman](https://stackoverflow.com/questions/13101288/intersection-of-two-convex-polygons/13105297#13105297) (not efficient),

* [rotating calipers](http://www.iro.umontreal.ca/~plante/compGeom/algorithm.html),

* sweep lines approach: [cryptic description](https://stackoverflow.com/questions/13101288/intersection-of-two-convex-polygons/31489587#31489587) and [good description](http://web.uvic.ca/~pgordon/geom/),

* [separating axes theorem](https://en.wikipedia.org/wiki/Hyperplane_separation_theorem#Use_in_collision_detection) and [algorithm outline](http://wm.ite.pl/articles/convex-polygon-intersection/article.html)

* [edge chase](https://www.sciencedirect.com/science/article/pii/0146664X82900235) and [nice example slides](http://www.bowdoin.edu/~ltoma/teaching/cs3250-CompGeom/spring17/Lectures/cg-convexintersection.pdf) (my current favorite)

**Comment by mforets** [comment]
borrowing your table from 

| ↓ ∩ →   | Ball1 | Ball2 | Ballp | HR/BInf | Polygon | Singleton |
|---------|-------|-------|-------|------------------------|---------|-----------|
|Ball1    |  |  |  |  |  |  |
|Ball2    |  |  |  |  |  | |
|Ballp    |  |  |  |         |  |  |
|HR/BInf   |  |  |  |         |  |  |
|Polygon  |  |  |  |         |  |  |
|Zonotope |  |  |  |         |  |  |
|Singleton |  |  |  |         |  |  |

**Comment by schillic** [comment]
You will be disappointed:

| ↓ ∩ → | Ball1 | Ball2 | Ballp | HR/BInf | Polygon | Singleton |
|----------|--------|--------|--------|-----------|------------|-------------|
|Ball1     |  |  |  |  |  |  |
|Ball2     |  |  |  |  |  |  |
|Ballp     |  |  |  |  |  |  |
|HR/BInf   |  |  |  | x|  |  |
|Polygon   |  |  |  |  |  |  |
|Zonotope  |  |  |  |  |  |  |
|Singleton |  |  |  |  |  | x|

**Comment by mforets** [comment]
For zonotopes we will find good information both in A. Girard and in M. Althoff dissertations.

**Comment by schillic** [comment]
Today I got a very elegant alternative to solve this problem:
`X ∩ Y = ∅ ⇔ 0 ∉ (X ⊕ -Y)`
This means that if we can decide the membership, we get this check for free. However, for Minkowski sum the membership check is an open task in #77.

**Comment by mforets** [comment]
Do we have an operator for `-Y`? For polytopes it could be seen as the linear map that transforms each vertex to its opposite wrt the origin.

**Comment by schillic** [comment]
> Do we have an operator for -Y?

No, but conceptually it should be really simple: Add a lazy operation, say, `Negative`, and implement all methods by calling the method for the wrapped set and multiplying the result by -1. It is just an annoying task, and I do not think it is worthwile because membership of Minkowski sum is really complicated.

**Comment by schillic** [comment]
Closing this as "too meta". We now have the function `isdisjoint` for quite some set types already.
