### ISSUE TITLE
Fix HPolygon vs HPolygon intersection in floating point

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#672]
Let

```julia
p = VPolygon([[0.161915, 0.780202], 
              [0.264545, 0.293386],  
              [0.54406, 0.0902449],  
              [0.801169, 0.00964868],
              [0.954425, 0.155487],
              [0.8336, 0.636783],
              [0.656131, 0.737161]])

q = VPolygon([[0.0800543, 0.318534],
              [0.122886, 0.0980148],
              [0.655319, 0.143195],
              [0.627578, 0.699661],
              [0.245012, 0.953383]])

plot([p, q], alpha=0.1)
```

![screen shot 2018-09-25 at 10 33 34](https://user-images.githubusercontent.com/12424594/46017656-62d88680-c0ae-11e8-9fca-62e372f9ed84.png)

Compute the intersection with `CDD`:

```julia
using Polyhedra

pv = convert(VPolytope, p)
qv = convert(VPolytope, q)
plot!(intersection(pv, qv), alpha=0.6, color="orange")
```

<img width="694" alt="screen shot 2018-09-25 at 10 41 19" src="https://user-images.githubusercontent.com/12424594/46018082-733d3100-c0af-11e8-85d8-2eafda29b111.png">

Compute the intersection using `intersection(::HPolygon, ::HPolygon)`:

```julia
ph = convert(HPolygon, p)
qh = convert(HPolygon, q)
plot!(intersection(ph, qh), alpha=0.3, color="black")
```

<img width="681" alt="screen shot 2018-09-25 at 10 42 46" src="https://user-images.githubusercontent.com/12424594/46018183-a7185680-c0af-11e8-8122-853f07b18b55.png">

**Comment by mforets** [comment]
FWIW note that

```julia
function intersection2(P1, P2)
    P = HPolygon()
    addconstraint!.(P, constraints_list(P1))
    addconstraint!.(P, constraints_list(P2))
    return P
end

plot(intersection2(tohrep(p), tohrep(q)), alpha=0.3, color="black")
```

<img width="678" alt="screen shot 2018-09-25 at 10 44 50" src="https://user-images.githubusercontent.com/12424594/46018318-f52d5a00-c0af-11e8-8c78-e71d6c281d89.png">

**Comment by schillic** [comment]
:worried:

**Comment by mforets** [comment]
Just checked this again, and it has been fixed by now 🎉 

```julia
ph = convert(HPolygon, p)
qh = convert(HPolygon, q)
plot!(intersection(ph, qh))
```

<img width="366" alt="Screen Shot 2019-05-08 at 08 35 30" src="https://user-images.githubusercontent.com/12424594/57337327-46d0b380-716c-11e9-8dfb-a5c731b2f4bd.png">

----

Regarding computation time, 

- `intersection(::HPolygon, ::HPolygon)` ... 140us
- `intersection(::HPolytope, ::HPolytope)` ... 284us
- `intersection(::HPolytope, ::HPolytope, backend=CDDLib.Library())` ... 645us

**Comment by mforets** [comment]
On the other hand intersection of original `VPolygon` is slow:

```julia
@btime intersection($p, $q) # as VPolygon
2.594 ms (32355 allocations: 1.84 MiB)
```
(this passes through Polyhedra through [this function](https://github.com/JuliaReach/LazySets.jl/blob/6289f14b24c78f8e13a7824bafc0487ec2408169/src/concrete_intersection.jl#L412), i'm thinking if we should rather use a 2D implementation, or at least convert to HPolygon and then use the intersection of HPolygon should be cheaper.
