### ISSUE TITLE
Containment check

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#68]
Add a containment check `∈(x, S)` for all sets.

For some we already have `is_contained`. I prefer `in` instead (the Julia alias for `∈`).

**Comment by mforets** [comment]
where `x` is a point? for polygons we should check [point in polygon](https://en.wikipedia.org/wiki/Point_in_polygon) algorithms.

agreed for overloading `in`

**Comment by mforets** [comment]
.. still we can use `is_contained` in the mathematical sense, as for #69

**Comment by schillic** [comment]
Yes, `x` is a point. Should it be a `Vector` or a `Singleton`?
We can provide a convenience conversion function for the other combination.

**Comment by mforets** [comment]
we can implement it with sets, i.e. using `Singleton`, and also provide the shortcut for `x` being a Vector.

**Comment by schillic** [comment]
I thought about it and I think it is more efficient to unwrap a `Singleton` (which is anyway what has to be done) in one case than to wrap a vector in a `Singleton` in the other case.
So I want to implement it for `AbstractVector` and provide a conversion function for `Singleton`.

**Comment by schillic** [comment]
> for polygons we should check point in polygon algorithms.

Thanks for this pointer. "Ray casting" sounds simple for our sorted `VPolygon`, so I will implement this one.

The algorithms in this link work for nonconvex polygons, and at the bottom it is said "Simpler algorithms are possible for [...] convex polygons [...]."
We also already have an implementation for `HPolygon` using support vectors. Not sure if this is "optimal", though.
We can always add better algorithms later, for now I just want *one* solution.

**Comment by schillic** [comment]
We are not 100% sure that the Zonotope implementation works in all cases, but keep it for now.

Most types are now supported by #74. Eventually we can continue in #77 with the missing ones.
