### ISSUE TITLE
Tag last release that supports v0.6

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#693]
A new release `v1.5.0` can be the latest release that supports julia v0.6.x

[Release log](https://github.com/JuliaReach/LazySets.jl/wiki/Release-log-tracker)

**Comment by schillic** [comment]
Let us wait with that for two more weeks.

**Comment by mforets** [comment]
i'd like to reconsider this issue. let's use the milestone `v1.5.0` for the issues that we'd like to get in this release.
