### ISSUE TITLE
Concrete intersection between VPolygons

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#698]
https://www.swtestacademy.com/intersection-convex-polygons-algorithm/

**Comment by schillic** [comment]
Currently we fall back to `Polyhedra`. Should we instead convert to H-rep if `Polyhedra` is not loaded?

**Comment by mforets** [comment]
intersection of convex polygons was implemented in https://github.com/JuliaReach/LazySets.jl/pull/2345 so i think we should close this. i kept the reference in the wiki : https://github.com/JuliaReach/LazySets.jl/wiki/References#polygon-intersection
