### ISSUE TITLE
Fix HPolygon plot interface with Gadfly

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#7]
Review `plot_polygon` (-> `plot` ?) and test different backends: PyPlot, Gadfly, Plots.

**Comment by schillic** [comment]
You have my vote for changing the name to `plot`.
It is shorter and not specific to the type, so we could also overload the function with other types in the future.

**Comment by mforets** [comment]
Okay so the branch is ready for review, let's continue in a new PR. 

I modified the REQUIRE to include the dependencies `RecipesBase` (for the `@recipe` macro) and `Plots` to have the `plot` function in interactive mode. IIUC, `Plots.jl` is a "macro" interface to use specific backends such as GR, PyPlot, Plotly. Gadfly is not supported.

**Comment by mforets** [comment]
followed in PR #11.
