### ISSUE TITLE
Use issubset for function names

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#700]
Function signatures in `/src/issubset.jl` are written using the `⊆` operator. But if you ask for the help in the REPL for `?issubset` it won't show those of lazysets. 

We should rather use `issubset` for the signatures, which will make both `?issubset` and `?⊆` be complete.

**Comment by schillic** [comment]
For me it works.
```
?\issubset<TAB>
```

**Comment by schillic** [comment]
I tried this in #2238 and this does *not* work for `?⊆`.

**Comment by mforets** [comment]
ok, but in that case, is there a motivation for the change?

**Comment by schillic** [comment]
I first made the change and then realized it. You can choose or tell me how to fix it to make both work.
