### ISSUE TITLE
Lazy support function for lazy operations

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#715]
For the following lazy operations, the support function [is easy to define recursively](https://juliareach.github.io/LazySets.jl/latest/man/polyhedral_approximations.html#Support-Function-1), without falling back to the support vector:

* [x] `LinearMap` #716
* [x] `ExponentialMap` #717
* [x] `MinkowskiSum`#717
* [x] `MinkowskiSumArray` #717
* [x] `ConvexHull` #717
* [x] `ConvexHullArray` #717
* [x] `CartesianProduct` #719
* [x] `CartesianProductArray` #719

We need this for operations such as `Intersection` where we do have an implementation of the support function but lack an implementation of the support vector.

(This is orthogonal to #600.)

**Comment by mforets** [comment]
For `CartesianProduct` and `CartesianProductArray`, formula (1.4) [here](https://juliareach.github.io/LazySets.jl/latest/man/polyhedral_approximations.html#Support-Function-1) is just the fallback implementation using the support vector. For this reason i suggest not to add anything.

**Comment by schillic** [comment]
> For CartesianProduct and CartesianProductArray, formula (1.4) here is just the fallback implementation using the support vector.

It looks to me as if it can be defined as the sum (exactly like the support function of the Minkowski sum). Correct?

**Comment by mforets** [comment]
Correct! Thanks for adding it.
