### ISSUE TITLE
Add ρ upper bound for an intersection

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#720]
Proposal: add 

```julia
ρ_upper_bound(d, cap::Intersection) = min(ρ_upper_bound(d, cap.X), ρ_upper_bound(d, cap.Y))
```
for intersections.

We can also add a default `ρ_upper_bound` which returns the exact `ρ`.

See #706, #707 for another approach that uses type dispatch.

**Comment by schillic** [comment]
I added a type declaration above.
