### ISSUE TITLE
Add `upper_bound` option to intersection 

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#722]
In https://github.com/JuliaReach/LazySets.jl/pull/721 we added `ρ_upper_bound` in the approximations module.

In other parts of the library eg. `is_intersection_empty` between a set and a halfspace, `ρ` is used. Instead of adding `is_intersection_empty_upper_bound`, we can have an optional keyword argument (eg. `upper_bound`) in the exact `ρ`, for this particular case of intersection, such that 

```julia
function ρ(d::AbstractVector{<:Real}, cap::Intersection, upper_bound=true)::Vector{<:Real} 
   if upper_bound 
        ρ_upper_bound(d, cap)
    else 
        error("the exact support function of an intersection is not implemented yet")
  end 
end
```

We would have to extend the method `is_intersection_empty` to accept keyword arguments that are passed through.

**Comment by schillic** [comment]
I still think that `upper_bound=true` is not good, for two reasons.
1. This is not the behavior you would expect.
2. We may run into an infinite loop when switching between `ρ` and `ρ_upper_bound`.

**Comment by mforets** [comment]
Agreed! It should be `upper_bound=false`.
