### ISSUE TITLE
Default is_intersection_empty between lazyset and abstract polytope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#724]
The proposal is to generalize

```julia
function is_intersection_empty(X::LazySet{N},
                               P::Union{HPolytope{N}, AbstractHPolygon{N}}
                              )::Bool where N<:Real

    for Hi in constraints_list(P)
        if is_intersection_empty(X, Hi)
            return true
        end
    end
    return false
end
```

to `P::AbstractPolytope{N}`, given that this type corresponds to "... sets defined as an intersection of a finite number of halfspaces, or equivalently, sets with finitely many vertices."

One can add the check

```julia
@assertion method_exists(constraints_list, Tuple{typeof(X)}) "this implementation requires that the list of constraints of `X` is available
```

**Comment by schillic** [comment]
I agree, but currently these are all types that support this method (see #188). I do not care if we change this now or later.

**Comment by mforets** [comment]
Any `AbstractHyperrectangle` also has `constraints_list`.

**Comment by schillic** [comment]
We have `isdisjoint(P::AbstractPolyhedron, X::LazySet)` now.
