### ISSUE TITLE
Constraints list of Ball1

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#731]
`B1(c, r)`, in dimension `n`, has `2^n` constraints whose normal directions `di` are

```
julia> Iterators.product([[1, -1] for i = 1:n]...)
Base.Iterators.Prod2{Array{Int64,1},Array{Int64,1}}([1, -1], [1, -1])

julia> collect(ans)
2×2 Array{Tuple{Int64,Int64},2}:
 (1, 1)   (1, -1)
 (-1, 1)  (-1, -1)
```

The constraints can be defined as `di^T (x-c) <= r` for all `di`.

**Comment by schillic** [comment]
> The constraints can be defined as di^T (x-c) <= r for all di.

This means that you have to create `LinearConstraint(di, dot(di, c) .+ r)`.
