### ISSUE TITLE
HPolygon conversions need to sort the constraints

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#736]
Some `convert` methods to `HPolygon` do not sort the constraints, e.g., [this one](https://github.com/JuliaReach/LazySets.jl/blob/372c19ae66309d740769f1d60b35aff30496fac4/src/convert.jl#L357).

**Comment by mforets** [comment]
As we have discussed elsewhere, i think that the constructor of `HPolygon` should sort the constraints by default.

**Comment by schillic** [comment]
See #477.
