### ISSUE TITLE
Add upper_bound argument to isdisjoint methods

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#737]

**Comment by schillic** [comment]
Actually, should the ρ functions be modified or the callers (in this case `isdisjoint`)? It sounds strange to modify a function that should not actually be used.

**Comment by schillic** [comment]
We agreed that we instead add `upper_bound=false` to `is_intersection_empty`.

**Comment by mforets** [comment]
With this option, there is the risk that `is_intersection_empty` returns `false` when it is actually `true`. See [this comment](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Approximations/upper_bounds.jl#L87).

**Comment by schillic** [comment]
`upper_bound` has gone.
