### ISSUE TITLE
Deprecate HPolytope's conversion constructor

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#768]
proposal: deprecate  `HPolytope(S::LazySet) = convert(HPolytope, S)` . usage of `convert(::Tagert_Type, S)` is more general and should be preferred.

**Comment by schillic** [comment]
Do you really mean "deprecate" or "remove"?

**Comment by mforets** [comment]
yes, i meant `@deprecate`. i haven't checked but if we don't use this construction much often in other packages (SX, Reachability), we can just delete it too.

**Comment by schillic** [comment]
Just for clarification: This constructor did not exist anymore.
