### ISSUE TITLE
Containment check, missing cases

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#77]
This is a continuation of #68. There we added containment checks (`x ∈ S`) for most set types. Some are still missing.

* [x] `HPolytope` (#167)
* [x] `Intersection` (#167)
* [ ] `ConvexHull`
A sufficient test is to check containment in both generating sets, but for negative answers one has to continue, e.g., checking ray intersection from some vertex of one set in the other set.
* [ ] `ExponentialProjectionMap`
* [ ] `MinkowskiSum`
One could subtract one set from the point and check for nonempty intersection with the other set. There is literature for the case that the sum consists of polytopes only, this could be interesting.

**Comment by mforets** [comment]
*proposal:*
add a method

```julia
∈(x::Singleton{N}, X::LazySet{N}; kwargs...)::Bool where {N<:Real} = ∈(x.element, X; kwargs...)
```

**Comment by schillic** [comment]
I think we had this idea before but then we said "a singleton is a set, so better use `issubset`".

**Comment by schillic** [comment]
Closing since there is no clear way to implement these methods.
