### ISSUE TITLE
Add check whether an HPolyhedron is bounded

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#772]
Maybe also add a convenience function that returns an `HPolytope` in case the set is bounded.

**Comment by mforets** [comment]
`isbounded(::HPolyhedron)` was added in #956.

 > Maybe also add a convenience function that returns an HPolytope in case the set is bounded.

Hmm i dunno, we can also leave the conversion to the user (maybe in some application the intention is to keep the sets bounded, so an error should be thrown).
