### ISSUE TITLE
Add method to swap arguments in a lazy operation

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#817]
The idea is not to actually swap the arguments (which is generally not possible due to type constraints) but to return a new object. This is good for convenience.
In the particular case of an `Intersection` object, we can also copy the `cache`.

**Comment by mforets** [comment]
example of current `master`:

```julia
X = BallInf(ones(2), 1.0);
H = LazySets.HalfSpace([-1.0, 0.0], 0.0);
d = [0.0, 1.0];

Z = X∩H
ρ(d, Z)
ρ(d, Z)

is intersection empty

2.0000000000000004

Z = H∩X
ρ(d, Z)
ρ(d, Z)
is intersection empty
is intersection empty

2.0000000000000004
```

**Comment by schillic** [comment]
#819 provided the method for `Intersection. We should add the method also for the other binary lazy operations.
