### ISSUE TITLE
vertices_list of HPolyhedron

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#820]
Does it make sense to have this? Currently we create it from the constraints, which is clearly wrong.

```julia
julia> plot(LazySets.HPolyhedron{Float64}(LazySets.HalfSpace{Float64}[
LazySets.HalfSpace{Float64}([-1.0, 0.0, 0.0, 0.0], 0.0),
LazySets.HalfSpace{Float64}([-0.714286, -1.0, 0.0, 0.0], 0.0)
]));
ERROR: BoundsError: attempt to access 16-element Array{Array{Float64,1},1} at index [16:30]
```

**Comment by mforets** [comment]
i propose to disable plotting sets of higher dimensions with an assertion at the beginning of each plot recipe (it already exists for `AbstractPolytope`).

**Comment by schillic** [comment]
The question was about `vertices_list`, not about `plot` :wink:
I agree that we should assert the dimensionality. I added that to the list in #237.

**Comment by schillic** [comment]
Or we just let the user convert to `HPolytope` first, which actually makes more sense to me.
I think we first need to define what `vertices_list` should return for a polyhedron. I can think of returning all the vertices where the polyhedron is bounded (but the set is *not* the convex hull of those vertices). If we cannot find a definition, we should rather not offer this method at all.
