### ISSUE TITLE
ρ crashes for AbstractFloat types and rational direction

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#86]
We have `ρ(d::AbstractVector{N}, S::LazySet)::N where {N<:Real}`.
This will crash for `Ball2`, even with rational direction. None of the below work:
```julia
ρ([1//1], Ball2([1//1], 1//1))
σ([1//1], Ball2([1//1], 1//1))
ρ([1//1], Ball2(1., 1.))
σ([1//1], Ball2(1., 1.))
```
The problem is that `Ball2` (and `Ballp`) is only really usable with `AbstractFloat` types.
I guess there is no way around. Should we instead require that these types cannot even be created with numeric types that are above `AbstractFloat`? At least this would avoid confusion.

**Comment by mforets** [comment]
Yes, we wrote the note "Exact inputs are not supported." [here](https://github.com/JuliaReach/LazySets.jl/blob/master/src/Ball2.jl#L103). We can just let it be `N<:AbstractFloat` in the constructor.
