### ISSUE TITLE
Move imports/exports to one place

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#874]
I suggest to move `import`/`export` statements to only one file (the module's main file).
* Currently we *sometimes* (for example) `import Base.∈` in files where we override that function, but this is not consistent.
* I find it helpful to have a place where you can see all functions and types that the package provides and overrides.

**Comment by mforets** [comment]
See also https://github.com/JuliaReach/LazySets.jl/issues/452.

For the `export`'s,  i dislike to include statements in the file `LazySets.jl` for that there are so many names that it will become messy, compared to the current state where one clearly sees all `includes` of the set types and operations. Then, one sees on top of each each set file the methods that are exported by that type. That said, the methods that are mandatory (methods required by the interface) shouldn't need to be included in the set's type export (on top). 

For `import`, i agree with the suggestion of putting them in `LazySets.jl`, but i'm also fine with the current status. In the former case there will be like 10-15 methods that are imported from `Base`. Some others are imported from `IntervalArithmetic` or from `Polyhedra` (but these could be kept in the current files).
