### ISSUE TITLE
Accept parametric number types

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#9]
It can be interesting to accept parametric number types so that we can work with:

- rationals (slower but exact)
- single precision (less precise but faster)
- complex numbers (eg. for [complex zonotopes](https://sites.google.com/site/arvind23adi/research/complex-zonotope))

**Comment by schillic** [comment]
This is also suggested in a [Julia design style guide section](https://docs.julialang.org/en/stable/manual/style-guide/#Avoid-using-floats-for-numeric-literals-in-generic-code-when-possible-1).

**Comment by schillic** [comment]
Then again, this is frowned upon in [the performance tips](https://docs.julialang.org/en/stable/manual/performance-tips/#Avoid-containers-with-abstract-type-parameters-1).

**Comment by mforets** [comment]
> Then again, this is frowned upon in the performance tips.

that's probably about

```julia
struct Ball2 <: LazySet
    center::Vector{AbstractFloat}
    radius::AbstractFloat
    Ball2(center, radius) = radius < 0. ? throw(DomainError()) : new(center, radius)
end
```
(bad idea), versus

```julia
struct Ball2{T} <: LazySet where {T<:Real}
    center::Vector{T}
    radius::T
    Ball2(center, radius) = radius < 0. ? throw(DomainError()) : new(center, radius)
end
```
which won't impact performance and still be generic.

see also: [julia gotchas handle](http://www.stochasticlifestyle.com/7-julia-gotchas-handle/), and [package example](https://github.com/ChrisRackauckas/ExamplePackage.jl/blob/master/src/output_string.jl)

**Comment by schillic** [comment]
What would be a good type abbreviation? For instance `N`umber or `F`loat?
We are not bound to a single letter, but I think it is convenient.

**Comment by mforets** [comment]
i've seen a lot of `N` for number types. for a case such as say, `Ball2` or `BallInf` we can use `N <: Real`: this includes `AbstractFloat` and also `Rational`'s.

for operators like `CartesianProduct`, `ConvexHull` we don't need to add anything at all, right? seems like there are other operators such as `LinearMap` where we should better use `AbstractMatrix{N}` and `where{N}` on the type's signature, that is without saying anything (`Any`). this is because i have in mind linear maps which contains interval coefficients (or even `LazySets`).

**Comment by schillic** [comment]
Correct, for now I only add the type argument to base set types.
And I chose `N`, very good :)

However, we probably also want to make methods such as `σ` to return the new type (otherwise this whole thing is useless).
Currently we have the following method for every `SomeLazySetType`:
```julia
function σ(d::AbstractVector{Float64}, S::SomeLazySetType)::Vector{Float64}
```
And I do not know if it will work out of the box if we just write `N` here.
For this to work, I guess we have two options how to infer the return type:
1. Make it the same as the input type (`d`).
2. Make it the same as the LazySet type (`S`).
3. Intersection of 1. and 2.: Make sure that input type and LazySet type coincide (makes perfect sense to me).

In cases 2. and 3. we also need that the operators such as `ConvexHull` have a number type.

**Comment by mforets** [comment]
IIUC, in those cases (that we don't need the type information inside the function), we can just write:

```
function σ(d::AbstractVector, S::SomeLazySetType)::Vector
```
(or even `σ(d, S)`), without an impact on the performance.

**Comment by schillic** [comment]
Okay, but then we have no type checking features.
What if the user calls the function with a `Rational` direction and a `Float64` set?
But I am fine with "this is the user's problem" :)

**Comment by mforets** [comment]
oh, i see what you mean. in that case this function i wrote above (without `N`) will get compiled and the resulting number type of `Vector` really depends on what is going on inside the function, or in other words, cannot be determined by the function's signature. doesn't seem like a good idea!

then take:

```
function σ(d::AbstractVector{N}, B::BallInf)::Vector{N} where{N<:Real}
    return B.center .+ unit_step.(d) .* B.radius
end
```

**Comment by schillic** [comment]
But this implies that the set also uses the `N` type, right?
As I said, I am ok with not adding a type and let it crash if the types do not match.
But I imagine that under the hood Julia just promotes types.
So we might expect a `Rational` computation but in fact Julia goes down to `Float64`, does the computation, and promotes back to `Rational` for the result.
But I do not know this for sure.
And, as I said, this is the user's fault.

**Comment by mforets** [comment]
> But this implies that the set also uses the N type, right?

yes

i think we should guarantee that: if in a reachability computation the input set is say, rational, then the computation will be carried over by rational. how we can enable this? maybe non-annotation of `N` in `σ` is just fine. hmm..

**Comment by schillic** [comment]
I just fear that we forget to parameterize at one place and then everything breaks.
Or, if Julia just auto-promotes, we will never find out.
But yes, let us go for the type-less version.

**Comment by schillic** [comment]
The first version is there, just has no meaning yet.

I removed the empty constructor for `VPolygon`.

**Comment by mforets** [comment]
> I removed the empty constructor for VPolygon.

thx for finding out that it currently breaks :) i'm not sure that we'll need to instantiate a VPolygon with no vertices in it; it's a possibility but maybe not too useful.

**Comment by schillic** [comment]
I am thinking if we want to drop those type asserts (I know, I wanted them).
It can be seen as a feature that we allow to multiply rational vectors with float sets.
We actually do support mixed set combinations in a `CartesianProduct` etc.

**Comment by mforets** [comment]
> I am thinking if we want to drop those type asserts (I know, I wanted them).

where exactly? 

in a case like matrix times set, instead of:

```
function *(M::AbstractMatrix{N}, sf::VoidSet) where {N<:Real}
..
end
```

i'd use: 

```
function *(M::AbstractMatrix, sf::VoidSet)
..
end
```

because we can have matrix with non-numeric types eg. an interval

**Comment by schillic** [comment]
The one you suggested [above](https://github.com/JuliaReach/LazySets.jl/issues/9#issuecomment-344717184).

**Comment by schillic** [comment]
Do we want to have a type constraint for `is_contained`?
```julia
function is_contained(x::AbstractVector{<:Real}, S::MySet)::Bool
```
vs.
```julia
function is_contained(x::AbstractVector, S::MySet)::Bool
```

**Comment by schillic** [comment]
There are functions we have to investigate such as:
```julia
julia> norm([1//1, 1//1])
1.4142135623730951
```
This particular case prevents using rationals in `σ` for `Ball2` etc.

**Comment by schillic** [comment]
I should have done all the changes except in the "function files" that do not contain any sets, and in `ExponentialMap.jl`.
@mforets: Can you have a look there?

Careful: We have to add a type to an empty `HPolygon` constructor now, so you have to do, e.g., `HPolygon{Float64}()`!

**Comment by schillic** [comment]
> we should be able to make it default to Float64, no? it's too much to have to write Float64 all the time

Done.

**Comment by mforets** [comment]
> This particular case prevents using rationals in σ for Ball2 etc.

for `BallInf` it is ok:

```julia
julia> b = BallInf([1//2, 3//2], 1//1)
LazySets.BallInf{Rational{Int64}}(Rational{Int64}[1//2, 3//2], 1//1)
julia> σ([6//7, 4//3], b)
2-element Array{Rational{Int64},1}:
 3//2
 5//2
```

but for `Ball2` we fall back to `Float64`:

```julia
julia> b = Ball2([1//2, 3//2], 1//1)
LazySets.Ball2{Rational{Int64}}(Rational{Int64}[1//2, 3//2], 1//1)

julia> σ([6//7, 4//3], b)
2-element Array{Float64,1}:
 1.04076
 2.34118
```

yes, that's because the supp func of a 2-ball involves the 2-norm that uses square roots. to solve that may entail working with something like [this package](https://github.com/anj1/AlgebraicNumbers.jl). i don't think we need this feature soon though.

**Comment by mforets** [comment]
### Summary

We set out to transform the hardcoded precision `Float64` to work in arbitrary precision but still with no loss in effiicency, by using Julia's parametric types mechanism.

This first implementation was limited to defining `Real` and `AbstractFloat` and turning all lazy sets numerical types into these parametric types (`N`). This happens basically in two areas:

- symbolics: constructors, nested lazy operations, etc.
- calcuations: support vector computations.

The aim is that the output support vector is an element of the given set *in the same precision.* One difficulty that we encountered is that some operations require to make a conversion that breaks the precision, eg. `Ball2` support vector which requires computing square roots. In such cases, we decided to limit the behavior of support vector to the arguments with correct behavior, i.e. `AbstractFloat`.
