### ISSUE TITLE
isdisjoint check with polyhedron is incorrect

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#902]
Bug report from [here](https://github.com/JuliaReach/LazySets.jl/issues/754#issuecomment-437387436):

[The following function](https://github.com/JuliaReach/LazySets.jl/blob/71a9bd44723047434a0a63c14013a00f764b4865/src/is_intersection_empty.jl#L865) is bugged:
```julia
function is_intersection_empty(P::Union{HPolyhedron{N}, HPolytope{N}, AbstractHPolygon{N}},
                               Q::Union{HPolyhedron{N}, HPolytope{N}, AbstractHPolygon{N}})
```
We take the constraints of `P` and intersect with `Q`. If `Q` is a polyhedron, this intersection may fail. We should prefer the bounded sets for the role of `Q`.

**Comment by schillic** [comment]
See #1039 for a concrete example.

**Comment by mforets** [comment]
example [here](https://github.com/JuliaReach/LazySets.jl/issues/1039#issue-401129705)
