### ISSUE TITLE
swap using order in some places

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#903]
```julia
$ julia -e '@time using Plots, LazySets'
 10.518915 seconds (19.45 M allocations: 1.016 GiB, 5.02% gc time)
$ julia -e '@time using LazySets, Plots'
 12.476767 seconds (22.38 M allocations: 1.153 GiB, 5.29% gc time)
```

**Comment by schillic** [comment]
Any idea about this behavior? It does not make sense to me.

**Comment by mforets** [comment]
I saw it [here](https://github.com/JuliaPlots/Plots.jl/issues/1825#issuecomment-434615563), and this behavior is related to merging the [method tables](https://docs.julialang.org/en/v1/devdocs/functions/index.html#Method-Tables-1) of each pkg (see other comment in the same issue).
