### ISSUE TITLE
Sampling from a set

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#917]
Add a method `sample` to sets. See #870 for how to handle RNG.

**Comment by mforets** [comment]
To sample a Ball2, see https://github.com/JuliaReach/LazySets.jl/pull/1503.

An example:

```julia
B1 = Ball2([-1.0, 2.0], 2.0)
B2 = Ball2([1.0, 0.5], 0.5)
plot([B1, B2])
plot!([Singleton(si) for si in sample(B1, 400)], aspectratio=1)
plot!([Singleton(si) for si in sample(B2, 600)], aspectratio=1)
```

<img width="516" alt="Screen Shot 2019-07-05 at 10 40 23" src="https://user-images.githubusercontent.com/12424594/60726190-5de41580-9f11-11e9-9be9-2242beb21cd2.png">

**Comment by mforets** [comment]
Other `sample` instances that could be implemented:

- hyperrectangular sets
- ellipsoids
- polytopes

**Comment by mforets** [comment]
[Rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling) is good as a (very general) fallback, since it only needs `LazySets.Approximations.box_overapproximation`.

**Comment by ueliwechsler** [comment]
Can you assign this issue to me?
I would just add my sampling code as a general fallback for an arbitrary `LazySet`.

**Comment by schillic** [comment]
I added #1589 to keep this meta issue open. But I cannot assign you there :cry:

**Comment by mforets** [comment]
To sample from `BallInf`'s, this package could be applied: https://github.com/stevengj/Sobol.jl

**Comment by schillic** [comment]
> To sample from BallInf's, this package could be applied: https://github.com/stevengj/Sobol.jl

Interesting, but I would make this optional because you may instead want to obtain a random sequence.

**Comment by schillic** [comment]
I outsourced the remaining proposal to a more concrete issue.
