### ISSUE TITLE
Make VPolygon's vertices field be abstract

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#927]
```julia
using LazySets, StaticVectors

julia> VPolygon([@SVector(rand(2)) for i in 1:3])
ERROR: MethodError: Cannot `convert` an object of type Array{SArray{Tuple{2},Float64,1,2},1} to an object of type VPolygon
Closest candidates are:
  convert(::Type{VPolygon}, ::AbstractHPolygon) at /Users/forets/.julia/dev/LazySets/src/convert.jl:65
  convert(::Type{VPolygon}, ::AbstractPolytope) at /Users/forets/.julia/dev/LazySets/src/convert.jl:119
  convert(::Type{T}, ::T) where T at essentials.jl:154
Stacktrace:
 [1] VPolygon(::Array{SArray{Tuple{2},Float64,1,2},1}) at ./deprecated.jl:473
 [2] top-level scope at none:0
```

**Comment by schillic** [comment]
I do not understand the suggestion.

**Comment by mforets** [comment]
To change the field `vertices::Vector{Vector{N}}` so something like `vertices::Vector{AbstractVector{N}}`  such that the points in the vpolygon can be represented by any abstract vector (but possibly concretely typed, so a new type should be added to the type),

**Comment by schillic** [comment]
Okay, I agree, but some comments:
1. Why only generalize the inner vector type?
2. Is there something special about `VPolygon` that we only want to generalize the type here? What about `VPolytope` for instance?
3. I do not know if it makes sense to make this type visible as a type parameter. I cannot think of a use case where you want to dispatch on this type. So `AbstractVector` is sufficient from my side.

**Comment by schillic** [comment]
> The outer container may be kept as a usual vector, no?

Why? :smiley:
I can think of a case where you want to pass a `SubArray` (from "`view`") for instance. Or maybe even an iterator that creates the vertices on-the-fly.
But I understand that then we would have to change a lot of types.

> not so suited for holding a large number of vectors

I do not expect that in 2D you have a large number anyway.

> 3

Okay, I was not sure anymore if it had impact on efficiency. In that case of course we should add a type parameter.

Note that at some places we may have the assumption that the type of points is `Vector{N}` (for instance in some return types) (but I did not check). This would have to be adapted.
