### ISSUE TITLE
Document interfaces

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#93]
- `LazySet` interfaces should be upgraded to its proper section under /Library/
- a picture of the hierarchy would be nice

**Comment by schillic** [comment]
[Here](https://www.dropbox.com/sh/nsmq3sngkqnhgxo/AACKxKvOJCJCoWixnnE-itYda?dl=0) is a temporary candidate for the type hierarchy.

**Comment by mforets** [comment]
and if we only keep the yellow boxes? i suggest to not show the concrete types in this diagram

**Comment by schillic** [comment]
Alright
