### ISSUE TITLE
convex_hull method for VPolygon

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#949]
Currently a user has to unwrap the vertices of a `VPolygon` to apply the `convex_hull` method.

**Comment by schillic** [comment]
Thinking about it, it does not really make sense to apply a convex hull to a single set. The method should rather be called `remove_redundancy` or something like that. In the background this can call to `convex_hull`, but a user would not have to know that.

**Comment by mforets** [comment]
PR https://github.com/JuliaReach/LazySets.jl/pull/953 adds `remove_redundant_vertices(::VPolygon)` (and the in-place version), and also `convex_hull(::VPolygon, ::VPolygon)`.
