### ISSUE TITLE
Revise convex_hull

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#950]
The concrete `convex_hull` methods are currently documented all in one place. I think we should add individual docs to each method.
Note that we have unary and binary versions of this method. The binary versions should go to `binary_functions.md`.
Also, should we reorganize the binary methods into the file `convex_hull_algorithms.jl`, or maybe into a new file `concrete_convex_hull.jl`? This could simplify working on #948 and #949 to catch method ambiguities.
We also need to add that function to our ambiguity tests (`unit_binary_operations.jl`).

**Comment by mforets** [comment]
> Also, should we reorganize the binary methods into the file convex_hull_algorithms.jl, or maybe into a new file concrete_convex_hull.jl?

👍  I have thought of reorganizing the library into subfolders in the past (`convex_hull.jl` is not a problem but `intersection.jl` vs `Intersection.jl` is a problem). I agree to either use subfolders or rename `concrete_...` 

- `concrete_intersection.jl`
- `concrete_convex_hull.jl`
- `concrete_minkowski_sum.jl` (to be added)
...

I'm preparing a PR with the renaming `concrete_convex_hull.jl`.

**Comment by schillic** [comment]
I think the suggested steps have been resolved by now.
