### ISSUE TITLE
Add dummy for functions required in interfaces

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#951]
The following should be true but it is not:

```julia
julia> hasmethod(vertices_list, Tuple{AbstractPolytope})
false
```

Proposal: add the dummy function:

```julia
function vertices_list(::AbstractPolytope) end
```

**Comment by schillic** [comment]
The problem is that [our check](https://github.com/JuliaReach/LazySets.jl/blob/ae4e196f3513299c7650382faefcc5c8dbf0ac62/test/check_method_implementation.jl#L76) for whether a function implements the interface methods uses `hasmethod`. If we add that, this check will always return `true`.

**Comment by mforets** [comment]
Ok, i see. I vote for closing this issue then.
