### ISSUE TITLE
Unary convex hull for VPolytope

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#952]
Proposal: add the same methods as that proposed in https://github.com/JuliaReach/LazySets.jl/issues/949 but for a `VPolytope`.

**Comment by schillic** [comment]
See my comment in the linked issue.

**Comment by mforets** [comment]
PR https://github.com/JuliaReach/LazySets.jl/pull/953 adds `remove_redundant_vertices(::VPolytope)` and `convex_hull(::VPolytope, ::VPolytope)`.
