### ISSUE TITLE
Add concrete and abstract traits

### ISSUE THREAD

**Issue by mforets** [JuliaReach/LazySets.jl#991]
Proposal: add methods to differentiate between concrete set types and interfaces, and (maybe) operations.

This functionality is useful to apply an operation on any concrete type, for example.

Note that Julia's `Base` has `isconcretetype` and `isabstracttype`, and they behave like this:
 
```julia
julia> isconcretetype(HalfSpace)
false

julia> isconcretetype(AbstractSingleton)
false

julia> isabstracttype(AbstractSingleton)
true

julia> isconcretetype(HalfSpace{Float64})
```

The function's names could be some of `isconcrete` / `isabstract` / `isconcreteset` / `isabstractset`.

**Comment by schillic** [comment]
I like it. What about `isinterface`/`isabstract`, `isconcrete`, and `islazy`? The suffix `set` is okay but not needed.

**Comment by mforets** [comment]
I like the name `isinterface` because it has a clear meaning in LazySets (https://juliareach.github.io/LazySets.jl/latest/lib/interfaces.html). So we would add 3 functions, `isinterface`, `isconcrete` and `islazy`.

**Comment by schillic** [comment]
Note that one cannot create an object of abstract type, so the `isinterface` function seems rather useless.

**Comment by mforets** [comment]
what do you think about adding `isoperation()` that returns `true` for eg. `LinearMap` and `false` for eg. `BallInf`? this would partially solve this issue.

**Comment by schillic** [comment]
`isoperation` sounds good!

**Comment by schillic** [comment]
Given that Julia's `isabstracttype` can be used to check for abstract types and `isoperation(type)` in #1734 can be used to check for lazy and concrete set types (by negation), I think we have covered everything here.
