### ISSUE TITLE
Add common polytopic methods to lazy operations

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#996]
For instance we have `vertices_list`, `constraints_list`, and `linear_map` for concrete-type polytopes but often not for lazy operations. The idea is to add these methods and just fall back to the definitions on the wrapped sets. See [this comment](https://github.com/JuliaReach/LazySets.jl/issues/941#issuecomment-448195948) for a list of `vertices_list` implementations. Sometimes the implementation is not trivial, e.g., see #675 for how to implement it for `MinkowskiSum`.

**Comment by mforets** [comment]
Would this definition make sense? `ispolytopic(X) = applicable(vertices_list, X) && isbounded(X)`

Then we can write generic fallbacks, eg. 

```julia
function convert(VPolygon, X)
    if ispolytopic(X) && dim(X) == 2
        return VPolygon(vertices_list(X))
    else
         throw(ArgumentError(...))
    end
end
```

**Comment by schillic** [comment]
> Would this definition make sense?

Yes, but that was not the point of this issue and is rather something that is enabled by it.

**Comment by mforets** [comment]
True, thanks. We have a couple of related issues about fallbacks; perhaps my comment was how i would like to implement https://github.com/JuliaReach/LazySets.jl/issues/1387.

**Comment by mforets** [comment]
For linear map, we could add the implementation that takes the constraints list of the cartesian product (https://github.com/JuliaReach/LazySets.jl/pull/2194/files#diff-ace1e54fabcf477ffe72b37d1fb1baeeR277)
