### ISSUE TITLE
Add vertices_list for HPolyhedron

### ISSUE THREAD

**Issue by schillic** [JuliaReach/LazySets.jl#998]
Currently we throw an error. However, the implementation for `HPolytope` works for unbounded polytopes and does what you would expect.
I think we have decided to not support vertices of polyhedra, but since it is so easy, should we support it?
```julia
julia> using LazySets, Polyhedra

julia> constraints = [LazySets.HalfSpace([1., 0.], 0.), LazySets.HalfSpace([0., 1.], 0.)];

julia> vertices_list(HPolyhedron(constraints))
ERROR: ArgumentError: the list of vertices of a (possibly unbounded) polyhedron is not
 defined; if the polyhedron is bounded, try converting to `HPolytope` first
Stacktrace:
 [1] vertices_list(::HPolyhedron{Float64}) at LazySets/src/HPolyhedron.jl:631
 [2] top-level scope at none:0

julia> vertices_list(HPolytope(constraints))
1-element Array{Array{Float64,1},1}:
 [0.0, 0.0]
```

**Comment by mforets** [comment]
I agree to let `vertices_list(::HPolyhedron)` work too.

**Comment by schillic** [comment]
We can use this implementation in the (currently) undefined case of [`linear_map(::HPolyhedron)`](https://github.com/JuliaReach/LazySets.jl/pull/980/files#diff-795b585c4704738125c4e81ad4bff018R527).

**Comment by schillic** [comment]
> We can use this implementation in the (currently) undefined case of linear_map(::HPolyhedron).

However, adding `vertices_list` is not a good idea because we would usually assume that the original set is the convex hull of the vertices (for instance the mentioned `linear_map`).
I changed my mind and vote for choosing a different name for the `vertices_list(::HPolyhedron)` method or for adding another method for polytopes that is identical to `vertices_list` but does not exist for `HPolyhedron` (which we then have to use internally).

**Comment by schillic** [comment]
Usually the `vertices_list` method is defined and more efficient than going to H-rep first.
We should now of course define `vertices_list` in `AbstractPolyhedron_functions.jl`, exactly as you defined it here.
```julia
function vertices_list(P::AbstractPolyhedron{N}; check_boundedness::Bool=true) where {N<:Real}
    if check_boundedness && !isbounded(P)
        throw ArgumentError("polyhedra need to be bounded to obtain their vertices")
    end
    return vertices_list(HPolytope(constraints_list(P), check_boundedness=false)))
end
```

_Originally posted by @schillic in https://github.com/JuliaReach/LazySets.jl/timeline_

**Comment by mforets** [comment]
we should update the linear map function (and docstring, in the `Vertex representation` part) when this method is available -- cf. [this comment](https://github.com/JuliaReach/LazySets.jl/pull/1950#discussion_r381411946)
